import {
  faBackward,
  faBacon,
  faBinoculars,
  faBurger,
  faCamera,
  faCameraRetro,
  faCandyCane,
  faChessBishop,
  faChessBoard,
  faChessKing,
  faChessPawn,
  faChessQueen,
  faChessRook,
  faCircleStop,
  faClapperboard,
  faClosedCaptioning,
  faCompactDisc,
  faCookieBite,
  faDice,
  faDiceD20,
  faDiceD6,
  faDiceSix,
  faDragon,
  faDrum,
  faDrumSteelpan,
  faFillDrip,
  faFilm,
  faForward,
  faForwardFast,
  faGamepad,
  faGhost,
  faGuitar,
  faHatWizard,
  faHeadphones,
  faHollyBerry,
  faHotdog,
  faIceCream,
  faIcons,
  faImages,
  faMartiniGlass,
  faMartiniGlassCitrus,
  faMasksTheater,
  faMicrophoneLines,
  faMusic,
  faPaintbrush,
  faPalette,
  faPanorama,
  faPause,
  faPhotoFilm,
  faPictureInPicture,
  faPizzaSlice,
  faRadio,
  faRecordVinyl,
  faShuttleSpace,
  faSleigh,
  faSnowman,
  faSprayCan,
  faStroopwafel,
  faSwatchbook,
  faTicket,
  faTicketSimple,
  faTv,
  faUmbrellaBeach,
  faVolumeHigh,
  faVolumeLow,
  faVolumeXmark,
  faWandSparkles,
  faWhiskeyGlass,
  faWineBottle,
  faWineGlassEmpty,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const entertainmentIcons = [
  { name: 'music', label: 'Música', category: 'entertainment', icon: faMusic, keywords: ['canción', 'audio', 'playlist', 'piano', 'teclado musical', 'bailar', 'baile', 'cantar'] },
  { name: 'guitar', label: 'Guitarra', category: 'entertainment', icon: faGuitar, keywords: ['instrumento', 'música', 'práctica', 'guitarra', 'acordes', 'bajo'] },
  { name: 'headphones', label: 'Auriculares', category: 'entertainment', icon: faHeadphones, keywords: ['música', 'audio', 'escuchar', 'cascos'] },
  { name: 'film', label: 'Cine', category: 'entertainment', icon: faFilm, keywords: ['película', 'video', 'series', 'cine', 'peli'] },
  { name: 'clapperboard', label: 'Rodaje', category: 'entertainment', icon: faClapperboard, keywords: ['cine', 'video', 'contenido', 'grabar', 'claqueta'] },
  { name: 'camera', label: 'Cámara', category: 'entertainment', icon: faCamera, keywords: ['foto', 'fotografía', 'creativo', 'cámara', 'retratar'] },
  { name: 'palette', label: 'Arte', category: 'entertainment', icon: faPalette, keywords: ['pintura', 'diseño', 'creatividad', 'draw', 'pintar', 'colores'] },
  { name: 'gamepad', label: 'Gaming', category: 'entertainment', icon: faGamepad, keywords: ['juegos', 'videojuegos', 'gaming', 'play', 'consola', 'mando'] },
  { name: 'dice', label: 'Juego', category: 'entertainment', icon: faDice, keywords: ['azar', 'board game', 'ocio', 'dados', 'juego de mesa'] },
  { name: 'tv', label: 'Televisión', category: 'entertainment', icon: faTv, keywords: ['series', 'streaming', 'pantalla', 'tele', 'televisión'] },
  { name: 'pizza-slice', label: 'Pizza', category: 'entertainment', icon: faPizzaSlice, keywords: ['comida', 'cena', 'ocio', 'restaurante', 'pizza'] },
  { name: 'masks-theater', label: 'Teatro', category: 'entertainment', icon: faMasksTheater, keywords: ['drama', 'actuación', 'cultura', 'show', 'teatro', 'máscaras'] },
  { name: 'record-vinyl', label: 'Vinilo', category: 'entertainment', icon: faRecordVinyl, keywords: ['vinilo', 'disco', 'música', 'tocadiscos', 'dj'] },
  { name: 'compact-disc', label: 'Disco', category: 'entertainment', icon: faCompactDisc, keywords: ['cd', 'disco', 'álbum', 'música'] },
  { name: 'drum', label: 'Batería', category: 'entertainment', icon: faDrum, keywords: ['batería', 'tambor', 'percusión', 'instrumento', 'ritmo'] },
  { name: 'microphone-lines', label: 'Cantar', category: 'entertainment', icon: faMicrophoneLines, keywords: ['cantar', 'karaoke', 'micro', 'voz', 'canto'] },
  { name: 'radio', label: 'Radio', category: 'entertainment', icon: faRadio, keywords: ['radio', 'emisora', 'escuchar', 'programa'] },
  { name: 'photo-film', label: 'Fotos y vídeo', category: 'entertainment', icon: faPhotoFilm, keywords: ['fotos', 'vídeo', 'galería', 'multimedia', 'editar'] },
  { name: 'images', label: 'Galería', category: 'entertainment', icon: faImages, keywords: ['fotos', 'galería', 'imágenes', 'álbum', 'recuerdos'] },
  { name: 'camera-retro', label: 'Cámara analógica', category: 'entertainment', icon: faCameraRetro, keywords: ['cámara', 'analógica', 'vintage', 'fotografía', 'carrete'] },
  { name: 'ticket', label: 'Entradas', category: 'entertainment', icon: faTicket, keywords: ['entrada', 'ticket', 'concierto', 'evento', 'espectáculo'] },
  { name: 'paintbrush', label: 'Pintar', category: 'entertainment', icon: faPaintbrush, keywords: ['pincel', 'pintar', 'acuarela', 'arte', 'cuadro'] },
  { name: 'spray-can', label: 'Grafiti', category: 'entertainment', icon: faSprayCan, keywords: ['grafiti', 'spray', 'street art', 'arte urbano', 'pintar'] },
  { name: 'dice-d20', label: 'Juego de rol', category: 'entertainment', icon: faDiceD20, keywords: ['rol', 'dados', 'dnd', 'partida', 'mesa'] },
  { name: 'ghost', label: 'Terror', category: 'entertainment', icon: faGhost, keywords: ['terror', 'fantasma', 'miedo', 'halloween', 'peli'] },
  { name: 'dragon', label: 'Fantasía', category: 'entertainment', icon: faDragon, keywords: ['fantasía', 'dragón', 'épico', 'rol', 'novela'] },
  { name: 'hat-wizard', label: 'Magia', category: 'entertainment', icon: faHatWizard, keywords: ['magia', 'mago', 'sombrero', 'fantasía', 'truco'] },
  { name: 'shuttle-space', label: 'Ciencia ficción', category: 'entertainment', icon: faShuttleSpace, keywords: ['espacio', 'cohete', 'ciencia ficción', 'nave', 'astronauta'] },
  { name: 'binoculars', label: 'Explorar', category: 'entertainment', icon: faBinoculars, keywords: ['explorar', 'prismáticos', 'observar', 'aves', 'descubrir'] },
  { name: 'umbrella-beach', label: 'Playa', category: 'entertainment', icon: faUmbrellaBeach, keywords: ['playa', 'vacaciones', 'sombrilla', 'descanso', 'verano'] },
  { name: 'burger', label: 'Hamburguesa', category: 'entertainment', icon: faBurger, keywords: ['hamburguesa', 'comida', 'capricho', 'fast food', 'cena'] },
  { name: 'ice-cream', label: 'Helado', category: 'entertainment', icon: faIceCream, keywords: ['helado', 'postre', 'dulce', 'verano', 'capricho'] },
  { name: 'cookie-bite', label: 'Dulce', category: 'entertainment', icon: faCookieBite, keywords: ['galleta', 'dulce', 'postre', 'capricho', 'merienda'] },
  { name: 'martini-glass-citrus', label: 'Cóctel', category: 'entertainment', icon: faMartiniGlassCitrus, keywords: ['cóctel', 'copa', 'bebida', 'fiesta', 'combinado'] },
  { name: 'chess-king', label: 'Ajedrez: rey', category: 'entertainment', icon: faChessKing, keywords: ['ajedrez', 'rey', 'partida', 'estrategia'] },
  { name: 'chess-queen', label: 'Ajedrez: dama', category: 'entertainment', icon: faChessQueen, keywords: ['ajedrez', 'dama', 'partida', 'estrategia'] },
  { name: 'chess-rook', label: 'Ajedrez: torre', category: 'entertainment', icon: faChessRook, keywords: ['ajedrez', 'torre', 'partida', 'estrategia'] },
  { name: 'chess-bishop', label: 'Ajedrez: alfil', category: 'entertainment', icon: faChessBishop, keywords: ['ajedrez', 'alfil', 'partida', 'estrategia'] },
  { name: 'chess-pawn', label: 'Ajedrez: peón', category: 'entertainment', icon: faChessPawn, keywords: ['ajedrez', 'peón', 'partida', 'estrategia'] },
  { name: 'chess-board', label: 'Tablero', category: 'entertainment', icon: faChessBoard, keywords: ['ajedrez', 'tablero', 'juego', 'mesa'] },
  { name: 'dice-six', label: 'Dado', category: 'entertainment', icon: faDiceSix, keywords: ['dado', 'juego', 'azar', 'mesa'] },
  { name: 'dice-d6', label: 'Dado de rol', category: 'entertainment', icon: faDiceD6, keywords: ['dado', 'rol', 'juego', 'mesa'] },
  { name: 'ticket-simple', label: 'Entrada', category: 'entertainment', icon: faTicketSimple, keywords: ['entrada', 'ticket', 'cine', 'concierto'] },
  { name: 'picture-in-picture', label: 'Pantalla flotante', category: 'entertainment', icon: faPictureInPicture, keywords: ['vídeo', 'pantalla', 'ver', 'serie'] },
  { name: 'closed-captioning', label: 'Subtítulos', category: 'entertainment', icon: faClosedCaptioning, keywords: ['subtítulos', 'ver', 'serie', 'idioma'] },
  { name: 'volume-high', label: 'Volumen alto', category: 'entertainment', icon: faVolumeHigh, keywords: ['volumen', 'sonido', 'audio', 'música'] },
  { name: 'volume-low', label: 'Volumen bajo', category: 'entertainment', icon: faVolumeLow, keywords: ['volumen', 'bajo', 'sonido'] },
  { name: 'volume-xmark', label: 'Sin volumen', category: 'entertainment', icon: faVolumeXmark, keywords: ['silencio', 'mute', 'sonido', 'apagar'] },
  { name: 'pause', label: 'Pausa', category: 'entertainment', icon: faPause, keywords: ['pausa', 'parar', 'descanso', 'reproducir'] },
  { name: 'forward', label: 'Avanzar', category: 'entertainment', icon: faForward, keywords: ['avanzar', 'adelantar', 'reproducir'] },
  { name: 'backward', label: 'Retroceder', category: 'entertainment', icon: faBackward, keywords: ['retroceder', 'atrás', 'reproducir'] },
  { name: 'forward-fast', label: 'Adelantar rápido', category: 'entertainment', icon: faForwardFast, keywords: ['adelantar', 'rápido', 'reproducir'] },
  { name: 'circle-stop', label: 'Parar', category: 'entertainment', icon: faCircleStop, keywords: ['parar', 'stop', 'detener', 'reproducir'] },
  { name: 'drum-steelpan', label: 'Percusión', category: 'entertainment', icon: faDrumSteelpan, keywords: ['tambor', 'percusión', 'música', 'tocar'] },
  { name: 'wand-sparkles', label: 'Magia', category: 'entertainment', icon: faWandSparkles, keywords: ['magia', 'varita', 'truco', 'fantasía'] },
  { name: 'swatchbook', label: 'Muestrario de color', category: 'entertainment', icon: faSwatchbook, keywords: ['color', 'muestras', 'paleta', 'diseño'] },
  { name: 'fill-drip', label: 'Rellenar de color', category: 'entertainment', icon: faFillDrip, keywords: ['color', 'pintar', 'relleno', 'diseño'] },
  { name: 'icons', label: 'Iconos', category: 'entertainment', icon: faIcons, keywords: ['iconos', 'diseño', 'símbolos'] },
  { name: 'panorama', label: 'Panorámica', category: 'entertainment', icon: faPanorama, keywords: ['panorámica', 'foto', 'paisaje', 'fotografía'] },
  { name: 'martini-glass', label: 'Copa', category: 'entertainment', icon: faMartiniGlass, keywords: ['copa', 'cóctel', 'bebida', 'fiesta'] },
  { name: 'whiskey-glass', label: 'Whisky', category: 'entertainment', icon: faWhiskeyGlass, keywords: ['whisky', 'copa', 'bebida', 'alcohol'] },
  { name: 'wine-bottle', label: 'Botella de vino', category: 'entertainment', icon: faWineBottle, keywords: ['vino', 'botella', 'cena', 'bebida'] },
  { name: 'wine-glass-empty', label: 'Copa vacía', category: 'entertainment', icon: faWineGlassEmpty, keywords: ['copa', 'vino', 'bebida', 'brindis'] },
  { name: 'hotdog', label: 'Perrito caliente', category: 'entertainment', icon: faHotdog, keywords: ['perrito', 'comida', 'capricho', 'calle'] },
  { name: 'bacon', label: 'Bacon', category: 'entertainment', icon: faBacon, keywords: ['bacon', 'desayuno', 'comida', 'capricho'] },
  { name: 'candy-cane', label: 'Caramelo', category: 'entertainment', icon: faCandyCane, keywords: ['caramelo', 'dulce', 'navidad', 'capricho'] },
  { name: 'stroopwafel', label: 'Gofre', category: 'entertainment', icon: faStroopwafel, keywords: ['gofre', 'dulce', 'postre', 'merienda'] },
  { name: 'sleigh', label: 'Trineo', category: 'entertainment', icon: faSleigh, keywords: ['trineo', 'navidad', 'invierno', 'fiesta'] },
  { name: 'snowman', label: 'Muñeco de nieve', category: 'entertainment', icon: faSnowman, keywords: ['nieve', 'invierno', 'muñeco', 'navidad'] },
  { name: 'holly-berry', label: 'Navidad', category: 'entertainment', icon: faHollyBerry, keywords: ['navidad', 'decoración', 'fiesta', 'invierno'] },
] as const satisfies readonly AppIconEntry[]
