import {
  faBinoculars,
  faBurger,
  faCamera,
  faCameraRetro,
  faClapperboard,
  faCompactDisc,
  faDiceD20,
  faDice,
  faDragon,
  faDrum,
  faFilm,
  faGamepad,
  faGhost,
  faGuitar,
  faHatWizard,
  faHeadphones,
  faIceCream,
  faImages,
  faMartiniGlassCitrus,
  faMasksTheater,
  faMicrophoneLines,
  faMusic,
  faPaintbrush,
  faPalette,
  faPhotoFilm,
  faPizzaSlice,
  faRadio,
  faRecordVinyl,
  faShuttleSpace,
  faSprayCan,
  faTicket,
  faTv,
  faUmbrellaBeach,
  faCookieBite,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const entertainmentIcons = [
  { name: 'music', label: 'Música', category: 'entertainment', icon: faMusic, keywords: ['canción', 'audio', 'playlist', 'piano', 'teclado musical', 'bailar', 'baile', 'cantar'] },
  { name: 'guitar', label: 'Guitarra', category: 'entertainment', icon: faGuitar, keywords: ['instrumento', 'música', 'práctica', 'guitarra', 'acordes', 'bajo'] },
  { name: 'headphones', label: 'Auriculares', category: 'entertainment', icon: faHeadphones, keywords: ['música', 'audio', 'escuchar', 'cascos'] },
  { name: 'film', label: 'Cine', category: 'entertainment', icon: faFilm, keywords: ['película', 'video', 'series', 'cine', 'peli'] },
  { name: 'clapperboard', label: 'Rodaje', category: 'entertainment', icon: faClapperboard, keywords: ['cine', 'video', 'contenido', 'grabar', 'claqueta'] },
  { name: 'camera', label: 'Cámara', category: 'entertainment', icon: faCamera, keywords: ['foto', 'fotografía', 'creativo', 'cámara', 'retratar'] },
  { name: 'palette', label: 'Arte', category: 'entertainment', icon: faPalette, keywords: ['pintura', 'diseño', 'creatividad', 'draw', 'pintar', 'colores'] },
  { name: 'gamepad', label: 'Gaming', category: 'entertainment', icon: faGamepad, keywords: ['juegos', 'videojuegos', 'gaming', 'play', 'consola', 'mando'] },
  { name: 'dice', label: 'Juego', category: 'entertainment', icon: faDice, keywords: ['azar', 'board game', 'ocio', 'dados', 'juego de mesa'] },
  { name: 'tv', label: 'Televisión', category: 'entertainment', icon: faTv, keywords: ['series', 'streaming', 'pantalla', 'tele', 'televisión'] },
  { name: 'pizza-slice', label: 'Pizza', category: 'entertainment', icon: faPizzaSlice, keywords: ['comida', 'cena', 'ocio', 'restaurante', 'pizza'] },
  { name: 'masks-theater', label: 'Teatro', category: 'entertainment', icon: faMasksTheater, keywords: ['drama', 'actuación', 'cultura', 'show', 'teatro', 'máscaras'] },
  { name: 'record-vinyl', label: 'Vinilo', category: 'entertainment', icon: faRecordVinyl, keywords: ['vinilo', 'disco', 'música', 'tocadiscos', 'dj'] },
  { name: 'compact-disc', label: 'Disco', category: 'entertainment', icon: faCompactDisc, keywords: ['cd', 'disco', 'álbum', 'música'] },
  { name: 'drum', label: 'Batería', category: 'entertainment', icon: faDrum, keywords: ['batería', 'tambor', 'percusión', 'instrumento', 'ritmo'] },
  { name: 'microphone-lines', label: 'Cantar', category: 'entertainment', icon: faMicrophoneLines, keywords: ['cantar', 'karaoke', 'micro', 'voz', 'canto'] },
  { name: 'radio', label: 'Radio', category: 'entertainment', icon: faRadio, keywords: ['radio', 'emisora', 'escuchar', 'programa'] },
  { name: 'photo-film', label: 'Fotos y vídeo', category: 'entertainment', icon: faPhotoFilm, keywords: ['fotos', 'vídeo', 'galería', 'multimedia', 'editar'] },
  { name: 'images', label: 'Galería', category: 'entertainment', icon: faImages, keywords: ['fotos', 'galería', 'imágenes', 'álbum', 'recuerdos'] },
  { name: 'camera-retro', label: 'Cámara analógica', category: 'entertainment', icon: faCameraRetro, keywords: ['cámara', 'analógica', 'vintage', 'fotografía', 'carrete'] },
  { name: 'ticket', label: 'Entradas', category: 'entertainment', icon: faTicket, keywords: ['entrada', 'ticket', 'concierto', 'evento', 'espectáculo'] },
  { name: 'paintbrush', label: 'Pintar', category: 'entertainment', icon: faPaintbrush, keywords: ['pincel', 'pintar', 'acuarela', 'arte', 'cuadro'] },
  { name: 'spray-can', label: 'Grafiti', category: 'entertainment', icon: faSprayCan, keywords: ['grafiti', 'spray', 'street art', 'arte urbano', 'pintar'] },
  { name: 'dice-d20', label: 'Juego de rol', category: 'entertainment', icon: faDiceD20, keywords: ['rol', 'dados', 'dnd', 'partida', 'mesa'] },
  { name: 'ghost', label: 'Terror', category: 'entertainment', icon: faGhost, keywords: ['terror', 'fantasma', 'miedo', 'halloween', 'peli'] },
  { name: 'dragon', label: 'Fantasía', category: 'entertainment', icon: faDragon, keywords: ['fantasía', 'dragón', 'épico', 'rol', 'novela'] },
  { name: 'hat-wizard', label: 'Magia', category: 'entertainment', icon: faHatWizard, keywords: ['magia', 'mago', 'sombrero', 'fantasía', 'truco'] },
  { name: 'shuttle-space', label: 'Ciencia ficción', category: 'entertainment', icon: faShuttleSpace, keywords: ['espacio', 'cohete', 'ciencia ficción', 'nave', 'astronauta'] },
  { name: 'binoculars', label: 'Explorar', category: 'entertainment', icon: faBinoculars, keywords: ['explorar', 'prismáticos', 'observar', 'aves', 'descubrir'] },
  { name: 'umbrella-beach', label: 'Playa', category: 'entertainment', icon: faUmbrellaBeach, keywords: ['playa', 'vacaciones', 'sombrilla', 'descanso', 'verano'] },
  { name: 'burger', label: 'Hamburguesa', category: 'entertainment', icon: faBurger, keywords: ['hamburguesa', 'comida', 'capricho', 'fast food', 'cena'] },
  { name: 'ice-cream', label: 'Helado', category: 'entertainment', icon: faIceCream, keywords: ['helado', 'postre', 'dulce', 'verano', 'capricho'] },
  { name: 'cookie-bite', label: 'Dulce', category: 'entertainment', icon: faCookieBite, keywords: ['galleta', 'dulce', 'postre', 'capricho', 'merienda'] },
  { name: 'martini-glass-citrus', label: 'Cóctel', category: 'entertainment', icon: faMartiniGlassCitrus, keywords: ['cóctel', 'copa', 'bebida', 'fiesta', 'combinado'] },
] as const satisfies readonly AppIconEntry[]
