import {
  faArrowRightArrowLeft,
  faArrowTrendDown,
  faArrowTrendUp,
  faBahtSign,
  faBarcode,
  faBitcoinSign,
  faBrazilianRealSign,
  faBuildingColumns,
  faCartArrowDown,
  faCartPlus,
  faCashRegister,
  faChartBar,
  faChartLine,
  faChartPie,
  faCircleDollarToSlot,
  faCoins,
  faColonSign,
  faCommentDollar,
  faCommentsDollar,
  faCreditCard,
  faDollarSign,
  faEuroSign,
  faFileCircleCheck,
  faFileCircleExclamation,
  faFileContract,
  faFileInvoiceDollar,
  faFileShield,
  faFilterCircleDollar,
  faFrancSign,
  faGem,
  faHandHolding,
  faHandHoldingDollar,
  faIndianRupeeSign,
  faLandmarkDome,
  faLiraSign,
  faLitecoinSign,
  faMagnifyingGlassDollar,
  faMoneyBill,
  faMoneyBill1,
  faMoneyBill1Wave,
  faMoneyBills,
  faMoneyBillTransfer,
  faMoneyBillTrendUp,
  faMoneyBillWave,
  faMoneyBillWheat,
  faMoneyCheck,
  faMoneyCheckDollar,
  faNairaSign,
  faPercent,
  faPesoSign,
  faPiggyBank,
  faReceipt,
  faRightLeft,
  faRubleSign,
  faRupeeSign,
  faRupiahSign,
  faSackDollar,
  faSackXmark,
  faScaleBalanced,
  faScaleUnbalanced,
  faScaleUnbalancedFlip,
  faShekelSign,
  faSterlingSign,
  faStoreSlash,
  faTags,
  faTurkishLiraSign,
  faVault,
  faWallet,
  faWonSign,
  faYenSign,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const financeIcons = [
  { name: 'wallet', label: 'Cartera', category: 'finance', icon: faWallet, keywords: ['dinero', 'finanzas', 'money', 'budget', 'cartera', 'monedero'] },
  { name: 'piggy-bank', label: 'Ahorro', category: 'finance', icon: faPiggyBank, keywords: ['ahorro', 'meta', 'savings', 'hucha', 'ahorrar'] },
  { name: 'money-bill', label: 'Efectivo', category: 'finance', icon: faMoneyBill, keywords: ['cash', 'billete', 'pago', 'efectivo', 'dinero'] },
  { name: 'credit-card', label: 'Tarjeta', category: 'finance', icon: faCreditCard, keywords: ['pago', 'banco', 'card', 'tarjeta', 'débito'] },
  { name: 'chart-line', label: 'Gráfica', category: 'finance', icon: faChartLine, keywords: ['stats', 'métricas', 'inversión', 'tendencia', 'bolsa'] },
  { name: 'chart-pie', label: 'Gráfico circular', category: 'finance', icon: faChartPie, keywords: ['presupuesto', 'distribución', 'analytics', 'reparto'] },
  { name: 'receipt', label: 'Recibo', category: 'finance', icon: faReceipt, keywords: ['gasto', 'factura', 'expense', 'ticket', 'recibo'] },
  { name: 'coins', label: 'Monedas', category: 'finance', icon: faCoins, keywords: ['ahorro', 'coins', 'dinero', 'monedas', 'cambio'] },
  { name: 'sack-dollar', label: 'Ahorros', category: 'finance', icon: faSackDollar, keywords: ['bolsa', 'inversión', 'wealth', 'fondo', 'capital'] },
  { name: 'cash-register', label: 'Caja', category: 'finance', icon: faCashRegister, keywords: ['ventas', 'tienda', 'negocio', 'caja', 'cobrar'] },
  { name: 'building-columns', label: 'Banco', category: 'finance', icon: faBuildingColumns, keywords: ['banco', 'bank', 'entidad', 'cuenta', 'hipoteca'] },
  { name: 'file-invoice-dollar', label: 'Factura', category: 'finance', icon: faFileInvoiceDollar, keywords: ['factura', 'invoice', 'cobro', 'autónomo', 'impuestos'] },
  { name: 'file-contract', label: 'Contrato', category: 'finance', icon: faFileContract, keywords: ['contrato', 'firma', 'alquiler', 'condiciones', 'legal'] },
  { name: 'money-bill-trend-up', label: 'Ingresos', category: 'finance', icon: faMoneyBillTrendUp, keywords: ['ingresos', 'nómina', 'sueldo', 'income', 'ganancias'] },
  { name: 'money-bill-transfer', label: 'Transferencia', category: 'finance', icon: faMoneyBillTransfer, keywords: ['transferencia', 'enviar dinero', 'bizum', 'pago', 'transfer'] },
  { name: 'money-bill-wave', label: 'Billetes', category: 'finance', icon: faMoneyBillWave, keywords: ['billetes', 'efectivo', 'dinero', 'cash', 'pago'] },
  { name: 'money-check-dollar', label: 'Nómina', category: 'finance', icon: faMoneyCheckDollar, keywords: ['nómina', 'cheque', 'salario', 'pago', 'sueldo'] },
  { name: 'hand-holding-dollar', label: 'Pagar', category: 'finance', icon: faHandHoldingDollar, keywords: ['pagar', 'préstamo', 'dar', 'devolver', 'deuda'] },
  { name: 'circle-dollar-to-slot', label: 'Aportación', category: 'finance', icon: faCircleDollarToSlot, keywords: ['aportar', 'donar', 'donación', 'hucha', 'aportación'] },
  { name: 'sack-xmark', label: 'Deuda', category: 'finance', icon: faSackXmark, keywords: ['deuda', 'pérdida', 'gasto', 'sin dinero', 'débito'] },
  { name: 'vault', label: 'Caja fuerte', category: 'finance', icon: faVault, keywords: ['caja fuerte', 'seguro', 'reserva', 'fondo de emergencia'] },
  { name: 'scale-balanced', label: 'Balance', category: 'finance', icon: faScaleBalanced, keywords: ['balance', 'equilibrio', 'cuentas', 'justicia', 'comparar'] },
  { name: 'arrow-trend-up', label: 'Subida', category: 'finance', icon: faArrowTrendUp, keywords: ['subir', 'crecer', 'ganancia', 'tendencia', 'alza'] },
  { name: 'arrow-trend-down', label: 'Bajada', category: 'finance', icon: faArrowTrendDown, keywords: ['bajar', 'pérdida', 'caída', 'tendencia', 'recorte'] },
  { name: 'percent', label: 'Interés', category: 'finance', icon: faPercent, keywords: ['porcentaje', 'interés', 'descuento', 'tasa', 'tipo'] },
  { name: 'euro-sign', label: 'Euro', category: 'finance', icon: faEuroSign, keywords: ['euro', 'moneda', 'dinero', 'precio', 'eur'] },
  { name: 'dollar-sign', label: 'Dólar', category: 'finance', icon: faDollarSign, keywords: ['dólar', 'moneda', 'dinero', 'precio', 'usd'] },
  { name: 'bitcoin-sign', label: 'Cripto', category: 'finance', icon: faBitcoinSign, keywords: ['bitcoin', 'cripto', 'criptomoneda', 'blockchain', 'inversión'] },
  { name: 'gem', label: 'Patrimonio', category: 'finance', icon: faGem, keywords: ['gema', 'joya', 'patrimonio', 'valor', 'lujo'] },
  { name: 'yen-sign', label: 'Yen', category: 'finance', icon: faYenSign, keywords: ['yen', 'japón', 'moneda', 'divisa'] },
  { name: 'won-sign', label: 'Won', category: 'finance', icon: faWonSign, keywords: ['won', 'corea', 'moneda', 'divisa'] },
  { name: 'sterling-sign', label: 'Libra', category: 'finance', icon: faSterlingSign, keywords: ['libra', 'reino unido', 'moneda', 'divisa'] },
  { name: 'ruble-sign', label: 'Rublo', category: 'finance', icon: faRubleSign, keywords: ['rublo', 'rusia', 'moneda', 'divisa'] },
  { name: 'rupee-sign', label: 'Rupia', category: 'finance', icon: faRupeeSign, keywords: ['rupia', 'moneda', 'divisa'] },
  { name: 'indian-rupee-sign', label: 'Rupia india', category: 'finance', icon: faIndianRupeeSign, keywords: ['rupia', 'india', 'moneda', 'divisa'] },
  { name: 'shekel-sign', label: 'Séquel', category: 'finance', icon: faShekelSign, keywords: ['séquel', 'israel', 'moneda', 'divisa'] },
  { name: 'peso-sign', label: 'Peso', category: 'finance', icon: faPesoSign, keywords: ['peso', 'moneda', 'divisa', 'latinoamérica'] },
  { name: 'franc-sign', label: 'Franco', category: 'finance', icon: faFrancSign, keywords: ['franco', 'suiza', 'moneda', 'divisa'] },
  { name: 'lira-sign', label: 'Lira', category: 'finance', icon: faLiraSign, keywords: ['lira', 'moneda', 'divisa'] },
  { name: 'turkish-lira-sign', label: 'Lira turca', category: 'finance', icon: faTurkishLiraSign, keywords: ['lira', 'turquía', 'moneda', 'divisa'] },
  { name: 'baht-sign', label: 'Baht', category: 'finance', icon: faBahtSign, keywords: ['baht', 'tailandia', 'moneda', 'divisa'] },
  { name: 'brazilian-real-sign', label: 'Real brasileño', category: 'finance', icon: faBrazilianRealSign, keywords: ['real', 'brasil', 'moneda', 'divisa'] },
  { name: 'colon-sign', label: 'Colón', category: 'finance', icon: faColonSign, keywords: ['colón', 'costa rica', 'moneda', 'divisa'] },
  { name: 'naira-sign', label: 'Naira', category: 'finance', icon: faNairaSign, keywords: ['naira', 'nigeria', 'moneda', 'divisa'] },
  { name: 'rupiah-sign', label: 'Rupia indonesia', category: 'finance', icon: faRupiahSign, keywords: ['rupia', 'indonesia', 'moneda', 'divisa'] },
  { name: 'litecoin-sign', label: 'Litecoin', category: 'finance', icon: faLitecoinSign, keywords: ['cripto', 'litecoin', 'moneda', 'inversión'] },
  { name: 'money-bills', label: 'Billetes', category: 'finance', icon: faMoneyBills, keywords: ['billetes', 'dinero', 'efectivo', 'cobrar'] },
  { name: 'money-bill-1', label: 'Billete', category: 'finance', icon: faMoneyBill1, keywords: ['billete', 'dinero', 'efectivo'] },
  { name: 'money-bill-1-wave', label: 'Dinero en mano', category: 'finance', icon: faMoneyBill1Wave, keywords: ['dinero', 'billete', 'pago', 'efectivo'] },
  { name: 'money-bill-wheat', label: 'Dinero del campo', category: 'finance', icon: faMoneyBillWheat, keywords: ['dinero', 'campo', 'cosecha', 'subvención'] },
  { name: 'money-check', label: 'Cheque', category: 'finance', icon: faMoneyCheck, keywords: ['cheque', 'pago', 'banco', 'talón'] },
  { name: 'comment-dollar', label: 'Consulta de precio', category: 'finance', icon: faCommentDollar, keywords: ['precio', 'presupuesto', 'mensaje', 'cobro'] },
  { name: 'comments-dollar', label: 'Negociar', category: 'finance', icon: faCommentsDollar, keywords: ['negociar', 'precio', 'acuerdo', 'presupuesto'] },
  { name: 'magnifying-glass-dollar', label: 'Revisar gastos', category: 'finance', icon: faMagnifyingGlassDollar, keywords: ['revisar', 'gastos', 'buscar', 'auditoría'] },
  { name: 'filter-circle-dollar', label: 'Filtrar gastos', category: 'finance', icon: faFilterCircleDollar, keywords: ['filtrar', 'gastos', 'categoría', 'presupuesto'] },
  { name: 'cart-plus', label: 'Añadir a la compra', category: 'finance', icon: faCartPlus, keywords: ['carrito', 'comprar', 'añadir', 'compra'] },
  { name: 'cart-arrow-down', label: 'Compra recibida', category: 'finance', icon: faCartArrowDown, keywords: ['carrito', 'compra', 'pedido', 'recibir'] },
  { name: 'store-slash', label: 'No comprar', category: 'finance', icon: faStoreSlash, keywords: ['no comprar', 'cerrado', 'ahorro', 'tienda'] },
  { name: 'barcode', label: 'Código de barras', category: 'finance', icon: faBarcode, keywords: ['código', 'barras', 'precio', 'producto'] },
  { name: 'tags', label: 'Etiquetas de precio', category: 'finance', icon: faTags, keywords: ['etiquetas', 'precios', 'rebajas', 'ofertas'] },
  { name: 'scale-unbalanced', label: 'Cuentas desiguales', category: 'finance', icon: faScaleUnbalanced, keywords: ['balanza', 'desequilibrio', 'gastos', 'comparar'] },
  { name: 'scale-unbalanced-flip', label: 'Cuentas descuadradas', category: 'finance', icon: faScaleUnbalancedFlip, keywords: ['balanza', 'descuadre', 'cuentas', 'comparar'] },
  { name: 'chart-bar', label: 'Gráfico de barras', category: 'finance', icon: faChartBar, keywords: ['gráfico', 'barras', 'datos', 'informe'] },
  { name: 'hand-holding', label: 'Dar', category: 'finance', icon: faHandHolding, keywords: ['dar', 'ofrecer', 'donar', 'mano'] },
  { name: 'landmark-dome', label: 'Institución', category: 'finance', icon: faLandmarkDome, keywords: ['banco', 'institución', 'impuestos', 'hacienda'] },
  { name: 'file-shield', label: 'Seguro', category: 'finance', icon: faFileShield, keywords: ['seguro', 'póliza', 'proteger', 'documento'] },
  { name: 'arrow-right-arrow-left', label: 'Transferir', category: 'finance', icon: faArrowRightArrowLeft, keywords: ['transferir', 'traspaso', 'intercambio', 'banco'] },
  { name: 'right-left', label: 'Cambio de divisa', category: 'finance', icon: faRightLeft, keywords: ['cambio', 'divisa', 'intercambio', 'moneda'] },
  { name: 'file-circle-check', label: 'Pago confirmado', category: 'finance', icon: faFileCircleCheck, keywords: ['pago', 'confirmado', 'factura', 'documento'] },
  { name: 'file-circle-exclamation', label: 'Pago pendiente', category: 'finance', icon: faFileCircleExclamation, keywords: ['pendiente', 'aviso', 'factura', 'documento'] },
] as const satisfies readonly AppIconEntry[]
