import {
  faArrowTrendDown,
  faArrowTrendUp,
  faBitcoinSign,
  faBuildingColumns,
  faCashRegister,
  faChartLine,
  faChartPie,
  faCircleDollarToSlot,
  faCoins,
  faCreditCard,
  faDollarSign,
  faEuroSign,
  faFileContract,
  faFileInvoiceDollar,
  faGem,
  faHandHoldingDollar,
  faMoneyBill,
  faMoneyBillTransfer,
  faMoneyBillTrendUp,
  faMoneyBillWave,
  faMoneyCheckDollar,
  faPercent,
  faPiggyBank,
  faReceipt,
  faSackDollar,
  faSackXmark,
  faScaleBalanced,
  faVault,
  faWallet,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const financeIcons = [
  { name: 'wallet', label: 'Cartera', category: 'finance', icon: faWallet, keywords: ['dinero', 'finanzas', 'money', 'budget', 'cartera', 'monedero'] },
  { name: 'piggy-bank', label: 'Ahorro', category: 'finance', icon: faPiggyBank, keywords: ['ahorro', 'meta', 'savings', 'hucha', 'ahorrar'] },
  { name: 'money-bill', label: 'Efectivo', category: 'finance', icon: faMoneyBill, keywords: ['cash', 'billete', 'pago', 'efectivo', 'dinero'] },
  { name: 'credit-card', label: 'Tarjeta', category: 'finance', icon: faCreditCard, keywords: ['pago', 'banco', 'card', 'tarjeta', 'débito'] },
  { name: 'chart-line', label: 'Gráfica', category: 'finance', icon: faChartLine, keywords: ['stats', 'métricas', 'inversión', 'tendencia', 'bolsa'] },
  { name: 'chart-pie', label: 'Gráfico circular', category: 'finance', icon: faChartPie, keywords: ['presupuesto', 'distribución', 'analytics', 'reparto'] },
  { name: 'receipt', label: 'Recibo', category: 'finance', icon: faReceipt, keywords: ['gasto', 'factura', 'expense', 'ticket', 'recibo'] },
  { name: 'coins', label: 'Monedas', category: 'finance', icon: faCoins, keywords: ['ahorro', 'coins', 'dinero', 'monedas', 'cambio'] },
  { name: 'sack-dollar', label: 'Ahorros', category: 'finance', icon: faSackDollar, keywords: ['bolsa', 'inversión', 'wealth', 'fondo', 'capital'] },
  { name: 'cash-register', label: 'Caja', category: 'finance', icon: faCashRegister, keywords: ['ventas', 'tienda', 'negocio', 'caja', 'cobrar'] },
  { name: 'building-columns', label: 'Banco', category: 'finance', icon: faBuildingColumns, keywords: ['banco', 'bank', 'entidad', 'cuenta', 'hipoteca'] },
  { name: 'file-invoice-dollar', label: 'Factura', category: 'finance', icon: faFileInvoiceDollar, keywords: ['factura', 'invoice', 'cobro', 'autónomo', 'impuestos'] },
  { name: 'file-contract', label: 'Contrato', category: 'finance', icon: faFileContract, keywords: ['contrato', 'firma', 'alquiler', 'condiciones', 'legal'] },
  { name: 'money-bill-trend-up', label: 'Ingresos', category: 'finance', icon: faMoneyBillTrendUp, keywords: ['ingresos', 'nómina', 'sueldo', 'income', 'ganancias'] },
  { name: 'money-bill-transfer', label: 'Transferencia', category: 'finance', icon: faMoneyBillTransfer, keywords: ['transferencia', 'enviar dinero', 'bizum', 'pago', 'transfer'] },
  { name: 'money-bill-wave', label: 'Billetes', category: 'finance', icon: faMoneyBillWave, keywords: ['billetes', 'efectivo', 'dinero', 'cash', 'pago'] },
  { name: 'money-check-dollar', label: 'Nómina', category: 'finance', icon: faMoneyCheckDollar, keywords: ['nómina', 'cheque', 'salario', 'pago', 'sueldo'] },
  { name: 'hand-holding-dollar', label: 'Pagar', category: 'finance', icon: faHandHoldingDollar, keywords: ['pagar', 'préstamo', 'dar', 'devolver', 'deuda'] },
  { name: 'circle-dollar-to-slot', label: 'Aportación', category: 'finance', icon: faCircleDollarToSlot, keywords: ['aportar', 'donar', 'donación', 'hucha', 'aportación'] },
  { name: 'sack-xmark', label: 'Deuda', category: 'finance', icon: faSackXmark, keywords: ['deuda', 'pérdida', 'gasto', 'sin dinero', 'débito'] },
  { name: 'vault', label: 'Caja fuerte', category: 'finance', icon: faVault, keywords: ['caja fuerte', 'seguro', 'reserva', 'fondo de emergencia'] },
  { name: 'scale-balanced', label: 'Balance', category: 'finance', icon: faScaleBalanced, keywords: ['balance', 'equilibrio', 'cuentas', 'justicia', 'comparar'] },
  { name: 'arrow-trend-up', label: 'Subida', category: 'finance', icon: faArrowTrendUp, keywords: ['subir', 'crecer', 'ganancia', 'tendencia', 'alza'] },
  { name: 'arrow-trend-down', label: 'Bajada', category: 'finance', icon: faArrowTrendDown, keywords: ['bajar', 'pérdida', 'caída', 'tendencia', 'recorte'] },
  { name: 'percent', label: 'Interés', category: 'finance', icon: faPercent, keywords: ['porcentaje', 'interés', 'descuento', 'tasa', 'tipo'] },
  { name: 'euro-sign', label: 'Euro', category: 'finance', icon: faEuroSign, keywords: ['euro', 'moneda', 'dinero', 'precio', 'eur'] },
  { name: 'dollar-sign', label: 'Dólar', category: 'finance', icon: faDollarSign, keywords: ['dólar', 'moneda', 'dinero', 'precio', 'usd'] },
  { name: 'bitcoin-sign', label: 'Cripto', category: 'finance', icon: faBitcoinSign, keywords: ['bitcoin', 'cripto', 'criptomoneda', 'blockchain', 'inversión'] },
  { name: 'gem', label: 'Patrimonio', category: 'finance', icon: faGem, keywords: ['gema', 'joya', 'patrimonio', 'valor', 'lujo'] },
] as const satisfies readonly AppIconEntry[]
