import {
  faBaseball,
  faBaseballBatBall,
  faBasketball,
  faBicycle,
  faBolt,
  faBottleWater,
  faBowlingBall,
  faChildReaching,
  faDumbbell,
  faFire,
  faFireFlameCurved,
  faFlagCheckered,
  faFootball,
  faFutbol,
  faGaugeHigh,
  faGolfBallTee,
  faHandFist,
  faHeartCircleBolt,
  faHockeyPuck,
  faMedal,
  faMountain,
  faMountainSun,
  faOm,
  faPersonBiking,
  faPersonHiking,
  faPersonRunning,
  faPersonSkating,
  faPersonSkiing,
  faPersonSkiingNordic,
  faPersonSnowboarding,
  faPersonSwimming,
  faPersonWalking,
  faRankingStar,
  faSailboat,
  faShoePrints,
  faStairs,
  faTableTennisPaddleBall,
  faVolleyball,
  faWaterLadder,
  faWeightHanging,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const fitnessIcons = [
  { name: 'dumbbell', label: 'Pesas', category: 'fitness', icon: faDumbbell, keywords: ['gym', 'fitness', 'exercise', 'workout', 'pesas', 'ejercicio', 'fuerza', 'mancuerna', 'musculación'] },
  { name: 'running', label: 'Correr', category: 'fitness', icon: faPersonRunning, keywords: ['person-running', 'ejercicio', 'deporte', 'cardio', 'run', 'gym', 'running', 'trotar'] },
  { name: 'walking', label: 'Caminar', category: 'fitness', icon: faPersonWalking, keywords: ['person-walking', 'paseo', 'steps', 'pasos', 'andar', 'walk'] },
  { name: 'bicycle', label: 'Bicicleta', category: 'fitness', icon: faBicycle, keywords: ['ciclismo', 'bike', 'cardio', 'bici', 'pedalear'] },
  { name: 'fire', label: 'Racha', category: 'fitness', icon: faFire, keywords: ['streak', 'motivación', 'calorías', 'intenso', 'fuego'] },
  { name: 'bolt', label: 'Energía', category: 'fitness', icon: faBolt, keywords: ['rápido', 'power', 'hiit', 'intensidad', 'rayo', 'energy'] },
  { name: 'person-swimming', label: 'Natación', category: 'fitness', icon: faPersonSwimming, keywords: ['nadar', 'piscina', 'swim', 'deporte', 'swimming', 'natacion'] },
  { name: 'futbol', label: 'Fútbol', category: 'fitness', icon: faFutbol, keywords: ['soccer', 'deporte', 'balón', 'equipo', 'football', 'pelota'] },
  { name: 'om', label: 'Yoga', category: 'fitness', icon: faOm, keywords: ['yoga', 'om', 'asana', 'postura', 'flexibilidad', 'estiramiento', 'mindfulness', 'pilates'] },
  { name: 'child-reaching', label: 'Estiramientos', category: 'fitness', icon: faChildReaching, keywords: ['estirar', 'stretching', 'movilidad', 'flexibilidad', 'calentamiento', 'abdominales', 'core'] },
  { name: 'hand-fist', label: 'Boxeo', category: 'fitness', icon: faHandFist, keywords: ['boxing', 'puño', 'artes marciales', 'karate', 'combate', 'fuerza'] },
  { name: 'weight-hanging', label: 'Pesa rusa', category: 'fitness', icon: faWeightHanging, keywords: ['kettlebell', 'peso', 'carga', 'fuerza', 'levantamiento', 'weight', 'abdominales'] },
  { name: 'person-hiking', label: 'Senderismo', category: 'fitness', icon: faPersonHiking, keywords: ['hiking', 'trekking', 'montaña', 'excursión', 'ruta', 'caminata'] },
  { name: 'person-biking', label: 'Ciclismo', category: 'fitness', icon: faPersonBiking, keywords: ['biking', 'bici', 'bicicleta', 'ruta', 'spinning', 'cycling'] },
  { name: 'person-skating', label: 'Patinaje', category: 'fitness', icon: faPersonSkating, keywords: ['skating', 'patines', 'patinete', 'hielo', 'ruedas'] },
  { name: 'person-skiing', label: 'Esquí', category: 'fitness', icon: faPersonSkiing, keywords: ['skiing', 'esqui', 'nieve', 'montaña', 'invierno'] },
  { name: 'person-skiing-nordic', label: 'Esquí de fondo', category: 'fitness', icon: faPersonSkiingNordic, keywords: ['nordic', 'esqui', 'fondo', 'nieve', 'resistencia'] },
  { name: 'person-snowboarding', label: 'Snowboard', category: 'fitness', icon: faPersonSnowboarding, keywords: ['snowboard', 'nieve', 'tabla', 'invierno', 'montaña'] },
  { name: 'basketball', label: 'Baloncesto', category: 'fitness', icon: faBasketball, keywords: ['basket', 'basketball', 'canasta', 'balón', 'equipo'] },
  { name: 'volleyball', label: 'Voleibol', category: 'fitness', icon: faVolleyball, keywords: ['volley', 'voley', 'playa', 'balón', 'equipo'] },
  { name: 'football', label: 'Fútbol americano', category: 'fitness', icon: faFootball, keywords: ['rugby', 'american football', 'balón', 'equipo'] },
  { name: 'baseball', label: 'Béisbol', category: 'fitness', icon: faBaseball, keywords: ['baseball', 'beisbol', 'pelota', 'equipo'] },
  { name: 'baseball-bat-ball', label: 'Bate', category: 'fitness', icon: faBaseballBatBall, keywords: ['bate', 'béisbol', 'baseball', 'golpear'] },
  { name: 'table-tennis-paddle-ball', label: 'Tenis de mesa', category: 'fitness', icon: faTableTennisPaddleBall, keywords: ['ping pong', 'tenis', 'padel', 'pádel', 'raqueta', 'paleta', 'tennis'] },
  { name: 'golf-ball-tee', label: 'Golf', category: 'fitness', icon: faGolfBallTee, keywords: ['golf', 'campo', 'putt', 'pelota'] },
  { name: 'bowling-ball', label: 'Bolos', category: 'fitness', icon: faBowlingBall, keywords: ['bowling', 'bolera', 'bola', 'ocio'] },
  { name: 'hockey-puck', label: 'Hockey', category: 'fitness', icon: faHockeyPuck, keywords: ['hockey', 'disco', 'hielo', 'equipo'] },
  { name: 'mountain', label: 'Escalada', category: 'fitness', icon: faMountain, keywords: ['escalada', 'climbing', 'montaña', 'cima', 'roca', 'reto'] },
  { name: 'mountain-sun', label: 'Aire libre', category: 'fitness', icon: faMountainSun, keywords: ['naturaleza', 'excursión', 'outdoor', 'paisaje', 'montaña', 'sol'] },
  { name: 'sailboat', label: 'Vela y remo', category: 'fitness', icon: faSailboat, keywords: ['remo', 'rowing', 'vela', 'barco', 'navegar', 'kayak', 'piragua'] },
  { name: 'water-ladder', label: 'Piscina', category: 'fitness', icon: faWaterLadder, keywords: ['piscina', 'pool', 'nadar', 'escalera', 'agua'] },
  { name: 'stairs', label: 'Escaleras', category: 'fitness', icon: faStairs, keywords: ['escaleras', 'subir', 'cardio', 'stairs', 'pisos'] },
  { name: 'shoe-prints', label: 'Pasos', category: 'fitness', icon: faShoePrints, keywords: ['pasos', 'steps', 'huellas', 'caminar', 'zapatillas'] },
  { name: 'gauge-high', label: 'Ritmo', category: 'fitness', icon: faGaugeHigh, keywords: ['ritmo', 'velocidad', 'intensidad', 'pace', 'marcador'] },
  { name: 'heart-circle-bolt', label: 'Cardio', category: 'fitness', icon: faHeartCircleBolt, keywords: ['cardio', 'pulsaciones', 'frecuencia', 'esfuerzo', 'corazón'] },
  { name: 'fire-flame-curved', label: 'Calorías', category: 'fitness', icon: faFireFlameCurved, keywords: ['calorías', 'quemar', 'burn', 'llama', 'energía'] },
  { name: 'bottle-water', label: 'Botella', category: 'fitness', icon: faBottleWater, keywords: ['agua', 'hidratación', 'botella', 'beber', 'water'] },
  { name: 'flag-checkered', label: 'Meta lograda', category: 'fitness', icon: faFlagCheckered, keywords: ['meta', 'carrera', 'maratón', 'finish', 'llegada'] },
  { name: 'medal', label: 'Medalla', category: 'fitness', icon: faMedal, keywords: ['medalla', 'competición', 'premio', 'podio', 'logro'] },
  { name: 'ranking-star', label: 'Podio', category: 'fitness', icon: faRankingStar, keywords: ['ranking', 'podio', 'clasificación', 'competición', 'primero'] },
] as const satisfies readonly AppIconEntry[]
