import {
  faAnchor,
  faArrowsSpin,
  faBaseball,
  faBaseballBatBall,
  faBasketball,
  faBicycle,
  faBolt,
  faBoltLightning,
  faBottleWater,
  faBowlingBall,
  faCableCar,
  faChildReaching,
  faDumbbell,
  faFire,
  faFireFlameCurved,
  faFireFlameSimple,
  faFlagCheckered,
  faFootball,
  faFutbol,
  faGaugeHigh,
  faGaugeSimple,
  faGolfBallTee,
  faHandBackFist,
  faHandFist,
  faHeartCircleBolt,
  faHockeyPuck,
  faLifeRing,
  faMaximize,
  faMedal,
  faMountain,
  faMountainSun,
  faOm,
  faPeopleCarryBox,
  faPeopleLine,
  faPeoplePulling,
  faPerson,
  faPersonArrowDownToLine,
  faPersonArrowUpFromLine,
  faPersonBiking,
  faPersonCane,
  faPersonDress,
  faPersonFalling,
  faPersonHiking,
  faPersonRunning,
  faPersonSkating,
  faPersonSkiing,
  faPersonSkiingNordic,
  faPersonSnowboarding,
  faPersonSwimming,
  faPersonWalking,
  faPersonWalkingArrowRight,
  faPersonWalkingLuggage,
  faPersonWalkingWithCane,
  faRankingStar,
  faRoad,
  faRoadCircleCheck,
  faRulerCombined,
  faRulerHorizontal,
  faRulerVertical,
  faSailboat,
  faShoePrints,
  faStairs,
  faStopwatch20,
  faStreetView,
  faTableTennisPaddleBall,
  faTemperatureArrowDown,
  faTemperatureArrowUp,
  faTowerObservation,
  faUpDown,
  faVolleyball,
  faWaterLadder,
  faWeightHanging,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const fitnessIcons = [
  { name: 'dumbbell', label: 'Pesas', category: 'fitness', icon: faDumbbell, keywords: ['gym', 'fitness', 'exercise', 'workout', 'pesas', 'ejercicio', 'fuerza', 'mancuerna', 'musculación', 'gimnasio', 'crossfit'] },
  { name: 'running', label: 'Correr', category: 'fitness', icon: faPersonRunning, keywords: ['person-running', 'ejercicio', 'deporte', 'cardio', 'run', 'gym', 'running', 'trotar'] },
  { name: 'walking', label: 'Caminar', category: 'fitness', icon: faPersonWalking, keywords: ['person-walking', 'paseo', 'steps', 'pasos', 'andar', 'walk'] },
  { name: 'bicycle', label: 'Bicicleta', category: 'fitness', icon: faBicycle, keywords: ['ciclismo', 'bike', 'cardio', 'bici', 'pedalear'] },
  { name: 'fire', label: 'Racha', category: 'fitness', icon: faFire, keywords: ['streak', 'motivación', 'calorías', 'intenso', 'fuego'] },
  { name: 'bolt', label: 'Energía', category: 'fitness', icon: faBolt, keywords: ['rápido', 'power', 'hiit', 'intensidad', 'rayo', 'energy'] },
  { name: 'person-swimming', label: 'Natación', category: 'fitness', icon: faPersonSwimming, keywords: ['nadar', 'piscina', 'swim', 'deporte', 'swimming', 'natacion'] },
  { name: 'futbol', label: 'Fútbol', category: 'fitness', icon: faFutbol, keywords: ['soccer', 'deporte', 'balón', 'equipo', 'football', 'pelota'] },
  { name: 'om', label: 'Yoga', category: 'fitness', icon: faOm, keywords: ['yoga', 'om', 'asana', 'postura', 'flexibilidad', 'estiramiento', 'mindfulness', 'pilates'] },
  { name: 'child-reaching', label: 'Estiramientos', category: 'fitness', icon: faChildReaching, keywords: ['estirar', 'stretching', 'movilidad', 'flexibilidad', 'calentamiento', 'abdominales', 'core'] },
  { name: 'hand-fist', label: 'Boxeo', category: 'fitness', icon: faHandFist, keywords: ['boxing', 'puño', 'artes marciales', 'karate', 'combate', 'fuerza'] },
  { name: 'weight-hanging', label: 'Pesa rusa', category: 'fitness', icon: faWeightHanging, keywords: ['kettlebell', 'peso', 'carga', 'fuerza', 'levantamiento', 'weight', 'abdominales'] },
  { name: 'person-hiking', label: 'Senderismo', category: 'fitness', icon: faPersonHiking, keywords: ['hiking', 'trekking', 'montaña', 'excursión', 'ruta', 'caminata'] },
  { name: 'person-biking', label: 'Ciclismo', category: 'fitness', icon: faPersonBiking, keywords: ['biking', 'bici', 'bicicleta', 'ruta', 'spinning', 'cycling'] },
  { name: 'person-skating', label: 'Patinaje', category: 'fitness', icon: faPersonSkating, keywords: ['skating', 'patines', 'patinete', 'hielo', 'ruedas', 'patinar'] },
  { name: 'person-skiing', label: 'Esquí', category: 'fitness', icon: faPersonSkiing, keywords: ['skiing', 'esqui', 'nieve', 'montaña', 'invierno'] },
  { name: 'person-skiing-nordic', label: 'Esquí de fondo', category: 'fitness', icon: faPersonSkiingNordic, keywords: ['nordic', 'esqui', 'fondo', 'nieve', 'resistencia'] },
  { name: 'person-snowboarding', label: 'Snowboard', category: 'fitness', icon: faPersonSnowboarding, keywords: ['snowboard', 'nieve', 'tabla', 'invierno', 'montaña'] },
  { name: 'basketball', label: 'Baloncesto', category: 'fitness', icon: faBasketball, keywords: ['basket', 'basketball', 'canasta', 'balón', 'equipo'] },
  { name: 'volleyball', label: 'Voleibol', category: 'fitness', icon: faVolleyball, keywords: ['volley', 'voley', 'playa', 'balón', 'equipo'] },
  { name: 'football', label: 'Fútbol americano', category: 'fitness', icon: faFootball, keywords: ['rugby', 'american football', 'balón', 'equipo'] },
  { name: 'baseball', label: 'Béisbol', category: 'fitness', icon: faBaseball, keywords: ['baseball', 'beisbol', 'pelota', 'equipo'] },
  { name: 'baseball-bat-ball', label: 'Bate', category: 'fitness', icon: faBaseballBatBall, keywords: ['bate', 'béisbol', 'baseball', 'golpear'] },
  { name: 'table-tennis-paddle-ball', label: 'Tenis de mesa', category: 'fitness', icon: faTableTennisPaddleBall, keywords: ['ping pong', 'tenis', 'padel', 'pádel', 'raqueta', 'paleta', 'tennis'] },
  { name: 'golf-ball-tee', label: 'Golf', category: 'fitness', icon: faGolfBallTee, keywords: ['golf', 'campo', 'putt', 'pelota'] },
  { name: 'bowling-ball', label: 'Bolos', category: 'fitness', icon: faBowlingBall, keywords: ['bowling', 'bolera', 'bola', 'ocio'] },
  { name: 'hockey-puck', label: 'Hockey', category: 'fitness', icon: faHockeyPuck, keywords: ['hockey', 'disco', 'hielo', 'equipo'] },
  { name: 'mountain', label: 'Escalada', category: 'fitness', icon: faMountain, keywords: ['escalada', 'climbing', 'montaña', 'cima', 'roca', 'reto'] },
  { name: 'mountain-sun', label: 'Aire libre', category: 'fitness', icon: faMountainSun, keywords: ['naturaleza', 'excursión', 'outdoor', 'paisaje', 'montaña', 'sol'] },
  { name: 'sailboat', label: 'Vela y remo', category: 'fitness', icon: faSailboat, keywords: ['remo', 'rowing', 'vela', 'barco', 'navegar', 'kayak', 'piragua'] },
  { name: 'water-ladder', label: 'Piscina', category: 'fitness', icon: faWaterLadder, keywords: ['piscina', 'pool', 'nadar', 'escalera', 'agua'] },
  { name: 'stairs', label: 'Escaleras', category: 'fitness', icon: faStairs, keywords: ['escaleras', 'subir', 'cardio', 'stairs', 'pisos'] },
  { name: 'shoe-prints', label: 'Pasos', category: 'fitness', icon: faShoePrints, keywords: ['pasos', 'steps', 'huellas', 'caminar', 'zapatillas'] },
  { name: 'gauge-high', label: 'Ritmo', category: 'fitness', icon: faGaugeHigh, keywords: ['ritmo', 'velocidad', 'intensidad', 'pace', 'marcador'] },
  { name: 'heart-circle-bolt', label: 'Cardio', category: 'fitness', icon: faHeartCircleBolt, keywords: ['cardio', 'pulsaciones', 'frecuencia', 'esfuerzo', 'corazón'] },
  { name: 'fire-flame-curved', label: 'Calorías', category: 'fitness', icon: faFireFlameCurved, keywords: ['calorías', 'quemar', 'burn', 'llama', 'energía'] },
  { name: 'bottle-water', label: 'Botella', category: 'fitness', icon: faBottleWater, keywords: ['agua', 'hidratación', 'botella', 'beber', 'water'] },
  { name: 'flag-checkered', label: 'Meta lograda', category: 'fitness', icon: faFlagCheckered, keywords: ['meta', 'carrera', 'maratón', 'finish', 'llegada'] },
  { name: 'medal', label: 'Medalla', category: 'fitness', icon: faMedal, keywords: ['medalla', 'competición', 'premio', 'podio', 'logro'] },
  { name: 'ranking-star', label: 'Podio', category: 'fitness', icon: faRankingStar, keywords: ['ranking', 'podio', 'clasificación', 'competición', 'primero'] },
  { name: 'person', label: 'Silueta', category: 'fitness', icon: faPerson, keywords: ['persona', 'cuerpo', 'figura', 'postura'] },
  { name: 'person-dress', label: 'Silueta con vestido', category: 'fitness', icon: faPersonDress, keywords: ['persona', 'cuerpo', 'figura', 'postura'] },
  { name: 'person-cane', label: 'Movilidad', category: 'fitness', icon: faPersonCane, keywords: ['bastón', 'movilidad', 'caminar', 'mayores'] },
  { name: 'person-walking-with-cane', label: 'Caminar con bastón', category: 'fitness', icon: faPersonWalkingWithCane, keywords: ['bastón', 'caminar', 'movilidad', 'rehabilitación'] },
  { name: 'person-walking-arrow-right', label: 'Salir a caminar', category: 'fitness', icon: faPersonWalkingArrowRight, keywords: ['caminar', 'salir', 'paseo', 'pasos'] },
  { name: 'person-walking-luggage', label: 'Caminar con carga', category: 'fitness', icon: faPersonWalkingLuggage, keywords: ['caminar', 'equipaje', 'viaje', 'pasos'] },
  { name: 'people-carry-box', label: 'Cargar peso', category: 'fitness', icon: faPeopleCarryBox, keywords: ['cargar', 'peso', 'equipo', 'mudanza'] },
  { name: 'people-pulling', label: 'Arrastrar', category: 'fitness', icon: faPeoplePulling, keywords: ['arrastrar', 'trineo', 'fuerza', 'equipo'] },
  { name: 'people-line', label: 'Clase en grupo', category: 'fitness', icon: faPeopleLine, keywords: ['grupo', 'fila', 'clase', 'equipo'] },
  { name: 'hand-back-fist', label: 'Boxeo', category: 'fitness', icon: faHandBackFist, keywords: ['boxeo', 'puño', 'golpe', 'fuerza'] },
  { name: 'arrows-spin', label: 'Rotación', category: 'fitness', icon: faArrowsSpin, keywords: ['rotar', 'movilidad', 'girar', 'estiramiento'] },
  { name: 'maximize', label: 'Estirar', category: 'fitness', icon: faMaximize, keywords: ['estirar', 'estiramiento', 'extensión', 'flexibilidad'] },
  { name: 'up-down', label: 'Repeticiones', category: 'fitness', icon: faUpDown, keywords: ['repeticiones', 'sentadillas', 'subir', 'bajar', 'flexiones', 'dominadas'] },
  { name: 'gauge-simple', label: 'Ritmo', category: 'fitness', icon: faGaugeSimple, keywords: ['ritmo', 'pulso', 'velocidad', 'medidor'] },
  { name: 'bolt-lightning', label: 'Explosividad', category: 'fitness', icon: faBoltLightning, keywords: ['energía', 'potencia', 'rápido', 'intensidad'] },
  { name: 'fire-flame-simple', label: 'Calorías', category: 'fitness', icon: faFireFlameSimple, keywords: ['calorías', 'quemar', 'fuego', 'intensidad'] },
  { name: 'temperature-arrow-up', label: 'Calentamiento', category: 'fitness', icon: faTemperatureArrowUp, keywords: ['calentar', 'subir', 'temperatura', 'pulsaciones'] },
  { name: 'temperature-arrow-down', label: 'Vuelta a la calma', category: 'fitness', icon: faTemperatureArrowDown, keywords: ['enfriar', 'bajar', 'temperatura', 'recuperación'] },
  { name: 'ruler-vertical', label: 'Altura', category: 'fitness', icon: faRulerVertical, keywords: ['altura', 'medir', 'estatura', 'talla'] },
  { name: 'ruler-horizontal', label: 'Medir contorno', category: 'fitness', icon: faRulerHorizontal, keywords: ['medir', 'cinta', 'contorno', 'progreso'] },
  { name: 'ruler-combined', label: 'Medidas', category: 'fitness', icon: faRulerCombined, keywords: ['medidas', 'medir', 'progreso', 'cuerpo'] },
  { name: 'road', label: 'Carretera', category: 'fitness', icon: faRoad, keywords: ['correr', 'ruta', 'carretera', 'kilómetros'] },
  { name: 'road-circle-check', label: 'Ruta completada', category: 'fitness', icon: faRoadCircleCheck, keywords: ['ruta', 'completada', 'correr', 'kilómetros'] },
  { name: 'tower-observation', label: 'Mirador', category: 'fitness', icon: faTowerObservation, keywords: ['mirador', 'subida', 'torre', 'excursión'] },
  { name: 'cable-car', label: 'Teleférico', category: 'fitness', icon: faCableCar, keywords: ['teleférico', 'montaña', 'esquí', 'subida'] },
  { name: 'life-ring', label: 'Salvavidas', category: 'fitness', icon: faLifeRing, keywords: ['natación', 'salvavidas', 'piscina', 'seguridad'] },
  { name: 'anchor', label: 'Ancla', category: 'fitness', icon: faAnchor, keywords: ['ancla', 'mar', 'barco', 'remo'] },
  { name: 'person-arrow-up-from-line', label: 'Incorporarse', category: 'fitness', icon: faPersonArrowUpFromLine, keywords: ['levantarse', 'subir', 'postura', 'ejercicio'] },
  { name: 'person-arrow-down-to-line', label: 'Agacharse', category: 'fitness', icon: faPersonArrowDownToLine, keywords: ['agacharse', 'bajar', 'sentadilla', 'postura'] },
  { name: 'person-falling', label: 'Equilibrio', category: 'fitness', icon: faPersonFalling, keywords: ['caída', 'equilibrio', 'estabilidad', 'prevención'] },
  { name: 'street-view', label: 'Salir al barrio', category: 'fitness', icon: faStreetView, keywords: ['paseo', 'barrio', 'calle', 'salir'] },
  { name: 'stopwatch-20', label: 'Cronómetro de serie', category: 'fitness', icon: faStopwatch20, keywords: ['cronómetro', 'tiempo', 'serie', 'descanso'] },
] as const satisfies readonly AppIconEntry[]
