import {
  faAppleWhole,
  faBacteria,
  faBandage,
  faBanSmoking,
  faBed,
  faBedPulse,
  faBowlFood,
  faBowlRice,
  faBreadSlice,
  faCapsules,
  faCarrot,
  faCheese,
  faCircleH,
  faCrutch,
  faDisease,
  faDroplet,
  faDrumstickBite,
  faEarDeaf,
  faEarListen,
  faEgg,
  faEyeLowVision,
  faFileMedical,
  faFishFins,
  faGlasses,
  faGlassWater,
  faHandHoldingDroplet,
  faHandSparkles,
  faHeadSideCough,
  faHeadSideMask,
  faHeart,
  faHeartCircleCheck,
  faHeartPulse,
  faHospital,
  faHospitalUser,
  faHouseChimneyMedical,
  faLaptopMedical,
  faLemon,
  faMaskFace,
  faMattressPillow,
  faMedkit,
  faMoon,
  faNotesMedical,
  faPepperHot,
  faPills,
  faPlateWheat,
  faPrescription,
  faPrescriptionBottleMedical,
  faPumpMedical,
  faRibbon,
  faShieldVirus,
  faSmoking,
  faSpoon,
  faStarOfLife,
  faStethoscope,
  faSyringe,
  faTablets,
  faTeeth,
  faTemperatureHigh,
  faTemperatureLow,
  faThermometer,
  faToilet,
  faTooth,
  faTruckMedical,
  faUserDoctor,
  faUserInjured,
  faUserNurse,
  faUtensils,
  faVial,
  faVirus,
  faViruses,
  faWeightScale,
  faWheatAwn,
  faWheelchair,
  faWheelchairMove,
  faXRay,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const healthIcons = [
  { name: 'heart', label: 'Salud', category: 'health', icon: faHeart, keywords: ['like', 'amor', 'bienestar', 'cardio', 'corazón'] },
  { name: 'heart-pulse', label: 'Pulso', category: 'health', icon: faHeartPulse, keywords: ['gym', 'fitness', 'cardio', 'ejercicio', 'salud', 'pulsaciones'] },
  { name: 'apple-whole', label: 'Nutrición', category: 'health', icon: faAppleWhole, keywords: ['fruta', 'dieta', 'healthy', 'comida sana', 'manzana'] },
  { name: 'bowl-food', label: 'Comida', category: 'health', icon: faBowlFood, keywords: ['alimentación', 'meal', 'diet', 'comer', 'plato'] },
  { name: 'utensils', label: 'Utensilios', category: 'health', icon: faUtensils, keywords: ['comer', 'cena', 'almuerzo', 'food', 'cubiertos'] },
  { name: 'droplet', label: 'Hidratación', category: 'health', icon: faDroplet, keywords: ['agua', 'water', 'beber', 'gota', 'hidratarse'] },
  { name: 'moon', label: 'Noche', category: 'health', icon: faMoon, keywords: ['sueño', 'sleep', 'descanso', 'noche', 'luna', 'dormir'] },
  { name: 'bed', label: 'Dormir', category: 'health', icon: faBed, keywords: ['sueño', 'sleep', 'descanso', 'siesta', 'cama', 'dormir'] },
  { name: 'medkit', label: 'Botiquín', category: 'health', icon: faMedkit, keywords: ['medicina', 'primeros auxilios', 'salud', 'kit', 'urgencias'] },
  { name: 'stethoscope', label: 'Médico', category: 'health', icon: faStethoscope, keywords: ['doctor', 'consulta', 'salud', 'revisión', 'chequeo'] },
  { name: 'weight-scale', label: 'Peso', category: 'health', icon: faWeightScale, keywords: ['báscula', 'fitness', 'control', 'pesarse', 'kilos'] },
  { name: 'pills', label: 'Medicación', category: 'health', icon: faPills, keywords: ['pastillas', 'farmacia', 'tratamiento', 'medicina', 'pastilla'] },
  { name: 'syringe', label: 'Vacuna', category: 'health', icon: faSyringe, keywords: ['inyección', 'vacuna', 'médico', 'salud', 'jeringa'] },
  { name: 'tooth', label: 'Dental', category: 'health', icon: faTooth, keywords: ['dientes', 'dentista', 'higiene', 'salud', 'cepillarse', 'muela'] },
  { name: 'capsules', label: 'Vitaminas', category: 'health', icon: faCapsules, keywords: ['vitaminas', 'suplementos', 'cápsulas', 'omega', 'magnesio'] },
  { name: 'prescription-bottle-medical', label: 'Tratamiento', category: 'health', icon: faPrescriptionBottleMedical, keywords: ['receta', 'bote', 'medicamento', 'farmacia', 'dosis'] },
  { name: 'glass-water', label: 'Vaso de agua', category: 'health', icon: faGlassWater, keywords: ['agua', 'vaso', 'beber', 'hidratación', 'water'] },
  { name: 'carrot', label: 'Verdura', category: 'health', icon: faCarrot, keywords: ['verdura', 'zanahoria', 'vegetal', 'hortaliza', 'dieta', 'vegetariano'] },
  { name: 'lemon', label: 'Cítricos', category: 'health', icon: faLemon, keywords: ['limón', 'fruta', 'cítrico', 'vitamina c', 'zumo'] },
  { name: 'pepper-hot', label: 'Picante', category: 'health', icon: faPepperHot, keywords: ['pimiento', 'picante', 'chili', 'especias', 'verdura'] },
  { name: 'bowl-rice', label: 'Arroz', category: 'health', icon: faBowlRice, keywords: ['arroz', 'cuenco', 'plato', 'hidratos', 'comida'] },
  { name: 'bread-slice', label: 'Pan', category: 'health', icon: faBreadSlice, keywords: ['pan', 'tostada', 'desayuno', 'hidratos', 'bread'] },
  { name: 'cheese', label: 'Queso', category: 'health', icon: faCheese, keywords: ['queso', 'lácteo', 'proteína', 'cheese'] },
  { name: 'egg', label: 'Huevo', category: 'health', icon: faEgg, keywords: ['huevo', 'proteína', 'desayuno', 'egg'] },
  { name: 'fish-fins', label: 'Pescado', category: 'health', icon: faFishFins, keywords: ['pescado', 'proteína', 'omega', 'cena', 'fish'] },
  { name: 'drumstick-bite', label: 'Carne', category: 'health', icon: faDrumstickBite, keywords: ['carne', 'pollo', 'proteína', 'cena', 'meat'] },
  { name: 'plate-wheat', label: 'Plato completo', category: 'health', icon: faPlateWheat, keywords: ['plato', 'menú', 'equilibrado', 'dieta', 'ración'] },
  { name: 'wheat-awn', label: 'Cereales', category: 'health', icon: faWheatAwn, keywords: ['cereal', 'trigo', 'integral', 'gluten', 'avena'] },
  { name: 'spoon', label: 'Cuchara', category: 'health', icon: faSpoon, keywords: ['cuchara', 'porción', 'medida', 'comer', 'sopa'] },
  { name: 'user-doctor', label: 'Doctor', category: 'health', icon: faUserDoctor, keywords: ['médico', 'doctor', 'consulta', 'cita médica', 'revisión'] },
  { name: 'user-nurse', label: 'Enfermería', category: 'health', icon: faUserNurse, keywords: ['enfermera', 'enfermero', 'cuidados', 'clínica', 'nurse'] },
  { name: 'hospital', label: 'Hospital', category: 'health', icon: faHospital, keywords: ['hospital', 'clínica', 'urgencias', 'centro de salud'] },
  { name: 'notes-medical', label: 'Historial', category: 'health', icon: faNotesMedical, keywords: ['historial', 'informe', 'médico', 'seguimiento', 'analítica'] },
  { name: 'heart-circle-check', label: 'Revisión', category: 'health', icon: faHeartCircleCheck, keywords: ['revisión', 'chequeo', 'control', 'tensión', 'checkup'] },
  { name: 'thermometer', label: 'Temperatura', category: 'health', icon: faThermometer, keywords: ['fiebre', 'termómetro', 'temperatura', 'gripe'] },
  { name: 'vial', label: 'Analítica', category: 'health', icon: faVial, keywords: ['análisis', 'sangre', 'laboratorio', 'prueba', 'muestra'] },
  { name: 'x-ray', label: 'Radiografía', category: 'health', icon: faXRay, keywords: ['radiografía', 'rayos x', 'prueba', 'hueso', 'traumatología'] },
  { name: 'bandage', label: 'Cura', category: 'health', icon: faBandage, keywords: ['tirita', 'cura', 'herida', 'venda', 'primeros auxilios'] },
  { name: 'crutch', label: 'Rehabilitación', category: 'health', icon: faCrutch, keywords: ['muleta', 'rehabilitación', 'fisio', 'lesión', 'recuperación'] },
  { name: 'wheelchair', label: 'Movilidad', category: 'health', icon: faWheelchair, keywords: ['silla de ruedas', 'movilidad', 'accesibilidad', 'discapacidad'] },
  { name: 'glasses', label: 'Gafas', category: 'health', icon: faGlasses, keywords: ['gafas', 'vista', 'óptica', 'ver', 'graduación'] },
  { name: 'ban-smoking', label: 'Dejar de fumar', category: 'health', icon: faBanSmoking, keywords: ['fumar', 'tabaco', 'dejar', 'no fumar', 'adicción'] },
  { name: 'mattress-pillow', label: 'Siesta', category: 'health', icon: faMattressPillow, keywords: ['siesta', 'almohada', 'descanso', 'nap', 'dormir'] },
  { name: 'bed-pulse', label: 'Reposo', category: 'health', icon: faBedPulse, keywords: ['reposo', 'enfermo', 'recuperación', 'baja', 'cama'] },
  { name: 'file-medical', label: 'Informe médico', category: 'health', icon: faFileMedical, keywords: ['informe', 'historial', 'médico', 'analítica'] },
  { name: 'laptop-medical', label: 'Consulta online', category: 'health', icon: faLaptopMedical, keywords: ['telemedicina', 'consulta', 'online', 'médico'] },
  { name: 'house-chimney-medical', label: 'Centro de salud', category: 'health', icon: faHouseChimneyMedical, keywords: ['centro de salud', 'clínica', 'ambulatorio', 'médico'] },
  { name: 'hospital-user', label: 'Ingreso', category: 'health', icon: faHospitalUser, keywords: ['hospital', 'ingreso', 'paciente', 'visita'] },
  { name: 'truck-medical', label: 'Ambulancia', category: 'health', icon: faTruckMedical, keywords: ['ambulancia', 'urgencias', 'emergencia', 'sanitario'] },
  { name: 'user-injured', label: 'Lesión', category: 'health', icon: faUserInjured, keywords: ['lesión', 'herido', 'recuperación', 'rehabilitación'] },
  { name: 'star-of-life', label: 'Emergencia', category: 'health', icon: faStarOfLife, keywords: ['emergencia', 'urgencias', 'salud', 'socorro'] },
  { name: 'circle-h', label: 'Hospital', category: 'health', icon: faCircleH, keywords: ['hospital', 'urgencias', 'centro', 'ingreso'] },
  { name: 'prescription', label: 'Receta', category: 'health', icon: faPrescription, keywords: ['receta', 'farmacia', 'medicación', 'prescripción'] },
  { name: 'tablets', label: 'Pastillas', category: 'health', icon: faTablets, keywords: ['pastillas', 'medicación', 'tomar', 'dosis'] },
  { name: 'pump-medical', label: 'Desinfectar', category: 'health', icon: faPumpMedical, keywords: ['desinfectar', 'gel', 'manos', 'higiene'] },
  { name: 'hand-holding-droplet', label: 'Donar sangre', category: 'health', icon: faHandHoldingDroplet, keywords: ['sangre', 'donar', 'gota', 'análisis'] },
  { name: 'hand-sparkles', label: 'Manos limpias', category: 'health', icon: faHandSparkles, keywords: ['manos', 'limpias', 'higiene', 'lavarse'] },
  { name: 'mask-face', label: 'Mascarilla', category: 'health', icon: faMaskFace, keywords: ['mascarilla', 'protección', 'virus', 'contagio'] },
  { name: 'head-side-cough', label: 'Tos', category: 'health', icon: faHeadSideCough, keywords: ['tos', 'resfriado', 'síntoma', 'contagio'] },
  { name: 'head-side-mask', label: 'Protección respiratoria', category: 'health', icon: faHeadSideMask, keywords: ['mascarilla', 'respirar', 'protección', 'alergia'] },
  { name: 'virus', label: 'Virus', category: 'health', icon: faVirus, keywords: ['virus', 'infección', 'contagio', 'enfermedad'] },
  { name: 'viruses', label: 'Infección', category: 'health', icon: faViruses, keywords: ['virus', 'infección', 'contagio', 'microbios'] },
  { name: 'bacteria', label: 'Bacterias', category: 'health', icon: faBacteria, keywords: ['bacterias', 'microbios', 'infección', 'higiene'] },
  { name: 'disease', label: 'Enfermedad', category: 'health', icon: faDisease, keywords: ['enfermedad', 'síntomas', 'diagnóstico', 'virus'] },
  { name: 'shield-virus', label: 'Prevención', category: 'health', icon: faShieldVirus, keywords: ['prevención', 'protección', 'virus', 'vacuna'] },
  { name: 'ribbon', label: 'Lazo solidario', category: 'health', icon: faRibbon, keywords: ['lazo', 'causa', 'concienciación', 'apoyo'] },
  { name: 'teeth', label: 'Dentadura', category: 'health', icon: faTeeth, keywords: ['dientes', 'dentadura', 'cepillar', 'dentista'] },
  { name: 'toilet', label: 'Baño', category: 'health', icon: faToilet, keywords: ['baño', 'aseo', 'digestión', 'wc'] },
  { name: 'temperature-high', label: 'Fiebre', category: 'health', icon: faTemperatureHigh, keywords: ['fiebre', 'temperatura', 'termómetro', 'calor'] },
  { name: 'temperature-low', label: 'Temperatura baja', category: 'health', icon: faTemperatureLow, keywords: ['frío', 'temperatura', 'termómetro', 'hipotermia'] },
  { name: 'eye-low-vision', label: 'Vista cansada', category: 'health', icon: faEyeLowVision, keywords: ['vista', 'visión', 'ojos', 'descanso visual'] },
  { name: 'ear-listen', label: 'Oído', category: 'health', icon: faEarListen, keywords: ['oído', 'escuchar', 'audición', 'revisión'] },
  { name: 'ear-deaf', label: 'Sordera', category: 'health', icon: faEarDeaf, keywords: ['sordera', 'audición', 'accesibilidad', 'oído'] },
  { name: 'smoking', label: 'Fumar', category: 'health', icon: faSmoking, keywords: ['fumar', 'tabaco', 'cigarro', 'dejar de fumar'] },
  { name: 'wheelchair-move', label: 'Silla de ruedas', category: 'health', icon: faWheelchairMove, keywords: ['silla de ruedas', 'movilidad', 'accesibilidad', 'rehabilitación'] },
] as const satisfies readonly AppIconEntry[]
