import {
  faBagShopping,
  faBasketShopping,
  faBath,
  faBlender,
  faBoxesStacked,
  faBroom,
  faBus,
  faCar,
  faCartShopping,
  faChair,
  faCloudRain,
  faCouch,
  faDoorOpen,
  faFaucet,
  faFireBurner,
  faGasPump,
  faHandsBubbles,
  faHouse,
  faJugDetergent,
  faKey,
  faKitchenSet,
  faMapLocationDot,
  faMotorcycle,
  faPaintRoller,
  faPlane,
  faPlantWilt,
  faPlug,
  faRecycle,
  faScrewdriver,
  faShirt,
  faShop,
  faShower,
  faSink,
  faSnowflake,
  faSoap,
  faSprayCanSparkles,
  faSuitcaseRolling,
  faTaxi,
  faTrain,
  faTrainSubway,
  faTrashCan,
  faTree,
  faUmbrella,
  faWrench,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const homeIcons = [
  { name: 'home', label: 'Hogar', category: 'home', icon: faHouse, keywords: ['house', 'inicio', 'casa', 'doméstico', 'hogar'] },
  { name: 'shirt', label: 'Ropa', category: 'home', icon: faShirt, keywords: ['lavandería', 'vestir', 'closet', 'plancha', 'planchar', 'camiseta', 'doblar'] },
  { name: 'cart-shopping', label: 'Compras', category: 'home', icon: faCartShopping, keywords: ['supermercado', 'errands', 'shopping', 'carro', 'compra'] },
  { name: 'car', label: 'Coche', category: 'home', icon: faCar, keywords: ['conducir', 'transporte', 'viaje', 'auto', 'coche'] },
  { name: 'bus', label: 'Autobús', category: 'home', icon: faBus, keywords: ['transporte', 'commute', 'público', 'bus', 'guagua'] },
  { name: 'motorcycle', label: 'Moto', category: 'home', icon: faMotorcycle, keywords: ['transporte', 'viaje', 'moto', 'scooter', 'patinete'] },
  { name: 'broom', label: 'Limpieza', category: 'home', icon: faBroom, keywords: ['limpiar', 'hogar', 'chores', 'housekeeping', 'barrer', 'escoba'] },
  { name: 'soap', label: 'Higiene', category: 'home', icon: faSoap, keywords: ['lavar', 'baño', 'limpieza', 'jabón', 'ducharse'] },
  { name: 'bath', label: 'Baño', category: 'home', icon: faBath, keywords: ['ducha', 'relax', 'higiene', 'bañera', 'bañarse'] },
  { name: 'tree', label: 'Árbol', category: 'home', icon: faTree, keywords: ['jardín', 'naturaleza', 'patio', 'planta', 'árbol'] },
  { name: 'snowflake', label: 'Nieve', category: 'home', icon: faSnowflake, keywords: ['invierno', 'frío', 'clima', 'nieve', 'copo'] },
  { name: 'umbrella', label: 'Paraguas', category: 'home', icon: faUmbrella, keywords: ['lluvia', 'clima', 'salir', 'paraguas'] },
  { name: 'key', label: 'Llaves', category: 'home', icon: faKey, keywords: ['casa', 'entrada', 'cerradura', 'hogar', 'llave'] },
  { name: 'jug-detergent', label: 'Lavadora', category: 'home', icon: faJugDetergent, keywords: ['lavadora', 'colada', 'detergente', 'ropa sucia', 'lavar', 'laundry'] },
  { name: 'sink', label: 'Fregar', category: 'home', icon: faSink, keywords: ['fregar', 'fregadero', 'platos', 'cocina', 'lavar', 'sink'] },
  { name: 'kitchen-set', label: 'Cocinar', category: 'home', icon: faKitchenSet, keywords: ['cocinar', 'cocina', 'receta', 'cook', 'guisar', 'batch cooking'] },
  { name: 'fire-burner', label: 'Fogón', category: 'home', icon: faFireBurner, keywords: ['fogón', 'cocina', 'hornillo', 'guisar', 'gas'] },
  { name: 'blender', label: 'Batidora', category: 'home', icon: faBlender, keywords: ['batidora', 'batido', 'smoothie', 'licuadora', 'cocina'] },
  { name: 'trash-can', label: 'Basura', category: 'home', icon: faTrashCan, keywords: ['basura', 'cubo', 'sacar la basura', 'residuos', 'papelera'] },
  { name: 'recycle', label: 'Reciclaje', category: 'home', icon: faRecycle, keywords: ['reciclar', 'reciclaje', 'residuos', 'eco', 'sostenible'] },
  { name: 'couch', label: 'Sofá', category: 'home', icon: faCouch, keywords: ['sofá', 'salón', 'descanso', 'casa', 'mueble'] },
  { name: 'chair', label: 'Silla', category: 'home', icon: faChair, keywords: ['silla', 'mueble', 'sentarse', 'postura', 'escritorio'] },
  { name: 'door-open', label: 'Salir de casa', category: 'home', icon: faDoorOpen, keywords: ['puerta', 'salir', 'entrada', 'irse', 'door'] },
  { name: 'plug', label: 'Enchufe', category: 'home', icon: faPlug, keywords: ['enchufe', 'luz', 'electricidad', 'cargar', 'consumo'] },
  { name: 'faucet', label: 'Grifo', category: 'home', icon: faFaucet, keywords: ['grifo', 'agua', 'fontanería', 'ahorro de agua'] },
  { name: 'shower', label: 'Ducha', category: 'home', icon: faShower, keywords: ['ducha', 'ducharse', 'higiene', 'baño', 'shower'] },
  { name: 'hands-bubbles', label: 'Lavarse las manos', category: 'home', icon: faHandsBubbles, keywords: ['manos', 'lavar', 'higiene', 'jabón', 'wash'] },
  { name: 'spray-can-sparkles', label: 'Limpieza a fondo', category: 'home', icon: faSprayCanSparkles, keywords: ['limpiar', 'spray', 'desinfectar', 'brillo', 'orden'] },
  { name: 'plant-wilt', label: 'Regar plantas', category: 'home', icon: faPlantWilt, keywords: ['plantas', 'regar', 'maceta', 'jardín', 'cuidar'] },
  { name: 'basket-shopping', label: 'Cesta', category: 'home', icon: faBasketShopping, keywords: ['cesta', 'compra', 'supermercado', 'lista de la compra'] },
  { name: 'bag-shopping', label: 'Bolsa', category: 'home', icon: faBagShopping, keywords: ['bolsa', 'compra', 'tienda', 'shopping'] },
  { name: 'shop', label: 'Tienda', category: 'home', icon: faShop, keywords: ['tienda', 'comercio', 'barrio', 'recados', 'shop'] },
  { name: 'boxes-stacked', label: 'Ordenar', category: 'home', icon: faBoxesStacked, keywords: ['cajas', 'orden', 'guardar', 'trastero', 'mudanza'] },
  { name: 'screwdriver', label: 'Bricolaje', category: 'home', icon: faScrewdriver, keywords: ['bricolaje', 'destornillador', 'arreglar', 'montar', 'diy'] },
  { name: 'wrench', label: 'Arreglos', category: 'home', icon: faWrench, keywords: ['llave inglesa', 'arreglar', 'reparar', 'fontanería', 'mantenimiento'] },
  { name: 'paint-roller', label: 'Pintar la casa', category: 'home', icon: faPaintRoller, keywords: ['pintar', 'rodillo', 'reforma', 'pared', 'pintura'] },
  { name: 'train', label: 'Tren', category: 'home', icon: faTrain, keywords: ['tren', 'transporte', 'cercanías', 'viaje', 'commute'] },
  { name: 'train-subway', label: 'Metro', category: 'home', icon: faTrainSubway, keywords: ['metro', 'transporte', 'subway', 'ciudad', 'commute'] },
  { name: 'taxi', label: 'Taxi', category: 'home', icon: faTaxi, keywords: ['taxi', 'transporte', 'ciudad', 'viaje'] },
  { name: 'plane', label: 'Avión', category: 'home', icon: faPlane, keywords: ['avión', 'viaje', 'vuelo', 'vacaciones', 'aeropuerto'] },
  { name: 'suitcase-rolling', label: 'Maleta', category: 'home', icon: faSuitcaseRolling, keywords: ['maleta', 'viaje', 'equipaje', 'preparar', 'vacaciones'] },
  { name: 'map-location-dot', label: 'Ruta', category: 'home', icon: faMapLocationDot, keywords: ['mapa', 'ruta', 'ubicación', 'trayecto', 'navegar'] },
  { name: 'gas-pump', label: 'Gasolina', category: 'home', icon: faGasPump, keywords: ['gasolina', 'repostar', 'coche', 'combustible'] },
  { name: 'cloud-rain', label: 'Lluvia', category: 'home', icon: faCloudRain, keywords: ['lluvia', 'clima', 'tiempo', 'paraguas', 'nube'] },
] as const satisfies readonly AppIconEntry[]
