import {
  faBookBookmark,
  faBrain,
  faCampground,
  faCloudSun,
  faClover,
  faFaceGrinStars,
  faFaceLaughBeam,
  faFaceMeh,
  faFaceSadTear,
  faFaceSmile,
  faFaceSmileBeam,
  faFeatherPointed,
  faHandHoldingHeart,
  faHandsPraying,
  faHotTubPerson,
  faInfinity,
  faLeaf,
  faLungs,
  faMugHot,
  faPeace,
  faPersonPraying,
  faPersonRays,
  faQuoteLeft,
  faRainbow,
  faSeedling,
  faSpa,
  faSun,
  faWater,
  faWind,
  faYinYang,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const mindfulnessIcons = [
  { name: 'brain', label: 'Mente', category: 'mindfulness', icon: faBrain, keywords: ['focus', 'cognición', 'meditar', 'estudio', 'mindfulness', 'cerebro'] },
  { name: 'spa', label: 'Meditar', category: 'mindfulness', icon: faSpa, keywords: ['relax', 'wellness', 'calma', 'yoga', 'spa', 'bienestar'] },
  { name: 'seedling', label: 'Crecimiento', category: 'mindfulness', icon: faSeedling, keywords: ['naturaleza', 'hábito', 'planta', 'mindfulness', 'brote', 'empezar'] },
  { name: 'leaf', label: 'Naturaleza', category: 'mindfulness', icon: faLeaf, keywords: ['eco', 'verde', 'aire libre', 'hoja', 'nature'] },
  { name: 'sun', label: 'Sol', category: 'mindfulness', icon: faSun, keywords: ['mañana', 'energía', 'luz', 'despertar', 'sol', 'vitamina d'] },
  { name: 'face-smile', label: 'Ánimo', category: 'mindfulness', icon: faFaceSmile, keywords: ['felicidad', 'positivo', 'humor', 'sonrisa', 'mood'] },
  { name: 'hands-praying', label: 'Gratitud', category: 'mindfulness', icon: faHandsPraying, keywords: ['oración', 'mindfulness', 'spiritual', 'gracias', 'agradecer'] },
  { name: 'lungs', label: 'Respiración', category: 'mindfulness', icon: faLungs, keywords: ['respirar', 'breathing', 'pulmones', 'aire', 'calma', 'ansiedad'] },
  { name: 'wind', label: 'Aire fresco', category: 'mindfulness', icon: faWind, keywords: ['aire', 'viento', 'ventilar', 'fresco', 'respirar'] },
  { name: 'person-praying', label: 'Meditación sentada', category: 'mindfulness', icon: faPersonPraying, keywords: ['meditar', 'meditación', 'sentarse', 'silencio', 'recogimiento', 'rezar'] },
  { name: 'yin-yang', label: 'Equilibrio', category: 'mindfulness', icon: faYinYang, keywords: ['equilibrio', 'balance', 'armonía', 'zen', 'tai chi'] },
  { name: 'peace', label: 'Paz', category: 'mindfulness', icon: faPeace, keywords: ['paz', 'calma', 'tranquilidad', 'peace', 'serenidad'] },
  { name: 'book-bookmark', label: 'Diario', category: 'mindfulness', icon: faBookBookmark, keywords: ['diario', 'journal', 'escribir', 'reflexión', 'cuaderno', 'bitácora'] },
  { name: 'feather-pointed', label: 'Escribir a mano', category: 'mindfulness', icon: faFeatherPointed, keywords: ['pluma', 'escritura', 'reflexión', 'journaling', 'carta'] },
  { name: 'quote-left', label: 'Afirmación', category: 'mindfulness', icon: faQuoteLeft, keywords: ['cita', 'frase', 'afirmación', 'mantra', 'quote', 'motivación'] },
  { name: 'mug-hot', label: 'Infusión', category: 'mindfulness', icon: faMugHot, keywords: ['té', 'te', 'infusión', 'calma', 'tea', 'pausa', 'calor'] },
  { name: 'hot-tub-person', label: 'Baño relajante', category: 'mindfulness', icon: faHotTubPerson, keywords: ['spa', 'jacuzzi', 'relax', 'masaje', 'descanso', 'baño'] },
  { name: 'hand-holding-heart', label: 'Autocuidado', category: 'mindfulness', icon: faHandHoldingHeart, keywords: ['cuidado', 'terapia', 'apoyo', 'amor propio', 'self care', 'psicólogo'] },
  { name: 'campground', label: 'Desconectar', category: 'mindfulness', icon: faCampground, keywords: ['camping', 'acampada', 'naturaleza', 'tienda', 'escapada', 'desconexión'] },
  { name: 'rainbow', label: 'Optimismo', category: 'mindfulness', icon: faRainbow, keywords: ['arcoíris', 'optimismo', 'esperanza', 'color', 'ánimo'] },
  { name: 'water', label: 'Olas', category: 'mindfulness', icon: faWater, keywords: ['agua', 'olas', 'mar', 'calma', 'fluir', 'sonido'] },
  { name: 'cloud-sun', label: 'Cielo', category: 'mindfulness', icon: faCloudSun, keywords: ['cielo', 'nubes', 'clima', 'calma', 'mañana'] },
  { name: 'infinity', label: 'Constancia', category: 'mindfulness', icon: faInfinity, keywords: ['infinito', 'constancia', 'siempre', 'continuidad', 'hábito'] },
  { name: 'clover', label: 'Suerte', category: 'mindfulness', icon: faClover, keywords: ['trébol', 'suerte', 'fortuna', 'luck', 'positivo'] },
  { name: 'person-rays', label: 'Presencia', category: 'mindfulness', icon: faPersonRays, keywords: ['presencia', 'energía', 'aura', 'consciencia', 'mindfulness'] },
  { name: 'face-laugh-beam', label: 'Alegría', category: 'mindfulness', icon: faFaceLaughBeam, keywords: ['reír', 'risa', 'alegría', 'feliz', 'humor'] },
  { name: 'face-smile-beam', label: 'Calma', category: 'mindfulness', icon: faFaceSmileBeam, keywords: ['calma', 'sereno', 'tranquilo', 'bienestar', 'sonrisa'] },
  { name: 'face-grin-stars', label: 'Ilusión', category: 'mindfulness', icon: faFaceGrinStars, keywords: ['ilusión', 'entusiasmo', 'motivación', 'estrellas', 'ganas'] },
  { name: 'face-meh', label: 'Ánimo bajo', category: 'mindfulness', icon: faFaceMeh, keywords: ['neutral', 'regular', 'apatía', 'ánimo', 'mood'] },
  { name: 'face-sad-tear', label: 'Tristeza', category: 'mindfulness', icon: faFaceSadTear, keywords: ['triste', 'llorar', 'ánimo', 'emoción', 'mood'] },
] as const satisfies readonly AppIconEntry[]
