import {
  faAnkh,
  faBahai,
  faBookBible,
  faBookBookmark,
  faBookJournalWhills,
  faBookQuran,
  faBookTanakh,
  faBrain,
  faCampground,
  faChurch,
  faCircleHalfStroke,
  faCloudMoon,
  faCloudSun,
  faClover,
  faCross,
  faDharmachakra,
  faFaceDizzy,
  faFaceFlushed,
  faFaceFrownOpen,
  faFaceGrimace,
  faFaceGrinBeam,
  faFaceGrinStars,
  faFaceKissBeam,
  faFaceLaughBeam,
  faFaceMeh,
  faFaceSadTear,
  faFaceSmile,
  faFaceSmileBeam,
  faFaceSmileWink,
  faFaceTired,
  faFeatherPointed,
  faGopuram,
  faHamsa,
  faHandHoldingHeart,
  faHandsHolding,
  faHandsPraying,
  faHanukiah,
  faHotTubPerson,
  faInfinity,
  faKaaba,
  faKhanda,
  faLeaf,
  faLungs,
  faMenorah,
  faMosque,
  faMugHot,
  faPeace,
  faPersonPraying,
  faPersonRays,
  faPlaceOfWorship,
  faQuoteLeft,
  faRainbow,
  faScrollTorah,
  faSeedling,
  faSpa,
  faSpiral,
  faStarAndCrescent,
  faStarOfDavid,
  faSun,
  faSynagogue,
  faToriiGate,
  faVihara,
  faVolumeOff,
  faWater,
  faWind,
  faYinYang,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const mindfulnessIcons = [
  { name: 'brain', label: 'Mente', category: 'mindfulness', icon: faBrain, keywords: ['focus', 'cognición', 'meditar', 'estudio', 'mindfulness', 'cerebro'] },
  { name: 'spa', label: 'Meditar', category: 'mindfulness', icon: faSpa, keywords: ['relax', 'wellness', 'calma', 'yoga', 'spa', 'bienestar'] },
  { name: 'seedling', label: 'Crecimiento', category: 'mindfulness', icon: faSeedling, keywords: ['naturaleza', 'hábito', 'planta', 'mindfulness', 'brote', 'empezar'] },
  { name: 'leaf', label: 'Naturaleza', category: 'mindfulness', icon: faLeaf, keywords: ['eco', 'verde', 'aire libre', 'hoja', 'nature'] },
  { name: 'sun', label: 'Sol', category: 'mindfulness', icon: faSun, keywords: ['mañana', 'energía', 'luz', 'despertar', 'sol', 'vitamina d'] },
  { name: 'face-smile', label: 'Ánimo', category: 'mindfulness', icon: faFaceSmile, keywords: ['felicidad', 'positivo', 'humor', 'sonrisa', 'mood'] },
  { name: 'hands-praying', label: 'Gratitud', category: 'mindfulness', icon: faHandsPraying, keywords: ['oración', 'mindfulness', 'spiritual', 'gracias', 'agradecer'] },
  { name: 'lungs', label: 'Respiración', category: 'mindfulness', icon: faLungs, keywords: ['respirar', 'breathing', 'pulmones', 'aire', 'calma', 'ansiedad'] },
  { name: 'wind', label: 'Aire fresco', category: 'mindfulness', icon: faWind, keywords: ['aire', 'viento', 'ventilar', 'fresco', 'respirar'] },
  { name: 'person-praying', label: 'Meditación sentada', category: 'mindfulness', icon: faPersonPraying, keywords: ['meditar', 'meditación', 'sentarse', 'silencio', 'recogimiento', 'rezar'] },
  { name: 'yin-yang', label: 'Equilibrio', category: 'mindfulness', icon: faYinYang, keywords: ['equilibrio', 'balance', 'armonía', 'zen', 'tai chi'] },
  { name: 'peace', label: 'Paz', category: 'mindfulness', icon: faPeace, keywords: ['paz', 'calma', 'tranquilidad', 'peace', 'serenidad'] },
  { name: 'book-bookmark', label: 'Diario', category: 'mindfulness', icon: faBookBookmark, keywords: ['diario', 'journal', 'escribir', 'reflexión', 'cuaderno', 'bitácora'] },
  { name: 'feather-pointed', label: 'Escribir a mano', category: 'mindfulness', icon: faFeatherPointed, keywords: ['pluma', 'escritura', 'reflexión', 'journaling', 'carta'] },
  { name: 'quote-left', label: 'Afirmación', category: 'mindfulness', icon: faQuoteLeft, keywords: ['cita', 'frase', 'afirmación', 'mantra', 'quote', 'motivación'] },
  { name: 'mug-hot', label: 'Infusión', category: 'mindfulness', icon: faMugHot, keywords: ['té', 'te', 'infusión', 'calma', 'tea', 'pausa', 'calor'] },
  { name: 'hot-tub-person', label: 'Baño relajante', category: 'mindfulness', icon: faHotTubPerson, keywords: ['spa', 'jacuzzi', 'relax', 'masaje', 'descanso', 'baño'] },
  { name: 'hand-holding-heart', label: 'Autocuidado', category: 'mindfulness', icon: faHandHoldingHeart, keywords: ['cuidado', 'terapia', 'apoyo', 'amor propio', 'self care', 'psicólogo'] },
  { name: 'campground', label: 'Desconectar', category: 'mindfulness', icon: faCampground, keywords: ['camping', 'acampada', 'naturaleza', 'tienda', 'escapada', 'desconexión'] },
  { name: 'rainbow', label: 'Optimismo', category: 'mindfulness', icon: faRainbow, keywords: ['arcoíris', 'optimismo', 'esperanza', 'color', 'ánimo'] },
  { name: 'water', label: 'Olas', category: 'mindfulness', icon: faWater, keywords: ['agua', 'olas', 'mar', 'calma', 'fluir', 'sonido'] },
  { name: 'cloud-sun', label: 'Cielo', category: 'mindfulness', icon: faCloudSun, keywords: ['cielo', 'nubes', 'clima', 'calma', 'mañana'] },
  { name: 'infinity', label: 'Constancia', category: 'mindfulness', icon: faInfinity, keywords: ['infinito', 'constancia', 'siempre', 'continuidad', 'hábito'] },
  { name: 'clover', label: 'Suerte', category: 'mindfulness', icon: faClover, keywords: ['trébol', 'suerte', 'fortuna', 'luck', 'positivo'] },
  { name: 'person-rays', label: 'Presencia', category: 'mindfulness', icon: faPersonRays, keywords: ['presencia', 'energía', 'aura', 'consciencia', 'mindfulness'] },
  { name: 'face-laugh-beam', label: 'Alegría', category: 'mindfulness', icon: faFaceLaughBeam, keywords: ['reír', 'risa', 'alegría', 'feliz', 'humor'] },
  { name: 'face-smile-beam', label: 'Calma', category: 'mindfulness', icon: faFaceSmileBeam, keywords: ['calma', 'sereno', 'tranquilo', 'bienestar', 'sonrisa'] },
  { name: 'face-grin-stars', label: 'Ilusión', category: 'mindfulness', icon: faFaceGrinStars, keywords: ['ilusión', 'entusiasmo', 'motivación', 'estrellas', 'ganas'] },
  { name: 'face-meh', label: 'Ánimo bajo', category: 'mindfulness', icon: faFaceMeh, keywords: ['neutral', 'regular', 'apatía', 'ánimo', 'mood'] },
  { name: 'face-sad-tear', label: 'Tristeza', category: 'mindfulness', icon: faFaceSadTear, keywords: ['triste', 'llorar', 'ánimo', 'emoción', 'mood'] },
  { name: 'place-of-worship', label: 'Lugar de culto', category: 'mindfulness', icon: faPlaceOfWorship, keywords: ['culto', 'templo', 'fe', 'oración'] },
  { name: 'church', label: 'Iglesia', category: 'mindfulness', icon: faChurch, keywords: ['iglesia', 'misa', 'fe', 'oración'] },
  { name: 'mosque', label: 'Mezquita', category: 'mindfulness', icon: faMosque, keywords: ['mezquita', 'oración', 'fe', 'islam'] },
  { name: 'synagogue', label: 'Sinagoga', category: 'mindfulness', icon: faSynagogue, keywords: ['sinagoga', 'fe', 'judaísmo', 'oración'] },
  { name: 'kaaba', label: 'Kaaba', category: 'mindfulness', icon: faKaaba, keywords: ['kaaba', 'meca', 'fe', 'islam'] },
  { name: 'vihara', label: 'Templo budista', category: 'mindfulness', icon: faVihara, keywords: ['templo', 'budismo', 'meditación', 'fe'] },
  { name: 'gopuram', label: 'Templo hindú', category: 'mindfulness', icon: faGopuram, keywords: ['templo', 'hinduismo', 'fe', 'oración'] },
  { name: 'torii-gate', label: 'Torii', category: 'mindfulness', icon: faToriiGate, keywords: ['torii', 'japón', 'sintoísmo', 'templo'] },
  { name: 'menorah', label: 'Menorá', category: 'mindfulness', icon: faMenorah, keywords: ['menorá', 'fe', 'judaísmo', 'velas'] },
  { name: 'hanukiah', label: 'Janukiá', category: 'mindfulness', icon: faHanukiah, keywords: ['janucá', 'fe', 'judaísmo', 'velas'] },
  { name: 'cross', label: 'Cruz', category: 'mindfulness', icon: faCross, keywords: ['cruz', 'fe', 'cristianismo', 'oración'] },
  { name: 'ankh', label: 'Anj', category: 'mindfulness', icon: faAnkh, keywords: ['anj', 'símbolo', 'espiritual', 'vida'] },
  { name: 'star-of-david', label: 'Estrella de David', category: 'mindfulness', icon: faStarOfDavid, keywords: ['estrella', 'judaísmo', 'fe', 'símbolo'] },
  { name: 'star-and-crescent', label: 'Media luna', category: 'mindfulness', icon: faStarAndCrescent, keywords: ['islam', 'fe', 'símbolo', 'luna'] },
  { name: 'dharmachakra', label: 'Rueda del dharma', category: 'mindfulness', icon: faDharmachakra, keywords: ['dharma', 'budismo', 'meditación', 'símbolo'] },
  { name: 'khanda', label: 'Khanda', category: 'mindfulness', icon: faKhanda, keywords: ['sijismo', 'fe', 'símbolo'] },
  { name: 'hamsa', label: 'Hamsa', category: 'mindfulness', icon: faHamsa, keywords: ['hamsa', 'amuleto', 'protección', 'símbolo'] },
  { name: 'bahai', label: 'Estrella bahai', category: 'mindfulness', icon: faBahai, keywords: ['bahai', 'fe', 'símbolo'] },
  { name: 'scroll-torah', label: 'Torá', category: 'mindfulness', icon: faScrollTorah, keywords: ['torá', 'fe', 'lectura', 'judaísmo'] },
  { name: 'book-bible', label: 'Biblia', category: 'mindfulness', icon: faBookBible, keywords: ['biblia', 'lectura', 'fe', 'oración'] },
  { name: 'book-quran', label: 'Corán', category: 'mindfulness', icon: faBookQuran, keywords: ['corán', 'lectura', 'fe', 'islam'] },
  { name: 'book-tanakh', label: 'Tanaj', category: 'mindfulness', icon: faBookTanakh, keywords: ['tanaj', 'lectura', 'fe', 'judaísmo'] },
  { name: 'book-journal-whills', label: 'Libro espiritual', category: 'mindfulness', icon: faBookJournalWhills, keywords: ['libro', 'espiritual', 'lectura', 'reflexión'] },
  { name: 'hands-holding', label: 'Sostener', category: 'mindfulness', icon: faHandsHolding, keywords: ['manos', 'sostener', 'cuidado', 'apoyo'] },
  { name: 'circle-half-stroke', label: 'Equilibrio', category: 'mindfulness', icon: faCircleHalfStroke, keywords: ['equilibrio', 'balance', 'contraste', 'calma'] },
  { name: 'spiral', label: 'Espiral', category: 'mindfulness', icon: faSpiral, keywords: ['espiral', 'calma', 'respiración', 'mente'] },
  { name: 'cloud-moon', label: 'Noche serena', category: 'mindfulness', icon: faCloudMoon, keywords: ['noche', 'luna', 'calma', 'dormir'] },
  { name: 'face-grin-beam', label: 'Alegría', category: 'mindfulness', icon: faFaceGrinBeam, keywords: ['ánimo', 'alegría', 'sonrisa', 'bienestar'] },
  { name: 'face-smile-wink', label: 'Buen ánimo', category: 'mindfulness', icon: faFaceSmileWink, keywords: ['ánimo', 'guiño', 'optimismo', 'sonrisa'] },
  { name: 'face-tired', label: 'Cansancio', category: 'mindfulness', icon: faFaceTired, keywords: ['cansancio', 'agotamiento', 'ánimo', 'descanso'] },
  { name: 'face-dizzy', label: 'Agobio', category: 'mindfulness', icon: faFaceDizzy, keywords: ['agobio', 'mareo', 'estrés', 'ánimo'] },
  { name: 'face-grimace', label: 'Tensión', category: 'mindfulness', icon: faFaceGrimace, keywords: ['tensión', 'estrés', 'ánimo', 'incomodidad'] },
  { name: 'face-frown-open', label: 'Desánimo', category: 'mindfulness', icon: faFaceFrownOpen, keywords: ['desánimo', 'triste', 'ánimo', 'bajón'] },
  { name: 'face-flushed', label: 'Vergüenza', category: 'mindfulness', icon: faFaceFlushed, keywords: ['vergüenza', 'rubor', 'ánimo', 'emoción'] },
  { name: 'face-kiss-beam', label: 'Cariño', category: 'mindfulness', icon: faFaceKissBeam, keywords: ['cariño', 'afecto', 'beso', 'ánimo'] },
  { name: 'volume-off', label: 'Silencio', category: 'mindfulness', icon: faVolumeOff, keywords: ['silencio', 'calma', 'sin ruido', 'desconectar'] },
] as const satisfies readonly AppIconEntry[]
