import {
  faBone,
  faBottleDroplet,
  faBoxTissue,
  faBriefcaseMedical,
  faBrush,
  faBugs,
  faBugSlash,
  faCarRear,
  faCat,
  faCircleDot,
  faCookie,
  faCow,
  faCrow,
  faDog,
  faDove,
  faEyeDropper,
  faFeather,
  faFish,
  faFrog,
  faGlassWaterDroplet,
  faHand,
  faHandHoldingMedical,
  faHandsHoldingCircle,
  faHeartCircleExclamation,
  faHeartCirclePlus,
  faHippo,
  faHorse,
  faHorseHead,
  faHotel,
  faHouseMedical,
  faIdCard,
  faJar,
  faJarWheat,
  faKiwiBird,
  faLocationPin,
  faMagnifyingGlassLocation,
  faMapLocation,
  faMosquito,
  faMosquitoNet,
  faOtter,
  faPaw,
  faPersonCirclePlus,
  faPersonWalkingDashedLineArrowRight,
  faPoop,
  faPrescriptionBottle,
  faPumpSoap,
  faScissors,
  faSheetPlastic,
  faShieldCat,
  faShieldDog,
  faShieldHeart,
  faShrimp,
  faSkullCrossbones,
  faSpider,
  faStaffSnake,
  faTeethOpen,
  faToiletPaper,
  faTrowel,
  faVialCircleCheck,
  faVials,
  faWorm,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const petsIcons = [
  {
    name: 'dog',
    label: 'Perro',
    category: 'pets',
    icon: faDog,
    keywords: ['mascota', 'pet', 'cachorro', 'paseo', 'canino'],
  },
  {
    name: 'cat',
    label: 'Gato',
    category: 'pets',
    icon: faCat,
    keywords: ['mascota', 'pet', 'felino', 'gato'],
  },
  {
    name: 'paw',
    label: 'Huella',
    category: 'pets',
    icon: faPaw,
    keywords: ['mascota', 'pet', 'animal', 'huella', 'perro', 'gato'],
  },
  {
    name: 'fish',
    label: 'Pez',
    category: 'pets',
    icon: faFish,
    keywords: ['mascota', 'pet', 'acuario', 'pecera', 'pez'],
  },
  {
    name: 'dove',
    label: 'Paloma',
    category: 'pets',
    icon: faDove,
    keywords: ['mascota', 'pet', 'ave', 'pájaro', 'bird'],
  },
  {
    name: 'crow',
    label: 'Cuervo',
    category: 'pets',
    icon: faCrow,
    keywords: ['mascota', 'pet', 'ave', 'pájaro', 'bird'],
  },
  {
    name: 'horse',
    label: 'Caballo',
    category: 'pets',
    icon: faHorse,
    keywords: ['mascota', 'pet', 'equino', 'hípica', 'caballo'],
  },
  {
    name: 'frog',
    label: 'Rana',
    category: 'pets',
    icon: faFrog,
    keywords: ['mascota', 'pet', 'anfibio', 'rana'],
  },
  {
    name: 'otter',
    label: 'Nutria',
    category: 'pets',
    icon: faOtter,
    keywords: ['mascota', 'pet', 'animal', 'nutria'],
  },
  {
    name: 'bone',
    label: 'Hueso',
    category: 'pets',
    icon: faBone,
    keywords: ['mascota', 'pet', 'perro', 'comida', 'snack', 'hueso'],
  },
  {
    name: 'feather',
    label: 'Pluma',
    category: 'pets',
    icon: faFeather,
    keywords: ['mascota', 'pet', 'ave', 'pájaro', 'pluma'],
  },
  { name: 'cow', label: 'Vaca', category: 'pets', icon: faCow, keywords: ['vaca', 'granja', 'animal', 'ganado', 'campo'] },
  { name: 'horse-head', label: 'Hípica', category: 'pets', icon: faHorseHead, keywords: ['caballo', 'hípica', 'equitación', 'montar', 'cuadra'] },
  { name: 'hippo', label: 'Hipopótamo', category: 'pets', icon: faHippo, keywords: ['hipopótamo', 'animal', 'zoo', 'salvaje'] },
  { name: 'kiwi-bird', label: 'Ave exótica', category: 'pets', icon: faKiwiBird, keywords: ['ave', 'pájaro', 'exótico', 'kiwi', 'bird'] },
  { name: 'spider', label: 'Araña', category: 'pets', icon: faSpider, keywords: ['araña', 'insecto', 'terrario', 'bicho'] },
  { name: 'bugs', label: 'Insectos', category: 'pets', icon: faBugs, keywords: ['insectos', 'bichos', 'plaga', 'hormigas'] },
  { name: 'mosquito', label: 'Mosquito', category: 'pets', icon: faMosquito, keywords: ['mosquito', 'insecto', 'picadura', 'plaga'] },
  { name: 'worm', label: 'Gusano', category: 'pets', icon: faWorm, keywords: ['gusano', 'lombriz', 'compost', 'tierra'] },
  { name: 'shrimp', label: 'Gamba', category: 'pets', icon: faShrimp, keywords: ['gamba', 'marisco', 'acuario', 'camarón'] },
  { name: 'jar', label: 'Comida de mascota', category: 'pets', icon: faJar, keywords: ['pienso', 'comida', 'bote', 'mascota', 'alimentar'] },
  { name: 'briefcase-medical', label: 'Veterinario', category: 'pets', icon: faBriefcaseMedical, keywords: ['veterinario', 'vet', 'mascota', 'salud animal', 'revisión'] },
  { name: 'scissors', label: 'Peluquería canina', category: 'pets', icon: faScissors, keywords: ['peluquería', 'cortar', 'pelo', 'aseo', 'tijeras', 'grooming'] },
  { name: 'shield-dog', label: 'Cuidado del perro', category: 'pets', icon: faShieldDog, keywords: ['perro', 'protección', 'seguro', 'cuidado', 'mascota'] },
  { name: 'shield-cat', label: 'Cuidado del gato', category: 'pets', icon: faShieldCat, keywords: ['gato', 'protección', 'seguro', 'cuidado', 'mascota'] },
  { name: 'jar-wheat', label: 'Pienso', category: 'pets', icon: faJarWheat, keywords: ['pienso', 'comida', 'mascota', 'alimentar', 'saco'] },
  { name: 'glass-water-droplet', label: 'Agua fresca', category: 'pets', icon: faGlassWaterDroplet, keywords: ['agua', 'bebedero', 'mascota', 'rellenar'] },
  { name: 'cookie', label: 'Premio', category: 'pets', icon: faCookie, keywords: ['premio', 'galleta', 'recompensa', 'adiestrar'] },
  { name: 'bottle-droplet', label: 'Champú de mascota', category: 'pets', icon: faBottleDroplet, keywords: ['champú', 'baño', 'aseo', 'mascota'] },
  { name: 'brush', label: 'Cepillado', category: 'pets', icon: faBrush, keywords: ['cepillar', 'pelo', 'aseo', 'mascota'] },
  { name: 'pump-soap', label: 'Jabón', category: 'pets', icon: faPumpSoap, keywords: ['jabón', 'lavar', 'higiene', 'baño'] },
  { name: 'teeth-open', label: 'Limpieza dental', category: 'pets', icon: faTeethOpen, keywords: ['dientes', 'boca', 'cepillar', 'mascota'] },
  { name: 'eye-dropper', label: 'Pipeta antiparasitaria', category: 'pets', icon: faEyeDropper, keywords: ['pipeta', 'antiparasitario', 'pulgas', 'tratamiento'] },
  { name: 'bug-slash', label: 'Antiparasitario', category: 'pets', icon: faBugSlash, keywords: ['antiparasitario', 'pulgas', 'garrapatas', 'tratamiento'] },
  { name: 'mosquito-net', label: 'Mosquitera', category: 'pets', icon: faMosquitoNet, keywords: ['mosquitera', 'protección', 'insectos', 'picaduras'] },
  { name: 'trowel', label: 'Pala de arena', category: 'pets', icon: faTrowel, keywords: ['pala', 'arenero', 'limpiar', 'gato'] },
  { name: 'poop', label: 'Recoger los excrementos', category: 'pets', icon: faPoop, keywords: ['caca', 'excrementos', 'recoger', 'paseo'] },
  { name: 'toilet-paper', label: 'Empapadores', category: 'pets', icon: faToiletPaper, keywords: ['papel', 'limpiar', 'accidentes', 'cachorro'] },
  { name: 'sheet-plastic', label: 'Proteger el suelo', category: 'pets', icon: faSheetPlastic, keywords: ['empapador', 'plástico', 'proteger', 'suelo'] },
  { name: 'box-tissue', label: 'Toallitas', category: 'pets', icon: faBoxTissue, keywords: ['toallitas', 'limpiar', 'higiene', 'mascota'] },
  { name: 'person-walking-dashed-line-arrow-right', label: 'Sacar a pasear', category: 'pets', icon: faPersonWalkingDashedLineArrowRight, keywords: ['paseo', 'perro', 'ruta', 'caminar'] },
  { name: 'map-location', label: 'Ruta del paseo', category: 'pets', icon: faMapLocation, keywords: ['ruta', 'paseo', 'mapa', 'perro'] },
  { name: 'location-pin', label: 'Localizador', category: 'pets', icon: faLocationPin, keywords: ['localizador', 'gps', 'ubicación', 'mascota'] },
  { name: 'magnifying-glass-location', label: 'Buscar a la mascota', category: 'pets', icon: faMagnifyingGlassLocation, keywords: ['buscar', 'perdida', 'localizar', 'mascota'] },
  { name: 'car-rear', label: 'Viajar con la mascota', category: 'pets', icon: faCarRear, keywords: ['coche', 'transporte', 'viaje', 'llevar'] },
  { name: 'hotel', label: 'Residencia de mascotas', category: 'pets', icon: faHotel, keywords: ['residencia', 'guardería', 'hotel', 'cuidado'] },
  { name: 'house-medical', label: 'Clínica veterinaria', category: 'pets', icon: faHouseMedical, keywords: ['clínica', 'veterinario', 'consulta', 'salud animal'] },
  { name: 'staff-snake', label: 'Veterinaria', category: 'pets', icon: faStaffSnake, keywords: ['veterinaria', 'medicina', 'salud animal', 'consulta'] },
  { name: 'vial-circle-check', label: 'Vacuna', category: 'pets', icon: faVialCircleCheck, keywords: ['vacuna', 'vacunación', 'veterinario', 'cartilla'] },
  { name: 'vials', label: 'Analítica', category: 'pets', icon: faVials, keywords: ['analítica', 'muestras', 'veterinario', 'revisión'] },
  { name: 'prescription-bottle', label: 'Medicina de la mascota', category: 'pets', icon: faPrescriptionBottle, keywords: ['medicina', 'bote', 'tratamiento', 'veterinario'] },
  { name: 'hand-holding-medical', label: 'Dar la medicación', category: 'pets', icon: faHandHoldingMedical, keywords: ['medicación', 'dar', 'pastilla', 'mascota'] },
  { name: 'heart-circle-exclamation', label: 'Revisión urgente', category: 'pets', icon: faHeartCircleExclamation, keywords: ['revisión', 'alerta', 'salud', 'mascota'] },
  { name: 'heart-circle-plus', label: 'Adoptar', category: 'pets', icon: faHeartCirclePlus, keywords: ['adoptar', 'acoger', 'cuidar', 'mascota'] },
  { name: 'hands-holding-circle', label: 'Acoger', category: 'pets', icon: faHandsHoldingCircle, keywords: ['acoger', 'cuidar', 'proteger', 'mascota'] },
  { name: 'person-circle-plus', label: 'Nuevo miembro', category: 'pets', icon: faPersonCirclePlus, keywords: ['adoptar', 'familia', 'nuevo', 'mascota'] },
  { name: 'shield-heart', label: 'Seguro de mascota', category: 'pets', icon: faShieldHeart, keywords: ['seguro', 'póliza', 'proteger', 'mascota'] },
  { name: 'id-card', label: 'Cartilla', category: 'pets', icon: faIdCard, keywords: ['cartilla', 'identificación', 'documento', 'veterinario'] },
  { name: 'hand', label: 'Orden de quieto', category: 'pets', icon: faHand, keywords: ['adiestrar', 'orden', 'quieto', 'mano'] },
  { name: 'circle-dot', label: 'Pelota', category: 'pets', icon: faCircleDot, keywords: ['pelota', 'juego', 'jugar', 'perro'] },
  { name: 'skull-crossbones', label: 'Tóxico para la mascota', category: 'pets', icon: faSkullCrossbones, keywords: ['tóxico', 'veneno', 'peligro', 'prohibido'] },
] as const satisfies readonly AppIconEntry[]
