import {
  faBone,
  faBriefcaseMedical,
  faBugs,
  faCat,
  faCow,
  faCrow,
  faDog,
  faDove,
  faFeather,
  faFish,
  faFrog,
  faHippo,
  faHorse,
  faHorseHead,
  faJar,
  faKiwiBird,
  faMosquito,
  faOtter,
  faPaw,
  faScissors,
  faShieldCat,
  faShieldDog,
  faShrimp,
  faSpider,
  faWorm,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const petsIcons = [
  {
    name: 'dog',
    label: 'Perro',
    category: 'pets',
    icon: faDog,
    keywords: ['mascota', 'pet', 'cachorro', 'paseo', 'canino'],
  },
  {
    name: 'cat',
    label: 'Gato',
    category: 'pets',
    icon: faCat,
    keywords: ['mascota', 'pet', 'felino', 'gato'],
  },
  {
    name: 'paw',
    label: 'Huella',
    category: 'pets',
    icon: faPaw,
    keywords: ['mascota', 'pet', 'animal', 'huella', 'perro', 'gato'],
  },
  {
    name: 'fish',
    label: 'Pez',
    category: 'pets',
    icon: faFish,
    keywords: ['mascota', 'pet', 'acuario', 'pecera', 'pez'],
  },
  {
    name: 'dove',
    label: 'Paloma',
    category: 'pets',
    icon: faDove,
    keywords: ['mascota', 'pet', 'ave', 'pájaro', 'bird'],
  },
  {
    name: 'crow',
    label: 'Cuervo',
    category: 'pets',
    icon: faCrow,
    keywords: ['mascota', 'pet', 'ave', 'pájaro', 'bird'],
  },
  {
    name: 'horse',
    label: 'Caballo',
    category: 'pets',
    icon: faHorse,
    keywords: ['mascota', 'pet', 'equino', 'hípica', 'caballo'],
  },
  {
    name: 'frog',
    label: 'Rana',
    category: 'pets',
    icon: faFrog,
    keywords: ['mascota', 'pet', 'anfibio', 'rana'],
  },
  {
    name: 'otter',
    label: 'Nutria',
    category: 'pets',
    icon: faOtter,
    keywords: ['mascota', 'pet', 'animal', 'nutria'],
  },
  {
    name: 'bone',
    label: 'Hueso',
    category: 'pets',
    icon: faBone,
    keywords: ['mascota', 'pet', 'perro', 'comida', 'snack', 'hueso'],
  },
  {
    name: 'feather',
    label: 'Pluma',
    category: 'pets',
    icon: faFeather,
    keywords: ['mascota', 'pet', 'ave', 'pájaro', 'pluma'],
  },
  { name: 'cow', label: 'Vaca', category: 'pets', icon: faCow, keywords: ['vaca', 'granja', 'animal', 'ganado', 'campo'] },
  { name: 'horse-head', label: 'Hípica', category: 'pets', icon: faHorseHead, keywords: ['caballo', 'hípica', 'equitación', 'montar', 'cuadra'] },
  { name: 'hippo', label: 'Hipopótamo', category: 'pets', icon: faHippo, keywords: ['hipopótamo', 'animal', 'zoo', 'salvaje'] },
  { name: 'kiwi-bird', label: 'Ave exótica', category: 'pets', icon: faKiwiBird, keywords: ['ave', 'pájaro', 'exótico', 'kiwi', 'bird'] },
  { name: 'spider', label: 'Araña', category: 'pets', icon: faSpider, keywords: ['araña', 'insecto', 'terrario', 'bicho'] },
  { name: 'bugs', label: 'Insectos', category: 'pets', icon: faBugs, keywords: ['insectos', 'bichos', 'plaga', 'hormigas'] },
  { name: 'mosquito', label: 'Mosquito', category: 'pets', icon: faMosquito, keywords: ['mosquito', 'insecto', 'picadura', 'plaga'] },
  { name: 'worm', label: 'Gusano', category: 'pets', icon: faWorm, keywords: ['gusano', 'lombriz', 'compost', 'tierra'] },
  { name: 'shrimp', label: 'Gamba', category: 'pets', icon: faShrimp, keywords: ['gamba', 'marisco', 'acuario', 'camarón'] },
  { name: 'jar', label: 'Comida de mascota', category: 'pets', icon: faJar, keywords: ['pienso', 'comida', 'bote', 'mascota', 'alimentar'] },
  { name: 'briefcase-medical', label: 'Veterinario', category: 'pets', icon: faBriefcaseMedical, keywords: ['veterinario', 'vet', 'mascota', 'salud animal', 'revisión'] },
  { name: 'scissors', label: 'Peluquería canina', category: 'pets', icon: faScissors, keywords: ['peluquería', 'cortar', 'pelo', 'aseo', 'tijeras', 'grooming'] },
  { name: 'shield-dog', label: 'Cuidado del perro', category: 'pets', icon: faShieldDog, keywords: ['perro', 'protección', 'seguro', 'cuidado', 'mascota'] },
  { name: 'shield-cat', label: 'Cuidado del gato', category: 'pets', icon: faShieldCat, keywords: ['gato', 'protección', 'seguro', 'cuidado', 'mascota'] },
] as const satisfies readonly AppIconEntry[]
