import {
  faBone,
  faCat,
  faCrow,
  faDog,
  faDove,
  faFeather,
  faFish,
  faFrog,
  faHorse,
  faOtter,
  faPaw,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const petsIcons = [
  {
    name: 'dog',
    label: 'Perro',
    category: 'pets',
    icon: faDog,
    keywords: ['mascota', 'pet', 'cachorro', 'paseo', 'canino'],
  },
  {
    name: 'cat',
    label: 'Gato',
    category: 'pets',
    icon: faCat,
    keywords: ['mascota', 'pet', 'felino', 'gato'],
  },
  {
    name: 'paw',
    label: 'Huella',
    category: 'pets',
    icon: faPaw,
    keywords: ['mascota', 'pet', 'animal', 'huella', 'perro', 'gato'],
  },
  {
    name: 'fish',
    label: 'Pez',
    category: 'pets',
    icon: faFish,
    keywords: ['mascota', 'pet', 'acuario', 'pecera', 'pez'],
  },
  {
    name: 'dove',
    label: 'Paloma',
    category: 'pets',
    icon: faDove,
    keywords: ['mascota', 'pet', 'ave', 'pájaro', 'bird'],
  },
  {
    name: 'crow',
    label: 'Cuervo',
    category: 'pets',
    icon: faCrow,
    keywords: ['mascota', 'pet', 'ave', 'pájaro', 'bird'],
  },
  {
    name: 'horse',
    label: 'Caballo',
    category: 'pets',
    icon: faHorse,
    keywords: ['mascota', 'pet', 'equino', 'hípica', 'caballo'],
  },
  {
    name: 'frog',
    label: 'Rana',
    category: 'pets',
    icon: faFrog,
    keywords: ['mascota', 'pet', 'anfibio', 'rana'],
  },
  {
    name: 'otter',
    label: 'Nutria',
    category: 'pets',
    icon: faOtter,
    keywords: ['mascota', 'pet', 'animal', 'nutria'],
  },
  {
    name: 'bone',
    label: 'Hueso',
    category: 'pets',
    icon: faBone,
    keywords: ['mascota', 'pet', 'perro', 'comida', 'snack', 'hueso'],
  },
  {
    name: 'feather',
    label: 'Pluma',
    category: 'pets',
    icon: faFeather,
    keywords: ['mascota', 'pet', 'ave', 'pájaro', 'pluma'],
  },
] as const satisfies readonly AppIconEntry[]
