import {
  faArrowsRotate,
  faBarsProgress,
  faBookmark,
  faBullseye,
  faCalendar,
  faCalendarCheck,
  faCalendarDays,
  faCalendarPlus,
  faCalendarXmark,
  faChartSimple,
  faCheckDouble,
  faCircleCheck,
  faClipboard,
  faClipboardList,
  faClock,
  faClockRotateLeft,
  faCrown,
  faFlag,
  faFolderTree,
  faGaugeSimpleHigh,
  faHourglass,
  faHourglassHalf,
  faListCheck,
  faListUl,
  faLocationCrosshairs,
  faNoteSticky,
  faRepeat,
  faRocket,
  faSquarePollVertical,
  faStopwatch,
  faTag,
  faThumbtack,
  faTrophy,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const productivityIcons = [
  { name: 'calendar', label: 'Calendario', category: 'productivity', icon: faCalendar, keywords: ['fecha', 'evento', 'agenda', 'calendario'] },
  { name: 'calendar-days', label: 'Calendario días', category: 'productivity', icon: faCalendarDays, keywords: ['semana', 'planificación', 'schedule', 'mes', 'agenda'] },
  { name: 'clock', label: 'Reloj', category: 'productivity', icon: faClock, keywords: ['tiempo', 'hora', 'duración', 'reloj'] },
  { name: 'stopwatch', label: 'Cronómetro', category: 'productivity', icon: faStopwatch, keywords: ['timer', 'intervalo', 'tiempo', 'pomodoro', 'cronómetro'] },
  { name: 'hourglass', label: 'Reloj de arena', category: 'productivity', icon: faHourglass, keywords: ['espera', 'deadline', 'plazo', 'tiempo'] },
  { name: 'list-check', label: 'Lista de tareas', category: 'productivity', icon: faListCheck, keywords: ['tareas', 'habits', 'checklist', 'hábitos', 'to do'] },
  { name: 'clipboard', label: 'Portapapeles', category: 'productivity', icon: faClipboard, keywords: ['notas', 'copiar', 'lista', 'portapapeles'] },
  { name: 'bars-progress', label: 'Progreso', category: 'productivity', icon: faBarsProgress, keywords: ['avance', 'proyecto', 'status', 'progreso'] },
  { name: 'bookmark', label: 'Marcador', category: 'productivity', icon: faBookmark, keywords: ['guardar', 'referencia', 'favorito', 'marcador'] },
  { name: 'target', label: 'Objetivo', category: 'productivity', icon: faBullseye, keywords: ['bullseye', 'meta', 'objetivo', 'focus', 'diana'] },
  { name: 'trophy', label: 'Logro', category: 'productivity', icon: faTrophy, keywords: ['premio', 'recompensa', 'hito', 'trofeo', 'logro'] },
  { name: 'flag', label: 'Meta', category: 'productivity', icon: faFlag, keywords: ['objetivo', 'hito', 'prioridad', 'marcador', 'bandera'] },
  { name: 'tag', label: 'Etiqueta', category: 'productivity', icon: faTag, keywords: ['tags', 'categoría', 'clasificar', 'label', 'etiqueta'] },
  { name: 'calendar-check', label: 'Día cumplido', category: 'productivity', icon: faCalendarCheck, keywords: ['cumplido', 'hecho', 'día', 'racha', 'completado'] },
  { name: 'calendar-plus', label: 'Nuevo evento', category: 'productivity', icon: faCalendarPlus, keywords: ['añadir', 'evento', 'cita', 'agendar', 'planificar'] },
  { name: 'calendar-xmark', label: 'Día libre', category: 'productivity', icon: faCalendarXmark, keywords: ['libre', 'descanso', 'cancelar', 'vacaciones', 'sin plan'] },
  { name: 'clock-rotate-left', label: 'Historial', category: 'productivity', icon: faClockRotateLeft, keywords: ['historial', 'pasado', 'revisar', 'deshacer', 'registro'] },
  { name: 'hourglass-half', label: 'A medias', category: 'productivity', icon: faHourglassHalf, keywords: ['a medias', 'en curso', 'progreso', 'tiempo', 'pendiente'] },
  { name: 'list-ul', label: 'Lista', category: 'productivity', icon: faListUl, keywords: ['lista', 'puntos', 'enumerar', 'apuntes'] },
  { name: 'clipboard-list', label: 'Checklist', category: 'productivity', icon: faClipboardList, keywords: ['checklist', 'lista', 'tareas', 'repaso', 'control'] },
  { name: 'note-sticky', label: 'Nota', category: 'productivity', icon: faNoteSticky, keywords: ['nota', 'post it', 'recordar', 'apunte', 'idea'] },
  { name: 'thumbtack', label: 'Fijar', category: 'productivity', icon: faThumbtack, keywords: ['fijar', 'chincheta', 'destacar', 'pin', 'importante'] },
  { name: 'folder-tree', label: 'Organización', category: 'productivity', icon: faFolderTree, keywords: ['organizar', 'carpetas', 'estructura', 'orden', 'archivo'] },
  { name: 'arrows-rotate', label: 'Rutina', category: 'productivity', icon: faArrowsRotate, keywords: ['rutina', 'repetir', 'ciclo', 'diario', 'refrescar'] },
  { name: 'repeat', label: 'Repetición', category: 'productivity', icon: faRepeat, keywords: ['repetir', 'otra vez', 'frecuencia', 'loop', 'constancia'] },
  { name: 'circle-check', label: 'Completado', category: 'productivity', icon: faCircleCheck, keywords: ['completado', 'hecho', 'ok', 'listo', 'done'] },
  { name: 'check-double', label: 'Todo hecho', category: 'productivity', icon: faCheckDouble, keywords: ['todo hecho', 'doble', 'confirmado', 'terminado'] },
  { name: 'chart-simple', label: 'Estadísticas', category: 'productivity', icon: faChartSimple, keywords: ['estadísticas', 'progreso', 'barras', 'datos', 'resumen'] },
  { name: 'square-poll-vertical', label: 'Balance semanal', category: 'productivity', icon: faSquarePollVertical, keywords: ['balance', 'encuesta', 'resumen', 'semana', 'análisis'] },
  { name: 'gauge-simple-high', label: 'Rendimiento', category: 'productivity', icon: faGaugeSimpleHigh, keywords: ['rendimiento', 'nivel', 'medidor', 'productividad', 'tope'] },
  { name: 'rocket', label: 'Impulso', category: 'productivity', icon: faRocket, keywords: ['impulso', 'lanzar', 'empezar', 'cohete', 'arrancar'] },
  { name: 'crown', label: 'Nivel máximo', category: 'productivity', icon: faCrown, keywords: ['corona', 'nivel', 'maestría', 'rey', 'premium'] },
  { name: 'location-crosshairs', label: 'Enfoque', category: 'productivity', icon: faLocationCrosshairs, keywords: ['enfoque', 'foco', 'concentración', 'centrar', 'precisión'] },
] as const satisfies readonly AppIconEntry[]
