import {
  faAlarmClock,
  faArrowDownShortWide,
  faArrowsRotate,
  faArrowUpRightDots,
  faBarsProgress,
  faBarsStaggered,
  faBellSlash,
  faBookmark,
  faBullseye,
  faCalendar,
  faCalendarCheck,
  faCalendarDays,
  faCalendarPlus,
  faCalendarXmark,
  faChartArea,
  faChartGantt,
  faChartSimple,
  faCheckDouble,
  faCircleCheck,
  faClipboard,
  faClipboardList,
  faClock,
  faClockRotateLeft,
  faClone,
  faCopy,
  faCrosshairs,
  faCrown,
  faDiagramNext,
  faFilePen,
  faFlag,
  faFolderClosed,
  faFolderOpen,
  faFolderPlus,
  faFolderTree,
  faGauge,
  faGaugeSimpleHigh,
  faGroupArrowsRotate,
  faHourglass,
  faHourglassEnd,
  faHourglassHalf,
  faHourglassStart,
  faInbox,
  faList,
  faListCheck,
  faListOl,
  faListUl,
  faLocationCrosshairs,
  faNoteSticky,
  faPaperclip,
  faPaste,
  faRectangleList,
  faRepeat,
  faRocket,
  faRotateRight,
  faRoute,
  faSignature,
  faSliders,
  faSort,
  faSquareCheck,
  faSquarePen,
  faSquarePollHorizontal,
  faSquarePollVertical,
  faStamp,
  faStopwatch,
  faTableColumns,
  faTag,
  faThumbtack,
  faTimeline,
  faTrophy,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const productivityIcons = [
  { name: 'calendar', label: 'Calendario', category: 'productivity', icon: faCalendar, keywords: ['fecha', 'evento', 'agenda', 'calendario'] },
  { name: 'calendar-days', label: 'Calendario días', category: 'productivity', icon: faCalendarDays, keywords: ['semana', 'planificación', 'schedule', 'mes', 'agenda'] },
  { name: 'clock', label: 'Reloj', category: 'productivity', icon: faClock, keywords: ['tiempo', 'hora', 'duración', 'reloj'] },
  { name: 'stopwatch', label: 'Cronómetro', category: 'productivity', icon: faStopwatch, keywords: ['timer', 'intervalo', 'tiempo', 'pomodoro', 'cronómetro'] },
  { name: 'hourglass', label: 'Reloj de arena', category: 'productivity', icon: faHourglass, keywords: ['espera', 'deadline', 'plazo', 'tiempo'] },
  { name: 'list-check', label: 'Lista de tareas', category: 'productivity', icon: faListCheck, keywords: ['tareas', 'habits', 'checklist', 'hábitos', 'to do'] },
  { name: 'clipboard', label: 'Portapapeles', category: 'productivity', icon: faClipboard, keywords: ['notas', 'copiar', 'lista', 'portapapeles'] },
  { name: 'bars-progress', label: 'Progreso', category: 'productivity', icon: faBarsProgress, keywords: ['avance', 'proyecto', 'status', 'progreso'] },
  { name: 'bookmark', label: 'Marcador', category: 'productivity', icon: faBookmark, keywords: ['guardar', 'referencia', 'favorito', 'marcador'] },
  { name: 'target', label: 'Objetivo', category: 'productivity', icon: faBullseye, keywords: ['bullseye', 'meta', 'objetivo', 'focus', 'diana'] },
  { name: 'trophy', label: 'Logro', category: 'productivity', icon: faTrophy, keywords: ['premio', 'recompensa', 'hito', 'trofeo', 'logro'] },
  { name: 'flag', label: 'Meta', category: 'productivity', icon: faFlag, keywords: ['objetivo', 'hito', 'prioridad', 'marcador', 'bandera'] },
  { name: 'tag', label: 'Etiqueta', category: 'productivity', icon: faTag, keywords: ['tags', 'categoría', 'clasificar', 'label', 'etiqueta'] },
  { name: 'calendar-check', label: 'Día cumplido', category: 'productivity', icon: faCalendarCheck, keywords: ['cumplido', 'hecho', 'día', 'racha', 'completado'] },
  { name: 'calendar-plus', label: 'Nuevo evento', category: 'productivity', icon: faCalendarPlus, keywords: ['añadir', 'evento', 'cita', 'agendar', 'planificar'] },
  { name: 'calendar-xmark', label: 'Día libre', category: 'productivity', icon: faCalendarXmark, keywords: ['libre', 'descanso', 'cancelar', 'vacaciones', 'sin plan'] },
  { name: 'clock-rotate-left', label: 'Historial', category: 'productivity', icon: faClockRotateLeft, keywords: ['historial', 'pasado', 'revisar', 'deshacer', 'registro'] },
  { name: 'hourglass-half', label: 'A medias', category: 'productivity', icon: faHourglassHalf, keywords: ['a medias', 'en curso', 'progreso', 'tiempo', 'pendiente'] },
  { name: 'list-ul', label: 'Lista', category: 'productivity', icon: faListUl, keywords: ['lista', 'puntos', 'enumerar', 'apuntes'] },
  { name: 'clipboard-list', label: 'Checklist', category: 'productivity', icon: faClipboardList, keywords: ['checklist', 'lista', 'tareas', 'repaso', 'control'] },
  { name: 'note-sticky', label: 'Nota', category: 'productivity', icon: faNoteSticky, keywords: ['nota', 'post it', 'recordar', 'apunte', 'idea'] },
  { name: 'thumbtack', label: 'Fijar', category: 'productivity', icon: faThumbtack, keywords: ['fijar', 'chincheta', 'destacar', 'pin', 'importante'] },
  { name: 'folder-tree', label: 'Organización', category: 'productivity', icon: faFolderTree, keywords: ['organizar', 'carpetas', 'estructura', 'orden', 'archivo'] },
  { name: 'arrows-rotate', label: 'Rutina', category: 'productivity', icon: faArrowsRotate, keywords: ['rutina', 'repetir', 'ciclo', 'diario', 'refrescar'] },
  { name: 'repeat', label: 'Repetición', category: 'productivity', icon: faRepeat, keywords: ['repetir', 'otra vez', 'frecuencia', 'loop', 'constancia'] },
  { name: 'circle-check', label: 'Completado', category: 'productivity', icon: faCircleCheck, keywords: ['completado', 'hecho', 'ok', 'listo', 'done'] },
  { name: 'check-double', label: 'Todo hecho', category: 'productivity', icon: faCheckDouble, keywords: ['todo hecho', 'doble', 'confirmado', 'terminado'] },
  { name: 'chart-simple', label: 'Estadísticas', category: 'productivity', icon: faChartSimple, keywords: ['estadísticas', 'progreso', 'barras', 'datos', 'resumen'] },
  { name: 'square-poll-vertical', label: 'Balance semanal', category: 'productivity', icon: faSquarePollVertical, keywords: ['balance', 'encuesta', 'resumen', 'semana', 'análisis'] },
  { name: 'gauge-simple-high', label: 'Rendimiento', category: 'productivity', icon: faGaugeSimpleHigh, keywords: ['rendimiento', 'nivel', 'medidor', 'productividad', 'tope'] },
  { name: 'rocket', label: 'Impulso', category: 'productivity', icon: faRocket, keywords: ['impulso', 'lanzar', 'empezar', 'cohete', 'arrancar'] },
  { name: 'crown', label: 'Nivel máximo', category: 'productivity', icon: faCrown, keywords: ['corona', 'nivel', 'maestría', 'rey', 'premium'] },
  { name: 'location-crosshairs', label: 'Enfoque', category: 'productivity', icon: faLocationCrosshairs, keywords: ['enfoque', 'foco', 'concentración', 'centrar', 'precisión'] },
  { name: 'list', label: 'Lista', category: 'productivity', icon: faList, keywords: ['lista', 'listado', 'tareas', 'puntos'] },
  { name: 'list-ol', label: 'Lista numerada', category: 'productivity', icon: faListOl, keywords: ['lista', 'numerada', 'orden', 'pasos'] },
  { name: 'rectangle-list', label: 'Checklist', category: 'productivity', icon: faRectangleList, keywords: ['checklist', 'lista', 'tareas', 'repaso'] },
  { name: 'square-check', label: 'Casilla marcada', category: 'productivity', icon: faSquareCheck, keywords: ['hecho', 'completado', 'marcar', 'check'] },
  { name: 'square-pen', label: 'Anotar', category: 'productivity', icon: faSquarePen, keywords: ['anotar', 'escribir', 'nota', 'editar'] },
  { name: 'file-pen', label: 'Redactar', category: 'productivity', icon: faFilePen, keywords: ['redactar', 'documento', 'escribir', 'borrador'] },
  { name: 'paperclip', label: 'Adjuntar', category: 'productivity', icon: faPaperclip, keywords: ['adjuntar', 'clip', 'archivo', 'documento'] },
  { name: 'copy', label: 'Copiar', category: 'productivity', icon: faCopy, keywords: ['copiar', 'duplicar', 'archivo'] },
  { name: 'paste', label: 'Pegar', category: 'productivity', icon: faPaste, keywords: ['pegar', 'portapapeles', 'copiar'] },
  { name: 'clone', label: 'Duplicar', category: 'productivity', icon: faClone, keywords: ['duplicar', 'clonar', 'copia', 'plantilla'] },
  { name: 'inbox', label: 'Bandeja de entrada', category: 'productivity', icon: faInbox, keywords: ['bandeja', 'inbox', 'correo', 'vaciar', 'pendientes'] },
  { name: 'folder-open', label: 'Carpeta abierta', category: 'productivity', icon: faFolderOpen, keywords: ['carpeta', 'abrir', 'archivos', 'organizar'] },
  { name: 'folder-closed', label: 'Carpeta', category: 'productivity', icon: faFolderClosed, keywords: ['carpeta', 'archivar', 'organizar'] },
  { name: 'folder-plus', label: 'Nueva carpeta', category: 'productivity', icon: faFolderPlus, keywords: ['carpeta', 'crear', 'organizar'] },
  { name: 'table-columns', label: 'Tablero', category: 'productivity', icon: faTableColumns, keywords: ['tablero', 'kanban', 'columnas', 'organizar'] },
  { name: 'timeline', label: 'Cronología', category: 'productivity', icon: faTimeline, keywords: ['cronología', 'línea de tiempo', 'plan', 'hitos'] },
  { name: 'chart-gantt', label: 'Planificación', category: 'productivity', icon: faChartGantt, keywords: ['gantt', 'plan', 'proyecto', 'calendario'] },
  { name: 'route', label: 'Ruta', category: 'productivity', icon: faRoute, keywords: ['ruta', 'plan', 'camino', 'pasos'] },
  { name: 'sort', label: 'Ordenar', category: 'productivity', icon: faSort, keywords: ['ordenar', 'clasificar', 'prioridad'] },
  { name: 'arrow-down-short-wide', label: 'Prioridad', category: 'productivity', icon: faArrowDownShortWide, keywords: ['ordenar', 'prioridad', 'clasificar', 'filtrar'] },
  { name: 'bars-staggered', label: 'Lista de pasos', category: 'productivity', icon: faBarsStaggered, keywords: ['lista', 'pasos', 'orden', 'tareas'] },
  { name: 'hourglass-start', label: 'Empezar el tiempo', category: 'productivity', icon: faHourglassStart, keywords: ['reloj', 'arena', 'empezar', 'tiempo'] },
  { name: 'hourglass-end', label: 'Tiempo agotado', category: 'productivity', icon: faHourglassEnd, keywords: ['reloj', 'arena', 'fin', 'tiempo'] },
  { name: 'alarm-clock', label: 'Alarma', category: 'productivity', icon: faAlarmClock, keywords: ['alarma', 'despertador', 'hora', 'recordatorio'] },
  { name: 'bell-slash', label: 'Silenciar avisos', category: 'productivity', icon: faBellSlash, keywords: ['silencio', 'no molestar', 'notificaciones', 'concentración'] },
  { name: 'sliders', label: 'Ajustes', category: 'productivity', icon: faSliders, keywords: ['ajustes', 'controles', 'configurar', 'preferencias'] },
  { name: 'arrow-up-right-dots', label: 'Progresar', category: 'productivity', icon: faArrowUpRightDots, keywords: ['progreso', 'subir', 'mejorar', 'escalar'] },
  { name: 'group-arrows-rotate', label: 'Rutina', category: 'productivity', icon: faGroupArrowsRotate, keywords: ['rutina', 'ciclo', 'repetir', 'hábito'] },
  { name: 'rotate-right', label: 'Repetir', category: 'productivity', icon: faRotateRight, keywords: ['repetir', 'volver', 'reintentar', 'ciclo'] },
  { name: 'crosshairs', label: 'Enfocar', category: 'productivity', icon: faCrosshairs, keywords: ['enfoque', 'foco', 'objetivo', 'concentración'] },
  { name: 'signature', label: 'Firmar', category: 'productivity', icon: faSignature, keywords: ['firma', 'firmar', 'compromiso', 'documento'] },
  { name: 'stamp', label: 'Sello', category: 'productivity', icon: faStamp, keywords: ['sello', 'aprobar', 'validar', 'marcar'] },
  { name: 'square-poll-horizontal', label: 'Avance', category: 'productivity', icon: faSquarePollHorizontal, keywords: ['avance', 'barras', 'progreso', 'encuesta'] },
  { name: 'chart-area', label: 'Tendencia', category: 'productivity', icon: faChartArea, keywords: ['gráfica', 'área', 'tendencia', 'datos'] },
  { name: 'gauge', label: 'Medidor', category: 'productivity', icon: faGauge, keywords: ['medidor', 'nivel', 'rendimiento', 'progreso'] },
  { name: 'diagram-next', label: 'Siguiente paso', category: 'productivity', icon: faDiagramNext, keywords: ['paso', 'flujo', 'siguiente', 'proceso'] },
] as const satisfies readonly AppIconEntry[]
