import {
  faAddressBook,
  faAddressCard,
  faBaby,
  faBeerMugEmpty,
  faCakeCandles,
  faCalendarDay,
  faChampagneGlasses,
  faChildren,
  faCircleUser,
  faComment,
  faCommentDots,
  faCommentSms,
  faEnvelopeOpenText,
  faFaceGrinHearts,
  faGift,
  faHandHoldingHand,
  faHandPeace,
  faHandshakeAngle,
  faHandsClapping,
  faHandsHoldingChild,
  faHouseUser,
  faLocationDot,
  faMessage,
  faMugSaucer,
  faPaperPlane,
  faPeopleGroup,
  faPeopleRoof,
  faPhoneVolume,
  faRing,
  faShareNodes,
  faThumbsUp,
  faUserPlus,
  faUsersRectangle,
  faWineGlass,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const socialIcons = [
  { name: 'people-roof', label: 'Familia', category: 'social', icon: faPeopleRoof, keywords: ['familia', 'padres', 'hermanos', 'casa', 'family', 'parientes'] },
  { name: 'hands-holding-child', label: 'Cuidar', category: 'social', icon: faHandsHoldingChild, keywords: ['cuidar', 'hijos', 'familia', 'crianza', 'apoyo'] },
  { name: 'children', label: 'Hijos', category: 'social', icon: faChildren, keywords: ['hijos', 'niños', 'familia', 'crianza', 'kids'] },
  { name: 'baby', label: 'Bebé', category: 'social', icon: faBaby, keywords: ['bebé', 'recién nacido', 'familia', 'crianza', 'baby'] },
  { name: 'hand-holding-hand', label: 'Pareja', category: 'social', icon: faHandHoldingHand, keywords: ['pareja', 'novia', 'novio', 'juntos', 'apoyo', 'de la mano'] },
  { name: 'ring', label: 'Aniversario', category: 'social', icon: faRing, keywords: ['anillo', 'boda', 'aniversario', 'pareja', 'compromiso'] },
  { name: 'people-group', label: 'Comunidad', category: 'social', icon: faPeopleGroup, keywords: ['comunidad', 'grupo', 'amigos', 'gente', 'vecinos', 'club'] },
  { name: 'handshake-angle', label: 'Voluntariado', category: 'social', icon: faHandshakeAngle, keywords: ['voluntariado', 'ayudar', 'solidaridad', 'echar una mano', 'ong'] },
  { name: 'user-plus', label: 'Nuevo contacto', category: 'social', icon: faUserPlus, keywords: ['contacto', 'añadir', 'conocer', 'amistad', 'seguir'] },
  { name: 'circle-user', label: 'Perfil', category: 'social', icon: faCircleUser, keywords: ['perfil', 'persona', 'avatar', 'cuenta', 'contacto'] },
  { name: 'address-book', label: 'Agenda', category: 'social', icon: faAddressBook, keywords: ['agenda', 'contactos', 'directorio', 'teléfonos'] },
  { name: 'address-card', label: 'Ficha de contacto', category: 'social', icon: faAddressCard, keywords: ['contacto', 'tarjeta', 'ficha', 'datos', 'vcard'] },
  { name: 'message', label: 'Mensaje', category: 'social', icon: faMessage, keywords: ['mensaje', 'escribir', 'chat', 'whatsapp', 'texto'] },
  { name: 'comment-dots', label: 'Chat', category: 'social', icon: faCommentDots, keywords: ['chat', 'conversación', 'hablar', 'mensajes', 'charlar'] },
  { name: 'comment', label: 'Comentario', category: 'social', icon: faComment, keywords: ['comentario', 'opinar', 'responder', 'burbuja'] },
  { name: 'comment-sms', label: 'SMS', category: 'social', icon: faCommentSms, keywords: ['sms', 'mensaje', 'texto', 'móvil'] },
  { name: 'phone-volume', label: 'Llamar', category: 'social', icon: faPhoneVolume, keywords: ['llamada', 'llamar', 'teléfono', 'call', 'hablar'] },
  { name: 'users-rectangle', label: 'Videollamada', category: 'social', icon: faUsersRectangle, keywords: ['videollamada', 'videoconferencia', 'zoom', 'meet', 'facetime', 'pantalla'] },
  { name: 'envelope-open-text', label: 'Carta', category: 'social', icon: faEnvelopeOpenText, keywords: ['carta', 'correo', 'leer', 'newsletter', 'mensaje'] },
  { name: 'paper-plane', label: 'Enviar', category: 'social', icon: faPaperPlane, keywords: ['enviar', 'mandar', 'mensaje', 'send', 'avión de papel'] },
  { name: 'share-nodes', label: 'Compartir', category: 'social', icon: faShareNodes, keywords: ['compartir', 'share', 'redes', 'difundir', 'enviar'] },
  { name: 'mug-saucer', label: 'Café con alguien', category: 'social', icon: faMugSaucer, keywords: ['café', 'cafe', 'quedada', 'charla', 'coffee', 'desayuno'] },
  { name: 'wine-glass', label: 'Copa', category: 'social', icon: faWineGlass, keywords: ['copa', 'vino', 'salir', 'quedada', 'brindis'] },
  { name: 'beer-mug-empty', label: 'Cañas', category: 'social', icon: faBeerMugEmpty, keywords: ['cerveza', 'caña', 'bar', 'quedada', 'amigos', 'beer'] },
  { name: 'champagne-glasses', label: 'Celebrar', category: 'social', icon: faChampagneGlasses, keywords: ['celebrar', 'brindis', 'fiesta', 'champán', 'celebración'] },
  { name: 'cake-candles', label: 'Cumpleaños', category: 'social', icon: faCakeCandles, keywords: ['cumpleaños', 'tarta', 'felicitar', 'aniversario', 'birthday'] },
  { name: 'gift', label: 'Regalo', category: 'social', icon: faGift, keywords: ['regalo', 'detalle', 'sorpresa', 'gift', 'obsequio'] },
  { name: 'calendar-day', label: 'Quedada', category: 'social', icon: faCalendarDay, keywords: ['quedada', 'plan', 'cita', 'agenda', 'evento'] },
  { name: 'location-dot', label: 'Punto de encuentro', category: 'social', icon: faLocationDot, keywords: ['sitio', 'lugar', 'ubicación', 'quedar', 'mapa'] },
  { name: 'house-user', label: 'Visita', category: 'social', icon: faHouseUser, keywords: ['visita', 'casa', 'invitar', 'anfitrión', 'recibir'] },
  { name: 'thumbs-up', label: 'Apoyo', category: 'social', icon: faThumbsUp, keywords: ['apoyo', 'me gusta', 'like', 'ánimo', 'aprobar'] },
  { name: 'hands-clapping', label: 'Aplauso', category: 'social', icon: faHandsClapping, keywords: ['aplauso', 'felicitar', 'enhorabuena', 'celebrar', 'aplaudir'] },
  { name: 'hand-peace', label: 'Saludo', category: 'social', icon: faHandPeace, keywords: ['saludo', 'hola', 'saludar', 'paz', 'gesto'] },
  { name: 'face-grin-hearts', label: 'Cariño', category: 'social', icon: faFaceGrinHearts, keywords: ['cariño', 'amor', 'querer', 'corazones', 'afecto'] },
] as const satisfies readonly AppIconEntry[]
