import {
  faAddressBook,
  faAddressCard,
  faAt,
  faBaby,
  faBeerMugEmpty,
  faCakeCandles,
  faCalendarDay,
  faChampagneGlasses,
  faChildren,
  faCircleUser,
  faComment,
  faCommentDots,
  faCommentSms,
  faEnvelopeOpenText,
  faFaceAngry,
  faFaceFrown,
  faFaceGrin,
  faFaceGrinHearts,
  faFaceGrinWide,
  faFaceKiss,
  faFaceLaugh,
  faFaceLaughWink,
  faFaceMehBlank,
  faFaceRollingEyes,
  faFaceSadCry,
  faFaceSurprise,
  faGift,
  faHandHoldingHand,
  faHandPeace,
  faHandPointUp,
  faHands,
  faHandsAslInterpreting,
  faHandsClapping,
  faHandshakeAngle,
  faHandsHoldingChild,
  faHandSpock,
  faHashtag,
  faHouseUser,
  faLocationDot,
  faMessage,
  faMugSaucer,
  faPaperPlane,
  faPeopleArrows,
  faPeopleGroup,
  faPeopleRoof,
  faPersonCircleCheck,
  faPersonCircleQuestion,
  faPhoneVolume,
  faReply,
  faReplyAll,
  faRing,
  faShare,
  faShareFromSquare,
  faShareNodes,
  faThumbsUp,
  faUserCheck,
  faUserMinus,
  faUserPen,
  faUserPlus,
  faUsersBetweenLines,
  faUsersLine,
  faUsersRays,
  faUsersRectangle,
  faUsersViewfinder,
  faUserTag,
  faUserXmark,
  faWineGlass,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const socialIcons = [
  { name: 'people-roof', label: 'Familia', category: 'social', icon: faPeopleRoof, keywords: ['familia', 'padres', 'hermanos', 'casa', 'family', 'parientes'] },
  { name: 'hands-holding-child', label: 'Cuidar', category: 'social', icon: faHandsHoldingChild, keywords: ['cuidar', 'hijos', 'familia', 'crianza', 'apoyo'] },
  { name: 'children', label: 'Hijos', category: 'social', icon: faChildren, keywords: ['hijos', 'niños', 'familia', 'crianza', 'kids'] },
  { name: 'baby', label: 'Bebé', category: 'social', icon: faBaby, keywords: ['bebé', 'recién nacido', 'familia', 'crianza', 'baby'] },
  { name: 'hand-holding-hand', label: 'Pareja', category: 'social', icon: faHandHoldingHand, keywords: ['pareja', 'novia', 'novio', 'juntos', 'apoyo', 'de la mano'] },
  { name: 'ring', label: 'Aniversario', category: 'social', icon: faRing, keywords: ['anillo', 'boda', 'aniversario', 'pareja', 'compromiso'] },
  { name: 'people-group', label: 'Comunidad', category: 'social', icon: faPeopleGroup, keywords: ['comunidad', 'grupo', 'amigos', 'gente', 'vecinos', 'club'] },
  { name: 'handshake-angle', label: 'Voluntariado', category: 'social', icon: faHandshakeAngle, keywords: ['voluntariado', 'ayudar', 'solidaridad', 'echar una mano', 'ong'] },
  { name: 'user-plus', label: 'Nuevo contacto', category: 'social', icon: faUserPlus, keywords: ['contacto', 'añadir', 'conocer', 'amistad', 'seguir'] },
  { name: 'circle-user', label: 'Perfil', category: 'social', icon: faCircleUser, keywords: ['perfil', 'persona', 'avatar', 'cuenta', 'contacto'] },
  { name: 'address-book', label: 'Agenda', category: 'social', icon: faAddressBook, keywords: ['agenda', 'contactos', 'directorio', 'teléfonos'] },
  { name: 'address-card', label: 'Ficha de contacto', category: 'social', icon: faAddressCard, keywords: ['contacto', 'tarjeta', 'ficha', 'datos', 'vcard'] },
  { name: 'message', label: 'Mensaje', category: 'social', icon: faMessage, keywords: ['mensaje', 'escribir', 'chat', 'whatsapp', 'texto'] },
  { name: 'comment-dots', label: 'Chat', category: 'social', icon: faCommentDots, keywords: ['chat', 'conversación', 'hablar', 'mensajes', 'charlar'] },
  { name: 'comment', label: 'Comentario', category: 'social', icon: faComment, keywords: ['comentario', 'opinar', 'responder', 'burbuja'] },
  { name: 'comment-sms', label: 'SMS', category: 'social', icon: faCommentSms, keywords: ['sms', 'mensaje', 'texto', 'móvil'] },
  { name: 'phone-volume', label: 'Llamar', category: 'social', icon: faPhoneVolume, keywords: ['llamada', 'llamar', 'teléfono', 'call', 'hablar'] },
  { name: 'users-rectangle', label: 'Videollamada', category: 'social', icon: faUsersRectangle, keywords: ['videollamada', 'videoconferencia', 'zoom', 'meet', 'facetime', 'pantalla'] },
  { name: 'envelope-open-text', label: 'Carta', category: 'social', icon: faEnvelopeOpenText, keywords: ['carta', 'correo', 'leer', 'newsletter', 'mensaje'] },
  { name: 'paper-plane', label: 'Enviar', category: 'social', icon: faPaperPlane, keywords: ['enviar', 'mandar', 'mensaje', 'send', 'avión de papel'] },
  { name: 'share-nodes', label: 'Compartir', category: 'social', icon: faShareNodes, keywords: ['compartir', 'share', 'redes', 'difundir', 'enviar'] },
  { name: 'mug-saucer', label: 'Café con alguien', category: 'social', icon: faMugSaucer, keywords: ['café', 'cafe', 'quedada', 'charla', 'coffee', 'desayuno'] },
  { name: 'wine-glass', label: 'Copa', category: 'social', icon: faWineGlass, keywords: ['copa', 'vino', 'salir', 'quedada', 'brindis'] },
  { name: 'beer-mug-empty', label: 'Cañas', category: 'social', icon: faBeerMugEmpty, keywords: ['cerveza', 'caña', 'bar', 'quedada', 'amigos', 'beer'] },
  { name: 'champagne-glasses', label: 'Celebrar', category: 'social', icon: faChampagneGlasses, keywords: ['celebrar', 'brindis', 'fiesta', 'champán', 'celebración'] },
  { name: 'cake-candles', label: 'Cumpleaños', category: 'social', icon: faCakeCandles, keywords: ['cumpleaños', 'tarta', 'felicitar', 'aniversario', 'birthday'] },
  { name: 'gift', label: 'Regalo', category: 'social', icon: faGift, keywords: ['regalo', 'detalle', 'sorpresa', 'gift', 'obsequio'] },
  { name: 'calendar-day', label: 'Quedada', category: 'social', icon: faCalendarDay, keywords: ['quedada', 'plan', 'cita', 'agenda', 'evento'] },
  { name: 'location-dot', label: 'Punto de encuentro', category: 'social', icon: faLocationDot, keywords: ['sitio', 'lugar', 'ubicación', 'quedar', 'mapa'] },
  { name: 'house-user', label: 'Visita', category: 'social', icon: faHouseUser, keywords: ['visita', 'casa', 'invitar', 'anfitrión', 'recibir'] },
  { name: 'thumbs-up', label: 'Apoyo', category: 'social', icon: faThumbsUp, keywords: ['apoyo', 'me gusta', 'like', 'ánimo', 'aprobar'] },
  { name: 'hands-clapping', label: 'Aplauso', category: 'social', icon: faHandsClapping, keywords: ['aplauso', 'felicitar', 'enhorabuena', 'celebrar', 'aplaudir'] },
  { name: 'hand-peace', label: 'Saludo', category: 'social', icon: faHandPeace, keywords: ['saludo', 'hola', 'saludar', 'paz', 'gesto'] },
  { name: 'face-grin-hearts', label: 'Cariño', category: 'social', icon: faFaceGrinHearts, keywords: ['cariño', 'amor', 'querer', 'corazones', 'afecto'] },
  { name: 'user-check', label: 'Contacto confirmado', category: 'social', icon: faUserCheck, keywords: ['usuario', 'confirmar', 'contacto', 'amigo'] },
  { name: 'user-minus', label: 'Quitar contacto', category: 'social', icon: faUserMinus, keywords: ['usuario', 'quitar', 'contacto'] },
  { name: 'user-xmark', label: 'Cortar contacto', category: 'social', icon: faUserXmark, keywords: ['usuario', 'eliminar', 'contacto', 'bloquear'] },
  { name: 'user-tag', label: 'Etiquetar persona', category: 'social', icon: faUserTag, keywords: ['etiquetar', 'persona', 'mención', 'contacto'] },
  { name: 'user-pen', label: 'Editar perfil', category: 'social', icon: faUserPen, keywords: ['perfil', 'editar', 'usuario', 'datos'] },
  { name: 'users-viewfinder', label: 'Encuentro', category: 'social', icon: faUsersViewfinder, keywords: ['grupo', 'encuentro', 'personas', 'quedada'] },
  { name: 'users-line', label: 'Fila de personas', category: 'social', icon: faUsersLine, keywords: ['personas', 'fila', 'cola', 'grupo'] },
  { name: 'users-between-lines', label: 'Comunidad', category: 'social', icon: faUsersBetweenLines, keywords: ['comunidad', 'personas', 'grupo', 'vecinos'] },
  { name: 'users-rays', label: 'Reunión', category: 'social', icon: faUsersRays, keywords: ['reunión', 'personas', 'grupo', 'encuentro'] },
  { name: 'people-arrows', label: 'Distancia', category: 'social', icon: faPeopleArrows, keywords: ['distancia', 'personas', 'separar', 'espacio'] },
  { name: 'person-circle-check', label: 'Persona confirmada', category: 'social', icon: faPersonCircleCheck, keywords: ['confirmar', 'persona', 'asistencia'] },
  { name: 'person-circle-question', label: 'Persona por confirmar', category: 'social', icon: faPersonCircleQuestion, keywords: ['duda', 'persona', 'pendiente', 'pregunta'] },
  { name: 'hands', label: 'Lengua de signos', category: 'social', icon: faHands, keywords: ['signos', 'manos', 'comunicación', 'accesibilidad'] },
  { name: 'hands-asl-interpreting', label: 'Intérprete de signos', category: 'social', icon: faHandsAslInterpreting, keywords: ['signos', 'intérprete', 'comunicación', 'accesibilidad'] },
  { name: 'hand-point-up', label: 'Señalar', category: 'social', icon: faHandPointUp, keywords: ['señalar', 'mano', 'atención', 'indicar'] },
  { name: 'hand-spock', label: 'Saludo', category: 'social', icon: faHandSpock, keywords: ['saludo', 'mano', 'amistad', 'gesto'] },
  { name: 'face-grin', label: 'Sonrisa amplia', category: 'social', icon: faFaceGrin, keywords: ['cara', 'sonrisa', 'alegría', 'ánimo'] },
  { name: 'face-grin-wide', label: 'Risa', category: 'social', icon: faFaceGrinWide, keywords: ['cara', 'risa', 'alegría', 'feliz'] },
  { name: 'face-laugh', label: 'Carcajada', category: 'social', icon: faFaceLaugh, keywords: ['risa', 'carcajada', 'humor', 'alegría'] },
  { name: 'face-laugh-wink', label: 'Risa con guiño', category: 'social', icon: faFaceLaughWink, keywords: ['risa', 'guiño', 'humor', 'complicidad'] },
  { name: 'face-angry', label: 'Enfado', category: 'social', icon: faFaceAngry, keywords: ['enfado', 'ira', 'emoción', 'ánimo'] },
  { name: 'face-frown', label: 'Tristeza', category: 'social', icon: faFaceFrown, keywords: ['triste', 'ánimo', 'emoción', 'pena'] },
  { name: 'face-sad-cry', label: 'Llanto', category: 'social', icon: faFaceSadCry, keywords: ['llorar', 'triste', 'emoción', 'desahogo'] },
  { name: 'face-surprise', label: 'Sorpresa', category: 'social', icon: faFaceSurprise, keywords: ['sorpresa', 'asombro', 'emoción'] },
  { name: 'face-meh-blank', label: 'Indiferencia', category: 'social', icon: faFaceMehBlank, keywords: ['indiferente', 'neutro', 'ánimo', 'emoción'] },
  { name: 'face-rolling-eyes', label: 'Hartazgo', category: 'social', icon: faFaceRollingEyes, keywords: ['harto', 'ojos', 'emoción', 'enfado'] },
  { name: 'face-kiss', label: 'Beso', category: 'social', icon: faFaceKiss, keywords: ['beso', 'cariño', 'pareja', 'afecto'] },
  { name: 'at', label: 'Arroba', category: 'social', icon: faAt, keywords: ['arroba', 'correo', 'usuario', 'mención'] },
  { name: 'hashtag', label: 'Etiqueta', category: 'social', icon: faHashtag, keywords: ['hashtag', 'etiqueta', 'tema', 'redes'] },
  { name: 'share', label: 'Compartir', category: 'social', icon: faShare, keywords: ['compartir', 'enviar', 'difundir'] },
  { name: 'share-from-square', label: 'Compartir fuera', category: 'social', icon: faShareFromSquare, keywords: ['compartir', 'enviar', 'externo', 'enlace'] },
  { name: 'reply', label: 'Responder', category: 'social', icon: faReply, keywords: ['responder', 'contestar', 'mensaje', 'correo'] },
  { name: 'reply-all', label: 'Responder a todos', category: 'social', icon: faReplyAll, keywords: ['responder', 'todos', 'correo', 'mensaje'] },
] as const satisfies readonly AppIconEntry[]
