import {
  faAlignCenter,
  faAlignJustify,
  faAlignLeft,
  faAlignRight,
  faAsterisk,
  faAtom,
  faAward,
  faBezierCurve,
  faBold,
  faBook,
  faBookAtlas,
  faBookMedical,
  faBookOpen,
  faBookOpenReader,
  faBraille,
  faCalculator,
  faCertificate,
  faChalkboard,
  faChalkboardUser,
  faChess,
  faChessKnight,
  faClipboardQuestion,
  faCompassDrafting,
  faDivide,
  faDna,
  faDrawPolygon,
  faEarthAfrica,
  faEarthAmericas,
  faEarthEurope,
  faEquals,
  faEraser,
  faFlask,
  faFont,
  faGlobe,
  faGraduationCap,
  faGreaterThan,
  faHeading,
  faHexagon,
  faHighlighter,
  faItalic,
  faLandmark,
  faLanguage,
  faLaptopFile,
  faLessThan,
  faLightbulb,
  faMagnifyingGlassChart,
  faMap,
  faMarker,
  faMicroscope,
  faNewspaper,
  faNotEqual,
  faOctagon,
  faParagraph,
  faPenFancy,
  faPenNib,
  faPentagon,
  faPlusMinus,
  faPodcast,
  faPuzzlePiece,
  faQuoteRight,
  faRuler,
  faSchool,
  faSchoolFlag,
  faScroll,
  faShapes,
  faSpellCheck,
  faSquareRootVariable,
  faStrikethrough,
  faSubscript,
  faSuperscript,
  faUnderline,
  faUserGraduate,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const studyIcons = [
  { name: 'book', label: 'Libro', category: 'study', icon: faBook, keywords: ['curso', 'leer', 'lectura', 'reading', 'libro'] },
  { name: 'book-open', label: 'Lectura', category: 'study', icon: faBookOpen, keywords: ['leer', 'estudio', 'reading', 'aprendizaje', 'libro'] },
  { name: 'graduation-cap', label: 'Formación', category: 'study', icon: faGraduationCap, keywords: ['curso', 'estudio', 'universidad', 'degree', 'carrera'] },
  { name: 'school', label: 'Escuela', category: 'study', icon: faSchool, keywords: ['clase', 'academia', 'education', 'colegio', 'cole'] },
  { name: 'chalkboard', label: 'Pizarra', category: 'study', icon: faChalkboard, keywords: ['clase', 'profesor', 'lesson', 'pizarra'] },
  { name: 'flask', label: 'Ciencia', category: 'study', icon: faFlask, keywords: ['laboratorio', 'química', 'experimento', 'matraz'] },
  { name: 'microscope', label: 'Microscopio', category: 'study', icon: faMicroscope, keywords: ['biología', 'investigación', 'lab', 'ciencia'] },
  { name: 'calculator', label: 'Calculadora', category: 'study', icon: faCalculator, keywords: ['matemáticas', 'números', 'math', 'calcular'] },
  { name: 'language', label: 'Idiomas', category: 'study', icon: faLanguage, keywords: ['inglés', 'traducción', 'learn language', 'idioma', 'francés', 'vocabulario'] },
  { name: 'globe', label: 'Mundo', category: 'study', icon: faGlobe, keywords: ['geografía', 'cultura', 'internacional', 'mundo', 'global'] },
  { name: 'lightbulb', label: 'Idea', category: 'study', icon: faLightbulb, keywords: ['aprendizaje', 'insight', 'creatividad', 'bombilla', 'idea'] },
  { name: 'atom', label: 'Física', category: 'study', icon: faAtom, keywords: ['ciencia', 'partículas', 'stem', 'átomo', 'física'] },
  { name: 'puzzle-piece', label: 'Puzzle', category: 'study', icon: faPuzzlePiece, keywords: ['lógica', 'problema', 'brain teaser', 'pieza', 'encajar'] },
  { name: 'book-open-reader', label: 'Estudiar', category: 'study', icon: faBookOpenReader, keywords: ['estudiar', 'repasar', 'leer', 'apuntes', 'study'] },
  { name: 'book-atlas', label: 'Atlas', category: 'study', icon: faBookAtlas, keywords: ['atlas', 'geografía', 'mapa', 'enciclopedia', 'consulta'] },
  { name: 'user-graduate', label: 'Graduación', category: 'study', icon: faUserGraduate, keywords: ['graduado', 'titulación', 'estudiante', 'carrera', 'máster'] },
  { name: 'chalkboard-user', label: 'Profesor', category: 'study', icon: faChalkboardUser, keywords: ['profesor', 'clase', 'enseñar', 'tutoría', 'docente'] },
  { name: 'laptop-file', label: 'Curso online', category: 'study', icon: faLaptopFile, keywords: ['curso', 'online', 'elearning', 'formación', 'clase virtual'] },
  { name: 'clipboard-question', label: 'Examen', category: 'study', icon: faClipboardQuestion, keywords: ['examen', 'test', 'prueba', 'preguntas', 'evaluación'] },
  { name: 'certificate', label: 'Certificado', category: 'study', icon: faCertificate, keywords: ['certificado', 'diploma', 'título', 'acreditación'] },
  { name: 'award', label: 'Reconocimiento', category: 'study', icon: faAward, keywords: ['premio', 'reconocimiento', 'mención', 'distinción'] },
  { name: 'pen-fancy', label: 'Escritura', category: 'study', icon: faPenFancy, keywords: ['escribir', 'redactar', 'pluma', 'writing', 'texto'] },
  { name: 'pen-nib', label: 'Caligrafía', category: 'study', icon: faPenNib, keywords: ['caligrafía', 'plumilla', 'letra', 'dibujar', 'trazo'] },
  { name: 'highlighter', label: 'Subrayar', category: 'study', icon: faHighlighter, keywords: ['subrayar', 'marcador', 'resaltar', 'apuntes'] },
  { name: 'eraser', label: 'Borrador', category: 'study', icon: faEraser, keywords: ['borrar', 'goma', 'corregir', 'error'] },
  { name: 'ruler', label: 'Regla', category: 'study', icon: faRuler, keywords: ['regla', 'medir', 'geometría', 'dibujo'] },
  { name: 'compass-drafting', label: 'Dibujo técnico', category: 'study', icon: faCompassDrafting, keywords: ['compás', 'geometría', 'dibujo', 'técnico', 'planos'] },
  { name: 'square-root-variable', label: 'Matemáticas', category: 'study', icon: faSquareRootVariable, keywords: ['matemáticas', 'álgebra', 'raíz', 'fórmula', 'mates'] },
  { name: 'spell-check', label: 'Ortografía', category: 'study', icon: faSpellCheck, keywords: ['ortografía', 'gramática', 'corregir', 'escribir', 'idioma'] },
  { name: 'earth-europe', label: 'Geografía', category: 'study', icon: faEarthEurope, keywords: ['geografía', 'europa', 'mundo', 'países', 'mapa'] },
  { name: 'dna', label: 'Biología', category: 'study', icon: faDna, keywords: ['biología', 'adn', 'genética', 'ciencia', 'células'] },
  { name: 'magnifying-glass-chart', label: 'Investigación', category: 'study', icon: faMagnifyingGlassChart, keywords: ['investigar', 'análisis', 'datos', 'research', 'estudio'] },
  { name: 'chess', label: 'Ajedrez', category: 'study', icon: faChess, keywords: ['ajedrez', 'chess', 'estrategia', 'partida', 'tablero'] },
  { name: 'chess-knight', label: 'Estrategia', category: 'study', icon: faChessKnight, keywords: ['caballo', 'ajedrez', 'estrategia', 'táctica', 'jugada'] },
  { name: 'podcast', label: 'Podcast', category: 'study', icon: faPodcast, keywords: ['podcast', 'audio', 'escuchar', 'episodio', 'aprender'] },
  { name: 'newspaper', label: 'Prensa', category: 'study', icon: faNewspaper, keywords: ['periódico', 'noticias', 'prensa', 'leer', 'actualidad'] },
  { name: 'scroll', label: 'Historia', category: 'study', icon: faScroll, keywords: ['historia', 'pergamino', 'antiguo', 'documento', 'texto'] },
  { name: 'landmark', label: 'Museo', category: 'study', icon: faLandmark, keywords: ['museo', 'monumento', 'cultura', 'patrimonio', 'visita'] },
  { name: 'font', label: 'Tipografía', category: 'study', icon: faFont, keywords: ['letra', 'tipografía', 'fuente', 'texto'] },
  { name: 'bold', label: 'Negrita', category: 'study', icon: faBold, keywords: ['negrita', 'texto', 'formato', 'resaltar'] },
  { name: 'italic', label: 'Cursiva', category: 'study', icon: faItalic, keywords: ['cursiva', 'texto', 'formato'] },
  { name: 'underline', label: 'Subrayar', category: 'study', icon: faUnderline, keywords: ['subrayar', 'texto', 'formato', 'resaltar'] },
  { name: 'strikethrough', label: 'Tachar', category: 'study', icon: faStrikethrough, keywords: ['tachar', 'texto', 'formato', 'corregir'] },
  { name: 'heading', label: 'Título', category: 'study', icon: faHeading, keywords: ['título', 'encabezado', 'texto', 'estructura'] },
  { name: 'paragraph', label: 'Párrafo', category: 'study', icon: faParagraph, keywords: ['párrafo', 'texto', 'redacción', 'escribir'] },
  { name: 'quote-right', label: 'Cita', category: 'study', icon: faQuoteRight, keywords: ['cita', 'comillas', 'referencia', 'texto'] },
  { name: 'align-left', label: 'Alinear a la izquierda', category: 'study', icon: faAlignLeft, keywords: ['alinear', 'texto', 'formato'] },
  { name: 'align-center', label: 'Centrar', category: 'study', icon: faAlignCenter, keywords: ['centrar', 'texto', 'formato'] },
  { name: 'align-right', label: 'Alinear a la derecha', category: 'study', icon: faAlignRight, keywords: ['alinear', 'texto', 'formato'] },
  { name: 'align-justify', label: 'Justificar', category: 'study', icon: faAlignJustify, keywords: ['justificar', 'texto', 'formato'] },
  { name: 'marker', label: 'Rotulador', category: 'study', icon: faMarker, keywords: ['rotulador', 'marcar', 'subrayar', 'apuntes'] },
  { name: 'braille', label: 'Braille', category: 'study', icon: faBraille, keywords: ['braille', 'lectura', 'accesibilidad', 'tacto'] },
  { name: 'book-medical', label: 'Manual de medicina', category: 'study', icon: faBookMedical, keywords: ['libro', 'medicina', 'estudio', 'apuntes'] },
  { name: 'school-flag', label: 'Colegio', category: 'study', icon: faSchoolFlag, keywords: ['colegio', 'escuela', 'clase', 'estudiar'] },
  { name: 'divide', label: 'Dividir', category: 'study', icon: faDivide, keywords: ['dividir', 'matemáticas', 'cálculo', 'operación'] },
  { name: 'equals', label: 'Igual', category: 'study', icon: faEquals, keywords: ['igual', 'matemáticas', 'resultado', 'ecuación'] },
  { name: 'not-equal', label: 'Distinto', category: 'study', icon: faNotEqual, keywords: ['distinto', 'matemáticas', 'comparar'] },
  { name: 'greater-than', label: 'Mayor que', category: 'study', icon: faGreaterThan, keywords: ['mayor', 'matemáticas', 'comparar'] },
  { name: 'less-than', label: 'Menor que', category: 'study', icon: faLessThan, keywords: ['menor', 'matemáticas', 'comparar'] },
  { name: 'plus-minus', label: 'Más menos', category: 'study', icon: faPlusMinus, keywords: ['más', 'menos', 'matemáticas', 'margen'] },
  { name: 'asterisk', label: 'Asterisco', category: 'study', icon: faAsterisk, keywords: ['asterisco', 'nota', 'referencia', 'matemáticas'] },
  { name: 'superscript', label: 'Superíndice', category: 'study', icon: faSuperscript, keywords: ['exponente', 'potencia', 'texto', 'fórmula'] },
  { name: 'subscript', label: 'Subíndice', category: 'study', icon: faSubscript, keywords: ['subíndice', 'fórmula', 'química', 'texto'] },
  { name: 'draw-polygon', label: 'Polígono', category: 'study', icon: faDrawPolygon, keywords: ['geometría', 'polígono', 'dibujo', 'figura'] },
  { name: 'bezier-curve', label: 'Curva', category: 'study', icon: faBezierCurve, keywords: ['curva', 'diseño', 'vector', 'dibujo'] },
  { name: 'shapes', label: 'Figuras', category: 'study', icon: faShapes, keywords: ['figuras', 'formas', 'geometría', 'dibujo'] },
  { name: 'hexagon', label: 'Hexágono', category: 'study', icon: faHexagon, keywords: ['hexágono', 'figura', 'geometría'] },
  { name: 'pentagon', label: 'Pentágono', category: 'study', icon: faPentagon, keywords: ['pentágono', 'figura', 'geometría'] },
  { name: 'octagon', label: 'Octágono', category: 'study', icon: faOctagon, keywords: ['octágono', 'figura', 'geometría'] },
  { name: 'map', label: 'Mapa', category: 'study', icon: faMap, keywords: ['mapa', 'geografía', 'ruta', 'viaje'] },
  { name: 'earth-americas', label: 'América', category: 'study', icon: faEarthAmericas, keywords: ['mundo', 'globo', 'américa', 'geografía'] },
  { name: 'earth-africa', label: 'África', category: 'study', icon: faEarthAfrica, keywords: ['mundo', 'globo', 'áfrica', 'geografía'] },
] as const satisfies readonly AppIconEntry[]
