import {
  faAtom,
  faAward,
  faBook,
  faBookAtlas,
  faBookOpen,
  faBookOpenReader,
  faCalculator,
  faCertificate,
  faChalkboard,
  faChalkboardUser,
  faChess,
  faChessKnight,
  faClipboardQuestion,
  faCompassDrafting,
  faDna,
  faEarthEurope,
  faEraser,
  faFlask,
  faGlobe,
  faGraduationCap,
  faHighlighter,
  faLandmark,
  faLanguage,
  faLaptopFile,
  faLightbulb,
  faMagnifyingGlassChart,
  faMicroscope,
  faNewspaper,
  faPenFancy,
  faPenNib,
  faPodcast,
  faPuzzlePiece,
  faRuler,
  faSchool,
  faScroll,
  faSpellCheck,
  faSquareRootVariable,
  faUserGraduate,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const studyIcons = [
  { name: 'book', label: 'Libro', category: 'study', icon: faBook, keywords: ['curso', 'leer', 'lectura', 'reading', 'libro'] },
  { name: 'book-open', label: 'Lectura', category: 'study', icon: faBookOpen, keywords: ['leer', 'estudio', 'reading', 'aprendizaje', 'libro'] },
  { name: 'graduation-cap', label: 'Formación', category: 'study', icon: faGraduationCap, keywords: ['curso', 'estudio', 'universidad', 'degree', 'carrera'] },
  { name: 'school', label: 'Escuela', category: 'study', icon: faSchool, keywords: ['clase', 'academia', 'education', 'colegio', 'cole'] },
  { name: 'chalkboard', label: 'Pizarra', category: 'study', icon: faChalkboard, keywords: ['clase', 'profesor', 'lesson', 'pizarra'] },
  { name: 'flask', label: 'Ciencia', category: 'study', icon: faFlask, keywords: ['laboratorio', 'química', 'experimento', 'matraz'] },
  { name: 'microscope', label: 'Microscopio', category: 'study', icon: faMicroscope, keywords: ['biología', 'investigación', 'lab', 'ciencia'] },
  { name: 'calculator', label: 'Calculadora', category: 'study', icon: faCalculator, keywords: ['matemáticas', 'números', 'math', 'calcular'] },
  { name: 'language', label: 'Idiomas', category: 'study', icon: faLanguage, keywords: ['inglés', 'traducción', 'learn language', 'idioma', 'francés', 'vocabulario'] },
  { name: 'globe', label: 'Mundo', category: 'study', icon: faGlobe, keywords: ['geografía', 'cultura', 'internacional', 'mundo', 'global'] },
  { name: 'lightbulb', label: 'Idea', category: 'study', icon: faLightbulb, keywords: ['aprendizaje', 'insight', 'creatividad', 'bombilla', 'idea'] },
  { name: 'atom', label: 'Física', category: 'study', icon: faAtom, keywords: ['ciencia', 'partículas', 'stem', 'átomo', 'física'] },
  { name: 'puzzle-piece', label: 'Puzzle', category: 'study', icon: faPuzzlePiece, keywords: ['lógica', 'problema', 'brain teaser', 'pieza', 'encajar'] },
  { name: 'book-open-reader', label: 'Estudiar', category: 'study', icon: faBookOpenReader, keywords: ['estudiar', 'repasar', 'leer', 'apuntes', 'study'] },
  { name: 'book-atlas', label: 'Atlas', category: 'study', icon: faBookAtlas, keywords: ['atlas', 'geografía', 'mapa', 'enciclopedia', 'consulta'] },
  { name: 'user-graduate', label: 'Graduación', category: 'study', icon: faUserGraduate, keywords: ['graduado', 'titulación', 'estudiante', 'carrera', 'máster'] },
  { name: 'chalkboard-user', label: 'Profesor', category: 'study', icon: faChalkboardUser, keywords: ['profesor', 'clase', 'enseñar', 'tutoría', 'docente'] },
  { name: 'laptop-file', label: 'Curso online', category: 'study', icon: faLaptopFile, keywords: ['curso', 'online', 'elearning', 'formación', 'clase virtual'] },
  { name: 'clipboard-question', label: 'Examen', category: 'study', icon: faClipboardQuestion, keywords: ['examen', 'test', 'prueba', 'preguntas', 'evaluación'] },
  { name: 'certificate', label: 'Certificado', category: 'study', icon: faCertificate, keywords: ['certificado', 'diploma', 'título', 'acreditación'] },
  { name: 'award', label: 'Reconocimiento', category: 'study', icon: faAward, keywords: ['premio', 'reconocimiento', 'mención', 'distinción'] },
  { name: 'pen-fancy', label: 'Escritura', category: 'study', icon: faPenFancy, keywords: ['escribir', 'redactar', 'pluma', 'writing', 'texto'] },
  { name: 'pen-nib', label: 'Caligrafía', category: 'study', icon: faPenNib, keywords: ['caligrafía', 'plumilla', 'letra', 'dibujar', 'trazo'] },
  { name: 'highlighter', label: 'Subrayar', category: 'study', icon: faHighlighter, keywords: ['subrayar', 'marcador', 'resaltar', 'apuntes'] },
  { name: 'eraser', label: 'Borrador', category: 'study', icon: faEraser, keywords: ['borrar', 'goma', 'corregir', 'error'] },
  { name: 'ruler', label: 'Regla', category: 'study', icon: faRuler, keywords: ['regla', 'medir', 'geometría', 'dibujo'] },
  { name: 'compass-drafting', label: 'Dibujo técnico', category: 'study', icon: faCompassDrafting, keywords: ['compás', 'geometría', 'dibujo', 'técnico', 'planos'] },
  { name: 'square-root-variable', label: 'Matemáticas', category: 'study', icon: faSquareRootVariable, keywords: ['matemáticas', 'álgebra', 'raíz', 'fórmula', 'mates'] },
  { name: 'spell-check', label: 'Ortografía', category: 'study', icon: faSpellCheck, keywords: ['ortografía', 'gramática', 'corregir', 'escribir', 'idioma'] },
  { name: 'earth-europe', label: 'Geografía', category: 'study', icon: faEarthEurope, keywords: ['geografía', 'europa', 'mundo', 'países', 'mapa'] },
  { name: 'dna', label: 'Biología', category: 'study', icon: faDna, keywords: ['biología', 'adn', 'genética', 'ciencia', 'células'] },
  { name: 'magnifying-glass-chart', label: 'Investigación', category: 'study', icon: faMagnifyingGlassChart, keywords: ['investigar', 'análisis', 'datos', 'research', 'estudio'] },
  { name: 'chess', label: 'Ajedrez', category: 'study', icon: faChess, keywords: ['ajedrez', 'chess', 'estrategia', 'partida', 'tablero'] },
  { name: 'chess-knight', label: 'Estrategia', category: 'study', icon: faChessKnight, keywords: ['caballo', 'ajedrez', 'estrategia', 'táctica', 'jugada'] },
  { name: 'podcast', label: 'Podcast', category: 'study', icon: faPodcast, keywords: ['podcast', 'audio', 'escuchar', 'episodio', 'aprender'] },
  { name: 'newspaper', label: 'Prensa', category: 'study', icon: faNewspaper, keywords: ['periódico', 'noticias', 'prensa', 'leer', 'actualidad'] },
  { name: 'scroll', label: 'Historia', category: 'study', icon: faScroll, keywords: ['historia', 'pergamino', 'antiguo', 'documento', 'texto'] },
  { name: 'landmark', label: 'Museo', category: 'study', icon: faLandmark, keywords: ['museo', 'monumento', 'cultura', 'patrimonio', 'visita'] },
] as const satisfies readonly AppIconEntry[]
