import {
  faBatteryEmpty,
  faBatteryFull,
  faBatteryHalf,
  faBlog,
  faCameraRotate,
  faChargingStation,
  faCircleNodes,
  faCloud,
  faCloudArrowDown,
  faCloudArrowUp,
  faCodeCommit,
  faCodeCompare,
  faCodeFork,
  faCodeMerge,
  faComputer,
  faComputerMouse,
  faCropSimple,
  faDatabase,
  faDisplay,
  faDownload,
  faEthernet,
  faFileAudio,
  faFileCode,
  faFileImage,
  faFileVideo,
  faFileZipper,
  faFingerprint,
  faFloppyDisk,
  faGears,
  faHardDrive,
  faImage,
  faLaptopCode,
  faLink,
  faLockOpen,
  faMemory,
  faMicrochip,
  faMicrophoneSlash,
  faMobileButton,
  faMobileRetro,
  faMobileScreen,
  faNetworkWired,
  faObjectGroup,
  faPhoneFlip,
  faPlugCircleBolt,
  faQrcode,
  faRobot,
  faRss,
  faSatellite,
  faSatelliteDish,
  faSdCard,
  faServer,
  faShield,
  faShieldHalved,
  faSignal,
  faSimCard,
  faSquareBinary,
  faTabletButton,
  faTabletScreenButton,
  faToggleOff,
  faToggleOn,
  faTowerBroadcast,
  faTowerCell,
  faUpload,
  faUserLock,
  faUserSecret,
  faUserShield,
  faVideoSlash,
  faVrCardboard,
  faWalkieTalkie,
  faWandMagicSparkles,
  faWifi,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const technologyIcons = [
  { name: 'mobile', label: 'Móvil', category: 'technology', icon: faMobileScreen, keywords: ['mobile-screen', 'phone', 'smartphone', 'app', 'móvil', 'pantalla'] },
  { name: 'tablet', label: 'Tablet', category: 'technology', icon: faTabletScreenButton, keywords: ['tablet-screen-button', 'ipad', 'dispositivo', 'tableta'] },
  { name: 'wifi', label: 'WiFi', category: 'technology', icon: faWifi, keywords: ['internet', 'red', 'conexión', 'wifi', 'router'] },
  { name: 'database', label: 'Base de datos', category: 'technology', icon: faDatabase, keywords: ['sql', 'datos', 'storage', 'base de datos'] },
  { name: 'server', label: 'Servidor', category: 'technology', icon: faServer, keywords: ['backend', 'hosting', 'infra', 'servidor'] },
  { name: 'cloud', label: 'Nube', category: 'technology', icon: faCloud, keywords: ['cloud', 'sync', 'backup', 'calma', 'relajación', 'mindfulness', 'nube'] },
  { name: 'robot', label: 'Robot', category: 'technology', icon: faRobot, keywords: ['ia', 'ai', 'automation', 'bot', 'robot'] },
  { name: 'microchip', label: 'Chip', category: 'technology', icon: faMicrochip, keywords: ['hardware', 'cpu', 'electrónica', 'chip', 'procesador'] },
  { name: 'laptop-code', label: 'Desarrollo', category: 'technology', icon: faLaptopCode, keywords: ['coding', 'programación', 'dev', 'software', 'programar'] },
  { name: 'computer', label: 'Ordenador', category: 'technology', icon: faComputer, keywords: ['ordenador', 'pc', 'equipo', 'computer', 'sobremesa'] },
  { name: 'display', label: 'Pantalla', category: 'technology', icon: faDisplay, keywords: ['pantalla', 'monitor', 'screen', 'tiempo de pantalla'] },
  { name: 'computer-mouse', label: 'Ratón', category: 'technology', icon: faComputerMouse, keywords: ['ratón', 'mouse', 'periférico', 'clic'] },
  { name: 'hard-drive', label: 'Disco duro', category: 'technology', icon: faHardDrive, keywords: ['disco', 'almacenamiento', 'hdd', 'ssd', 'backup'] },
  { name: 'floppy-disk', label: 'Guardar', category: 'technology', icon: faFloppyDisk, keywords: ['guardar', 'save', 'disquete', 'copia'] },
  { name: 'cloud-arrow-up', label: 'Copia de seguridad', category: 'technology', icon: faCloudArrowUp, keywords: ['backup', 'subir', 'nube', 'sincronizar', 'copia'] },
  { name: 'network-wired', label: 'Red', category: 'technology', icon: faNetworkWired, keywords: ['red', 'network', 'cable', 'lan', 'conexión'] },
  { name: 'circle-nodes', label: 'Nodos', category: 'technology', icon: faCircleNodes, keywords: ['nodos', 'grafo', 'red', 'conexiones', 'sistema'] },
  { name: 'file-code', label: 'Código fuente', category: 'technology', icon: faFileCode, keywords: ['código', 'fichero', 'script', 'programar', 'source'] },
  { name: 'gears', label: 'Automatización', category: 'technology', icon: faGears, keywords: ['automatizar', 'engranajes', 'proceso', 'script', 'workflow'] },
  { name: 'wand-magic-sparkles', label: 'Inteligencia artificial', category: 'technology', icon: faWandMagicSparkles, keywords: ['ia', 'ai', 'magia', 'generar', 'prompt', 'automático'] },
  { name: 'qrcode', label: 'Código QR', category: 'technology', icon: faQrcode, keywords: ['qr', 'código', 'escanear', 'scan'] },
  { name: 'fingerprint', label: 'Huella digital', category: 'technology', icon: faFingerprint, keywords: ['huella', 'biometría', 'acceso', 'seguridad', 'desbloquear'] },
  { name: 'shield-halved', label: 'Seguridad', category: 'technology', icon: faShieldHalved, keywords: ['seguridad', 'escudo', 'protección', 'antivirus', 'security'] },
  { name: 'user-shield', label: 'Privacidad', category: 'technology', icon: faUserShield, keywords: ['privacidad', 'datos', 'protección', 'cuenta', 'contraseñas'] },
  { name: 'battery-full', label: 'Batería', category: 'technology', icon: faBatteryFull, keywords: ['batería', 'carga', 'energía', 'pila'] },
  { name: 'charging-station', label: 'Cargar', category: 'technology', icon: faChargingStation, keywords: ['cargar', 'carga', 'enchufar', 'batería', 'coche eléctrico'] },
  { name: 'satellite-dish', label: 'Antena', category: 'technology', icon: faSatelliteDish, keywords: ['antena', 'satélite', 'señal', 'parabólica'] },
  { name: 'tower-cell', label: 'Cobertura', category: 'technology', icon: faTowerCell, keywords: ['cobertura', 'antena', 'móvil', 'señal', '5g'] },
  { name: 'link', label: 'Enlace', category: 'technology', icon: faLink, keywords: ['enlace', 'link', 'url', 'web', 'compartir'] },
  { name: 'blog', label: 'Blog', category: 'technology', icon: faBlog, keywords: ['blog', 'artículo', 'publicar', 'escribir', 'web'] },
  { name: 'vr-cardboard', label: 'Realidad virtual', category: 'technology', icon: faVrCardboard, keywords: ['vr', 'realidad virtual', 'gafas', 'inmersivo', 'metaverso'] },
  { name: 'memory', label: 'Memoria RAM', category: 'technology', icon: faMemory, keywords: ['ram', 'memoria', 'ordenador', 'hardware'] },
  { name: 'sd-card', label: 'Tarjeta SD', category: 'technology', icon: faSdCard, keywords: ['sd', 'tarjeta', 'memoria', 'foto'] },
  { name: 'sim-card', label: 'Tarjeta SIM', category: 'technology', icon: faSimCard, keywords: ['sim', 'móvil', 'tarjeta', 'línea'] },
  { name: 'ethernet', label: 'Red por cable', category: 'technology', icon: faEthernet, keywords: ['ethernet', 'red', 'cable', 'conexión'] },
  { name: 'tower-broadcast', label: 'Emisión', category: 'technology', icon: faTowerBroadcast, keywords: ['emisión', 'señal', 'antena', 'streaming'] },
  { name: 'satellite', label: 'Satélite', category: 'technology', icon: faSatellite, keywords: ['satélite', 'señal', 'espacio', 'gps'] },
  { name: 'signal', label: 'Cobertura', category: 'technology', icon: faSignal, keywords: ['cobertura', 'señal', 'móvil', 'red'] },
  { name: 'code-commit', label: 'Commit', category: 'technology', icon: faCodeCommit, keywords: ['commit', 'git', 'código', 'versión'] },
  { name: 'code-merge', label: 'Fusionar', category: 'technology', icon: faCodeMerge, keywords: ['merge', 'git', 'código', 'rama'] },
  { name: 'code-fork', label: 'Bifurcar', category: 'technology', icon: faCodeFork, keywords: ['fork', 'git', 'rama', 'código'] },
  { name: 'code-compare', label: 'Comparar código', category: 'technology', icon: faCodeCompare, keywords: ['diff', 'comparar', 'código', 'revisión'] },
  { name: 'square-binary', label: 'Binario', category: 'technology', icon: faSquareBinary, keywords: ['binario', 'código', 'datos', 'programar'] },
  { name: 'download', label: 'Descargar', category: 'technology', icon: faDownload, keywords: ['descargar', 'archivo', 'bajar', 'internet'] },
  { name: 'upload', label: 'Subir', category: 'technology', icon: faUpload, keywords: ['subir', 'cargar', 'archivo', 'internet'] },
  { name: 'cloud-arrow-down', label: 'Descargar de la nube', category: 'technology', icon: faCloudArrowDown, keywords: ['nube', 'descargar', 'copia', 'backup'] },
  { name: 'file-zipper', label: 'Comprimir', category: 'technology', icon: faFileZipper, keywords: ['zip', 'comprimir', 'archivo', 'carpeta'] },
  { name: 'object-group', label: 'Agrupar', category: 'technology', icon: faObjectGroup, keywords: ['agrupar', 'diseño', 'objetos', 'selección'] },
  { name: 'crop-simple', label: 'Recortar', category: 'technology', icon: faCropSimple, keywords: ['recortar', 'imagen', 'edición', 'foto'] },
  { name: 'image', label: 'Imagen', category: 'technology', icon: faImage, keywords: ['imagen', 'foto', 'archivo', 'galería'] },
  { name: 'file-image', label: 'Archivo de imagen', category: 'technology', icon: faFileImage, keywords: ['imagen', 'archivo', 'foto', 'adjunto'] },
  { name: 'file-video', label: 'Archivo de vídeo', category: 'technology', icon: faFileVideo, keywords: ['vídeo', 'archivo', 'grabar', 'editar'] },
  { name: 'file-audio', label: 'Archivo de audio', category: 'technology', icon: faFileAudio, keywords: ['audio', 'archivo', 'sonido', 'podcast'] },
  { name: 'camera-rotate', label: 'Cambiar de cámara', category: 'technology', icon: faCameraRotate, keywords: ['cámara', 'girar', 'selfi', 'foto'] },
  { name: 'video-slash', label: 'Cámara apagada', category: 'technology', icon: faVideoSlash, keywords: ['vídeo', 'apagar', 'reunión', 'cámara'] },
  { name: 'microphone-slash', label: 'Micrófono apagado', category: 'technology', icon: faMicrophoneSlash, keywords: ['micrófono', 'silencio', 'mute', 'reunión'] },
  { name: 'tablet-button', label: 'Tableta', category: 'technology', icon: faTabletButton, keywords: ['tableta', 'pantalla', 'dispositivo', 'leer'] },
  { name: 'mobile-button', label: 'Móvil con botón', category: 'technology', icon: faMobileButton, keywords: ['móvil', 'teléfono', 'dispositivo'] },
  { name: 'mobile-retro', label: 'Móvil antiguo', category: 'technology', icon: faMobileRetro, keywords: ['móvil', 'antiguo', 'teléfono', 'desconexión'] },
  { name: 'phone-flip', label: 'Llamar', category: 'technology', icon: faPhoneFlip, keywords: ['llamada', 'teléfono', 'contacto'] },
  { name: 'walkie-talkie', label: 'Walkie', category: 'technology', icon: faWalkieTalkie, keywords: ['walkie', 'radio', 'comunicación'] },
  { name: 'toggle-on', label: 'Activado', category: 'technology', icon: faToggleOn, keywords: ['activar', 'interruptor', 'encendido', 'ajuste'] },
  { name: 'toggle-off', label: 'Desactivado', category: 'technology', icon: faToggleOff, keywords: ['desactivar', 'interruptor', 'apagado', 'ajuste'] },
  { name: 'battery-half', label: 'Batería a medias', category: 'technology', icon: faBatteryHalf, keywords: ['batería', 'carga', 'energía', 'móvil'] },
  { name: 'battery-empty', label: 'Batería vacía', category: 'technology', icon: faBatteryEmpty, keywords: ['batería', 'sin carga', 'energía', 'cargar'] },
  { name: 'plug-circle-bolt', label: 'Enchufar', category: 'technology', icon: faPlugCircleBolt, keywords: ['enchufe', 'cargar', 'energía', 'electricidad'] },
  { name: 'shield', label: 'Seguridad', category: 'technology', icon: faShield, keywords: ['seguridad', 'protección', 'escudo', 'privacidad'] },
  { name: 'lock-open', label: 'Desbloquear', category: 'technology', icon: faLockOpen, keywords: ['desbloquear', 'abrir', 'candado', 'acceso'] },
  { name: 'user-secret', label: 'Anonimato', category: 'technology', icon: faUserSecret, keywords: ['anónimo', 'privacidad', 'incógnito', 'seguridad'] },
  { name: 'user-lock', label: 'Cuenta protegida', category: 'technology', icon: faUserLock, keywords: ['usuario', 'bloqueo', 'privacidad', 'seguridad'] },
  { name: 'rss', label: 'Suscripción', category: 'technology', icon: faRss, keywords: ['rss', 'feed', 'suscripción', 'noticias'] },
] as const satisfies readonly AppIconEntry[]
