import {
  faBatteryFull,
  faBlog,
  faChargingStation,
  faCircleNodes,
  faCloud,
  faCloudArrowUp,
  faComputer,
  faComputerMouse,
  faDatabase,
  faDisplay,
  faFileCode,
  faFingerprint,
  faFloppyDisk,
  faGears,
  faHardDrive,
  faLaptopCode,
  faLink,
  faMicrochip,
  faMobileScreen,
  faNetworkWired,
  faQrcode,
  faRobot,
  faSatelliteDish,
  faServer,
  faShieldHalved,
  faTabletScreenButton,
  faTowerCell,
  faUserShield,
  faVrCardboard,
  faWandMagicSparkles,
  faWifi,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const technologyIcons = [
  { name: 'mobile', label: 'Móvil', category: 'technology', icon: faMobileScreen, keywords: ['mobile-screen', 'phone', 'smartphone', 'app', 'móvil', 'pantalla'] },
  { name: 'tablet', label: 'Tablet', category: 'technology', icon: faTabletScreenButton, keywords: ['tablet-screen-button', 'ipad', 'dispositivo', 'tableta'] },
  { name: 'wifi', label: 'WiFi', category: 'technology', icon: faWifi, keywords: ['internet', 'red', 'conexión', 'wifi', 'router'] },
  { name: 'database', label: 'Base de datos', category: 'technology', icon: faDatabase, keywords: ['sql', 'datos', 'storage', 'base de datos'] },
  { name: 'server', label: 'Servidor', category: 'technology', icon: faServer, keywords: ['backend', 'hosting', 'infra', 'servidor'] },
  { name: 'cloud', label: 'Nube', category: 'technology', icon: faCloud, keywords: ['cloud', 'sync', 'backup', 'calma', 'relajación', 'mindfulness', 'nube'] },
  { name: 'robot', label: 'Robot', category: 'technology', icon: faRobot, keywords: ['ia', 'ai', 'automation', 'bot', 'robot'] },
  { name: 'microchip', label: 'Chip', category: 'technology', icon: faMicrochip, keywords: ['hardware', 'cpu', 'electrónica', 'chip', 'procesador'] },
  { name: 'laptop-code', label: 'Desarrollo', category: 'technology', icon: faLaptopCode, keywords: ['coding', 'programación', 'dev', 'software', 'programar'] },
  { name: 'computer', label: 'Ordenador', category: 'technology', icon: faComputer, keywords: ['ordenador', 'pc', 'equipo', 'computer', 'sobremesa'] },
  { name: 'display', label: 'Pantalla', category: 'technology', icon: faDisplay, keywords: ['pantalla', 'monitor', 'screen', 'tiempo de pantalla'] },
  { name: 'computer-mouse', label: 'Ratón', category: 'technology', icon: faComputerMouse, keywords: ['ratón', 'mouse', 'periférico', 'clic'] },
  { name: 'hard-drive', label: 'Disco duro', category: 'technology', icon: faHardDrive, keywords: ['disco', 'almacenamiento', 'hdd', 'ssd', 'backup'] },
  { name: 'floppy-disk', label: 'Guardar', category: 'technology', icon: faFloppyDisk, keywords: ['guardar', 'save', 'disquete', 'copia'] },
  { name: 'cloud-arrow-up', label: 'Copia de seguridad', category: 'technology', icon: faCloudArrowUp, keywords: ['backup', 'subir', 'nube', 'sincronizar', 'copia'] },
  { name: 'network-wired', label: 'Red', category: 'technology', icon: faNetworkWired, keywords: ['red', 'network', 'cable', 'lan', 'conexión'] },
  { name: 'circle-nodes', label: 'Nodos', category: 'technology', icon: faCircleNodes, keywords: ['nodos', 'grafo', 'red', 'conexiones', 'sistema'] },
  { name: 'file-code', label: 'Código fuente', category: 'technology', icon: faFileCode, keywords: ['código', 'fichero', 'script', 'programar', 'source'] },
  { name: 'gears', label: 'Automatización', category: 'technology', icon: faGears, keywords: ['automatizar', 'engranajes', 'proceso', 'script', 'workflow'] },
  { name: 'wand-magic-sparkles', label: 'Inteligencia artificial', category: 'technology', icon: faWandMagicSparkles, keywords: ['ia', 'ai', 'magia', 'generar', 'prompt', 'automático'] },
  { name: 'qrcode', label: 'Código QR', category: 'technology', icon: faQrcode, keywords: ['qr', 'código', 'escanear', 'scan'] },
  { name: 'fingerprint', label: 'Huella digital', category: 'technology', icon: faFingerprint, keywords: ['huella', 'biometría', 'acceso', 'seguridad', 'desbloquear'] },
  { name: 'shield-halved', label: 'Seguridad', category: 'technology', icon: faShieldHalved, keywords: ['seguridad', 'escudo', 'protección', 'antivirus', 'security'] },
  { name: 'user-shield', label: 'Privacidad', category: 'technology', icon: faUserShield, keywords: ['privacidad', 'datos', 'protección', 'cuenta', 'contraseñas'] },
  { name: 'battery-full', label: 'Batería', category: 'technology', icon: faBatteryFull, keywords: ['batería', 'carga', 'energía', 'pila'] },
  { name: 'charging-station', label: 'Cargar', category: 'technology', icon: faChargingStation, keywords: ['cargar', 'carga', 'enchufar', 'batería', 'coche eléctrico'] },
  { name: 'satellite-dish', label: 'Antena', category: 'technology', icon: faSatelliteDish, keywords: ['antena', 'satélite', 'señal', 'parabólica'] },
  { name: 'tower-cell', label: 'Cobertura', category: 'technology', icon: faTowerCell, keywords: ['cobertura', 'antena', 'móvil', 'señal', '5g'] },
  { name: 'link', label: 'Enlace', category: 'technology', icon: faLink, keywords: ['enlace', 'link', 'url', 'web', 'compartir'] },
  { name: 'blog', label: 'Blog', category: 'technology', icon: faBlog, keywords: ['blog', 'artículo', 'publicar', 'escribir', 'web'] },
  { name: 'vr-cardboard', label: 'Realidad virtual', category: 'technology', icon: faVrCardboard, keywords: ['vr', 'realidad virtual', 'gafas', 'inmersivo', 'metaverso'] },
] as const satisfies readonly AppIconEntry[]
