import {
  faBoxArchive,
  faBriefcase,
  faBug,
  faBuilding,
  faBullhorn,
  faBusinessTime,
  faChartColumn,
  faClipboardCheck,
  faCode,
  faCodeBranch,
  faCodePullRequest,
  faComments,
  faDesktop,
  faDiagramProject,
  faFile,
  faFileLines,
  faFilePdf,
  faFileSignature,
  faFolder,
  faGavel,
  faHammer,
  faHandshake,
  faHeadset,
  faHelmetSafety,
  faHouseLaptop,
  faIdCardClip,
  faKeyboard,
  faLaptop,
  faMicrophone,
  faPen,
  faPencil,
  faPenRuler,
  faPenToSquare,
  faPersonChalkboard,
  faPersonDigging,
  faPhone,
  faPrint,
  faScrewdriverWrench,
  faSitemap,
  faTableList,
  faTerminal,
  faToolbox,
  faUserGroup,
  faUsers,
  faUserTie,
  faVideo,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const workIcons = [
  { name: 'briefcase', label: 'Trabajo', category: 'work', icon: faBriefcase, keywords: ['trabajo', 'office', 'job', 'business', 'oficina'] },
  { name: 'laptop', label: 'Portátil', category: 'work', icon: faLaptop, keywords: ['ordenador', 'computer', 'remoto', 'remote'] },
  { name: 'desktop', label: 'Escritorio', category: 'work', icon: faDesktop, keywords: ['pc', 'monitor', 'oficina'] },
  { name: 'keyboard', label: 'Teclado', category: 'work', icon: faKeyboard, keywords: ['escribir', 'typing', 'input'] },
  { name: 'code', label: 'Código', category: 'work', icon: faCode, keywords: ['coding', 'programación', 'dev', 'software'] },
  { name: 'terminal', label: 'Terminal', category: 'work', icon: faTerminal, keywords: ['cli', 'consola', 'shell', 'programación', 'coding', 'dev'] },
  { name: 'bug', label: 'Bug', category: 'work', icon: faBug, keywords: ['debug', 'error', 'incidencia'] },
  { name: 'folder', label: 'Carpeta', category: 'work', icon: faFolder, keywords: ['archivos', 'proyecto', 'documentos'] },
  { name: 'file', label: 'Archivo', category: 'work', icon: faFile, keywords: ['documento', 'fichero'] },
  { name: 'file-lines', label: 'Documento', category: 'work', icon: faFileLines, keywords: ['notas', 'informe', 'escritura'] },
  { name: 'diagram-project', label: 'Proyecto', category: 'work', icon: faDiagramProject, keywords: ['kanban', 'gestión', 'planificación'] },
  { name: 'screwdriver-wrench', label: 'Mantenimiento', category: 'work', icon: faScrewdriverWrench, keywords: ['reparar', 'tools', 'fix'] },
  { name: 'hammer', label: 'Construcción', category: 'work', icon: faHammer, keywords: ['build', 'maker', 'obra'] },
  { name: 'toolbox', label: 'Herramientas', category: 'work', icon: faToolbox, keywords: ['kit', 'utilidades', 'tools'] },
  { name: 'building', label: 'Empresa', category: 'work', icon: faBuilding, keywords: ['corporativo', 'oficina', 'negocio'] },
  { name: 'users', label: 'Equipo', category: 'social', icon: faUsers, keywords: ['colaboración', 'team', 'grupo', 'social'] },
  { name: 'user-group', label: 'Grupo', category: 'social', icon: faUserGroup, keywords: ['reunión', 'team', 'personas', 'social'] },
  { name: 'comments', label: 'Comentarios', category: 'social', icon: faComments, keywords: ['chat', 'feedback', 'mensajes', 'social'] },
  { name: 'phone', label: 'Teléfono', category: 'social', icon: faPhone, keywords: ['llamada', 'call', 'contacto', 'social'] },
  { name: 'video', label: 'Videollamada', category: 'work', icon: faVideo, keywords: ['reunión', 'meet', 'zoom', 'streaming'] },
  { name: 'microphone', label: 'Micrófono', category: 'work', icon: faMicrophone, keywords: ['audio', 'podcast', 'voz'] },
  { name: 'headset', label: 'Auricular', category: 'work', icon: faHeadset, keywords: ['soporte', 'call center', 'audio'] },
  { name: 'pen', label: 'Bolígrafo', category: 'work', icon: faPen, keywords: ['escribir', 'firma', 'notas'] },
  { name: 'pencil', label: 'Lápiz', category: 'work', icon: faPencil, keywords: ['dibujar', 'sketch', 'borrador'] },
  { name: 'edit', label: 'Editar', category: 'work', icon: faPenToSquare, keywords: ['pen', 'modificar', 'lapiz', 'escribir'] },
  { name: 'house-laptop', label: 'Teletrabajo', category: 'work', icon: faHouseLaptop, keywords: ['teletrabajo', 'remoto', 'remote', 'casa', 'home office'] },
  { name: 'person-chalkboard', label: 'Presentación', category: 'work', icon: faPersonChalkboard, keywords: ['presentación', 'exponer', 'charla', 'formación', 'demo'] },
  { name: 'chart-column', label: 'Informe', category: 'work', icon: faChartColumn, keywords: ['informe', 'report', 'barras', 'métricas', 'resultados'] },
  { name: 'table-list', label: 'Tabla', category: 'work', icon: faTableList, keywords: ['tabla', 'listado', 'datos', 'registro', 'hoja'] },
  { name: 'clipboard-check', label: 'Revisión', category: 'work', icon: faClipboardCheck, keywords: ['revisar', 'validar', 'checklist', 'aprobado', 'control'] },
  { name: 'sitemap', label: 'Organigrama', category: 'work', icon: faSitemap, keywords: ['organigrama', 'estructura', 'jerarquía', 'mapa', 'equipo'] },
  { name: 'handshake', label: 'Acuerdo', category: 'work', icon: faHandshake, keywords: ['acuerdo', 'trato', 'cliente', 'negociación', 'deal'] },
  { name: 'user-tie', label: 'Cliente', category: 'work', icon: faUserTie, keywords: ['cliente', 'jefe', 'traje', 'negocio', 'ejecutivo'] },
  { name: 'business-time', label: 'Jornada', category: 'work', icon: faBusinessTime, keywords: ['jornada', 'horario', 'trabajo', 'fichar', 'oficina'] },
  { name: 'print', label: 'Imprimir', category: 'work', icon: faPrint, keywords: ['imprimir', 'impresora', 'papel', 'documento'] },
  { name: 'file-signature', label: 'Firmar', category: 'work', icon: faFileSignature, keywords: ['firma', 'firmar', 'contrato', 'documento', 'trámite'] },
  { name: 'file-pdf', label: 'PDF', category: 'work', icon: faFilePdf, keywords: ['pdf', 'documento', 'archivo', 'informe'] },
  { name: 'box-archive', label: 'Archivar', category: 'work', icon: faBoxArchive, keywords: ['archivar', 'archivo', 'guardar', 'caja', 'histórico'] },
  { name: 'bullhorn', label: 'Anuncio', category: 'work', icon: faBullhorn, keywords: ['anuncio', 'comunicar', 'marketing', 'megáfono', 'difundir'] },
  { name: 'gavel', label: 'Legal', category: 'work', icon: faGavel, keywords: ['legal', 'abogado', 'martillo', 'juicio', 'normativa'] },
  { name: 'id-card-clip', label: 'Credencial', category: 'work', icon: faIdCardClip, keywords: ['credencial', 'acreditación', 'identificación', 'empleado', 'badge'] },
  { name: 'helmet-safety', label: 'Seguridad laboral', category: 'work', icon: faHelmetSafety, keywords: ['casco', 'seguridad', 'obra', 'prevención', 'epi'] },
  { name: 'person-digging', label: 'Obra', category: 'work', icon: faPersonDigging, keywords: ['obra', 'cavar', 'construcción', 'trabajo manual', 'reforma'] },
  { name: 'code-branch', label: 'Rama de código', category: 'work', icon: faCodeBranch, keywords: ['git', 'rama', 'branch', 'versión', 'dev'] },
  { name: 'code-pull-request', label: 'Pull request', category: 'work', icon: faCodePullRequest, keywords: ['pull request', 'pr', 'revisión de código', 'git', 'merge'] },
  { name: 'pen-ruler', label: 'Diseño', category: 'work', icon: faPenRuler, keywords: ['diseño', 'design', 'maqueta', 'boceto', 'ux'] },
] as const satisfies readonly AppIconEntry[]
