import {
  faBellConcierge,
  faBoxArchive,
  faBoxesPacking,
  faBriefcase,
  faBug,
  faBuilding,
  faBuildingUser,
  faBullhorn,
  faBusinessTime,
  faChartColumn,
  faCity,
  faClipboardCheck,
  faClipboardUser,
  faCode,
  faCodeBranch,
  faCodePullRequest,
  faComments,
  faDesktop,
  faDiagramProject,
  faDolly,
  faFile,
  faFileCsv,
  faFileExcel,
  faFileExport,
  faFileImport,
  faFileInvoice,
  faFileLines,
  faFilePdf,
  faFilePowerpoint,
  faFileSignature,
  faFileWord,
  faFolder,
  faGavel,
  faHammer,
  faHandshake,
  faHeadset,
  faHelmetSafety,
  faHouseLaptop,
  faIdBadge,
  faIdCardClip,
  faIndustry,
  faKeyboard,
  faLaptop,
  faMicrophone,
  faOilCan,
  faPallet,
  faPen,
  faPencil,
  faPenRuler,
  faPenToSquare,
  faPersonChalkboard,
  faPersonDigging,
  faPhone,
  faPrint,
  faRectangleAd,
  faScrewdriverWrench,
  faSignsPost,
  faSitemap,
  faStapler,
  faStore,
  faSuitcase,
  faTableList,
  faTerminal,
  faToolbox,
  faTractor,
  faTrowelBricks,
  faTruck,
  faTruckFast,
  faUserClock,
  faUserGear,
  faUserGroup,
  faUsers,
  faUsersGear,
  faUserTie,
  faVideo,
  faWarehouse,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const workIcons = [
  { name: 'briefcase', label: 'Trabajo', category: 'work', icon: faBriefcase, keywords: ['trabajo', 'office', 'job', 'business', 'oficina'] },
  { name: 'laptop', label: 'Portátil', category: 'work', icon: faLaptop, keywords: ['ordenador', 'computer', 'remoto', 'remote'] },
  { name: 'desktop', label: 'Escritorio', category: 'work', icon: faDesktop, keywords: ['pc', 'monitor', 'oficina'] },
  { name: 'keyboard', label: 'Teclado', category: 'work', icon: faKeyboard, keywords: ['escribir', 'typing', 'input'] },
  { name: 'code', label: 'Código', category: 'work', icon: faCode, keywords: ['coding', 'programación', 'dev', 'software'] },
  { name: 'terminal', label: 'Terminal', category: 'work', icon: faTerminal, keywords: ['cli', 'consola', 'shell', 'programación', 'coding', 'dev'] },
  { name: 'bug', label: 'Bug', category: 'work', icon: faBug, keywords: ['debug', 'error', 'incidencia'] },
  { name: 'folder', label: 'Carpeta', category: 'work', icon: faFolder, keywords: ['archivos', 'proyecto', 'documentos'] },
  { name: 'file', label: 'Archivo', category: 'work', icon: faFile, keywords: ['documento', 'fichero'] },
  { name: 'file-lines', label: 'Documento', category: 'work', icon: faFileLines, keywords: ['notas', 'informe', 'escritura'] },
  { name: 'diagram-project', label: 'Proyecto', category: 'work', icon: faDiagramProject, keywords: ['kanban', 'gestión', 'planificación'] },
  { name: 'screwdriver-wrench', label: 'Mantenimiento', category: 'work', icon: faScrewdriverWrench, keywords: ['reparar', 'tools', 'fix'] },
  { name: 'hammer', label: 'Construcción', category: 'work', icon: faHammer, keywords: ['build', 'maker', 'obra'] },
  { name: 'toolbox', label: 'Herramientas', category: 'work', icon: faToolbox, keywords: ['kit', 'utilidades', 'tools'] },
  { name: 'building', label: 'Empresa', category: 'work', icon: faBuilding, keywords: ['corporativo', 'oficina', 'negocio'] },
  { name: 'users', label: 'Equipo', category: 'social', icon: faUsers, keywords: ['colaboración', 'team', 'grupo', 'social'] },
  { name: 'user-group', label: 'Grupo', category: 'social', icon: faUserGroup, keywords: ['reunión', 'team', 'personas', 'social'] },
  { name: 'comments', label: 'Comentarios', category: 'social', icon: faComments, keywords: ['chat', 'feedback', 'mensajes', 'social'] },
  { name: 'phone', label: 'Teléfono', category: 'social', icon: faPhone, keywords: ['llamada', 'call', 'contacto', 'social'] },
  { name: 'video', label: 'Videollamada', category: 'work', icon: faVideo, keywords: ['reunión', 'meet', 'zoom', 'streaming'] },
  { name: 'microphone', label: 'Micrófono', category: 'work', icon: faMicrophone, keywords: ['audio', 'podcast', 'voz'] },
  { name: 'headset', label: 'Auricular', category: 'work', icon: faHeadset, keywords: ['soporte', 'call center', 'audio'] },
  { name: 'pen', label: 'Bolígrafo', category: 'work', icon: faPen, keywords: ['escribir', 'firma', 'notas'] },
  { name: 'pencil', label: 'Lápiz', category: 'work', icon: faPencil, keywords: ['dibujar', 'sketch', 'borrador'] },
  { name: 'edit', label: 'Editar', category: 'work', icon: faPenToSquare, keywords: ['pen', 'modificar', 'lapiz', 'escribir'] },
  { name: 'house-laptop', label: 'Teletrabajo', category: 'work', icon: faHouseLaptop, keywords: ['teletrabajo', 'remoto', 'remote', 'casa', 'home office'] },
  { name: 'person-chalkboard', label: 'Presentación', category: 'work', icon: faPersonChalkboard, keywords: ['presentación', 'exponer', 'charla', 'formación', 'demo'] },
  { name: 'chart-column', label: 'Informe', category: 'work', icon: faChartColumn, keywords: ['informe', 'report', 'barras', 'métricas', 'resultados'] },
  { name: 'table-list', label: 'Tabla', category: 'work', icon: faTableList, keywords: ['tabla', 'listado', 'datos', 'registro', 'hoja'] },
  { name: 'clipboard-check', label: 'Revisión', category: 'work', icon: faClipboardCheck, keywords: ['revisar', 'validar', 'checklist', 'aprobado', 'control'] },
  { name: 'sitemap', label: 'Organigrama', category: 'work', icon: faSitemap, keywords: ['organigrama', 'estructura', 'jerarquía', 'mapa', 'equipo'] },
  { name: 'handshake', label: 'Acuerdo', category: 'work', icon: faHandshake, keywords: ['acuerdo', 'trato', 'cliente', 'negociación', 'deal'] },
  { name: 'user-tie', label: 'Cliente', category: 'work', icon: faUserTie, keywords: ['cliente', 'jefe', 'traje', 'negocio', 'ejecutivo'] },
  { name: 'business-time', label: 'Jornada', category: 'work', icon: faBusinessTime, keywords: ['jornada', 'horario', 'trabajo', 'fichar', 'oficina'] },
  { name: 'print', label: 'Imprimir', category: 'work', icon: faPrint, keywords: ['imprimir', 'impresora', 'papel', 'documento'] },
  { name: 'file-signature', label: 'Firmar', category: 'work', icon: faFileSignature, keywords: ['firma', 'firmar', 'contrato', 'documento', 'trámite'] },
  { name: 'file-pdf', label: 'PDF', category: 'work', icon: faFilePdf, keywords: ['pdf', 'documento', 'archivo', 'informe'] },
  { name: 'box-archive', label: 'Archivar', category: 'work', icon: faBoxArchive, keywords: ['archivar', 'archivo', 'guardar', 'caja', 'histórico'] },
  { name: 'bullhorn', label: 'Anuncio', category: 'work', icon: faBullhorn, keywords: ['anuncio', 'comunicar', 'marketing', 'megáfono', 'difundir'] },
  { name: 'gavel', label: 'Legal', category: 'work', icon: faGavel, keywords: ['legal', 'abogado', 'martillo', 'juicio', 'normativa'] },
  { name: 'id-card-clip', label: 'Credencial', category: 'work', icon: faIdCardClip, keywords: ['credencial', 'acreditación', 'identificación', 'empleado', 'badge'] },
  { name: 'helmet-safety', label: 'Seguridad laboral', category: 'work', icon: faHelmetSafety, keywords: ['casco', 'seguridad', 'obra', 'prevención', 'epi'] },
  { name: 'person-digging', label: 'Obra', category: 'work', icon: faPersonDigging, keywords: ['obra', 'cavar', 'construcción', 'trabajo manual', 'reforma'] },
  { name: 'code-branch', label: 'Rama de código', category: 'work', icon: faCodeBranch, keywords: ['git', 'rama', 'branch', 'versión', 'dev'] },
  { name: 'code-pull-request', label: 'Pull request', category: 'work', icon: faCodePullRequest, keywords: ['pull request', 'pr', 'revisión de código', 'git', 'merge'] },
  { name: 'pen-ruler', label: 'Diseño', category: 'work', icon: faPenRuler, keywords: ['diseño', 'design', 'maqueta', 'boceto', 'ux'] },
  { name: 'industry', label: 'Industria', category: 'work', icon: faIndustry, keywords: ['fábrica', 'industria', 'planta', 'producción'] },
  { name: 'warehouse', label: 'Almacén', category: 'work', icon: faWarehouse, keywords: ['almacén', 'inventario', 'stock', 'nave'] },
  { name: 'store', label: 'Tienda', category: 'work', icon: faStore, keywords: ['tienda', 'comercio', 'negocio', 'local'] },
  { name: 'suitcase', label: 'Maletín', category: 'work', icon: faSuitcase, keywords: ['maletín', 'viaje de trabajo', 'equipaje', 'negocio'] },
  { name: 'id-badge', label: 'Credencial', category: 'work', icon: faIdBadge, keywords: ['credencial', 'acreditación', 'identificación', 'trabajo'] },
  { name: 'user-clock', label: 'Fichar', category: 'work', icon: faUserClock, keywords: ['fichar', 'horario', 'jornada', 'control horario'] },
  { name: 'user-gear', label: 'Perfil de trabajo', category: 'work', icon: faUserGear, keywords: ['usuario', 'ajustes', 'perfil', 'configurar'] },
  { name: 'users-gear', label: 'Gestionar equipo', category: 'work', icon: faUsersGear, keywords: ['equipo', 'gestionar', 'personas', 'configurar'] },
  { name: 'clipboard-user', label: 'Ficha de persona', category: 'work', icon: faClipboardUser, keywords: ['ficha', 'expediente', 'persona', 'informe'] },
  { name: 'building-user', label: 'Oficina', category: 'work', icon: faBuildingUser, keywords: ['oficina', 'empresa', 'despacho', 'edificio'] },
  { name: 'city', label: 'Ciudad', category: 'work', icon: faCity, keywords: ['ciudad', 'oficinas', 'urbano', 'empresa'] },
  { name: 'truck', label: 'Reparto', category: 'work', icon: faTruck, keywords: ['camión', 'reparto', 'transporte', 'logística'] },
  { name: 'truck-fast', label: 'Envío rápido', category: 'work', icon: faTruckFast, keywords: ['envío', 'urgente', 'reparto', 'logística'] },
  { name: 'dolly', label: 'Carretilla', category: 'work', icon: faDolly, keywords: ['carretilla', 'carga', 'almacén', 'mudanza'] },
  { name: 'pallet', label: 'Palé', category: 'work', icon: faPallet, keywords: ['palé', 'carga', 'almacén', 'stock'] },
  { name: 'boxes-packing', label: 'Empaquetar', category: 'work', icon: faBoxesPacking, keywords: ['empaquetar', 'cajas', 'pedido', 'envío'] },
  { name: 'tractor', label: 'Tractor', category: 'work', icon: faTractor, keywords: ['tractor', 'campo', 'agricultura', 'granja'] },
  { name: 'trowel-bricks', label: 'Albañilería', category: 'work', icon: faTrowelBricks, keywords: ['albañil', 'obra', 'ladrillo', 'construcción'] },
  { name: 'oil-can', label: 'Mantenimiento', category: 'work', icon: faOilCan, keywords: ['aceite', 'mantenimiento', 'engrasar', 'taller'] },
  { name: 'signs-post', label: 'Señalizar', category: 'work', icon: faSignsPost, keywords: ['señal', 'indicaciones', 'dirección', 'cartel'] },
  { name: 'bell-concierge', label: 'Recepción', category: 'work', icon: faBellConcierge, keywords: ['recepción', 'atención', 'timbre', 'servicio'] },
  { name: 'file-invoice', label: 'Factura', category: 'work', icon: faFileInvoice, keywords: ['factura', 'cobrar', 'documento', 'cliente'] },
  { name: 'file-csv', label: 'Datos en CSV', category: 'work', icon: faFileCsv, keywords: ['csv', 'datos', 'exportar', 'tabla'] },
  { name: 'file-excel', label: 'Hoja de cálculo', category: 'work', icon: faFileExcel, keywords: ['excel', 'hoja', 'datos', 'informe'] },
  { name: 'file-word', label: 'Documento de texto', category: 'work', icon: faFileWord, keywords: ['word', 'documento', 'informe', 'texto'] },
  { name: 'file-powerpoint', label: 'Presentación', category: 'work', icon: faFilePowerpoint, keywords: ['presentación', 'diapositivas', 'exponer', 'charla'] },
  { name: 'file-export', label: 'Exportar', category: 'work', icon: faFileExport, keywords: ['exportar', 'enviar', 'archivo', 'datos'] },
  { name: 'file-import', label: 'Importar', category: 'work', icon: faFileImport, keywords: ['importar', 'cargar', 'archivo', 'datos'] },
  { name: 'rectangle-ad', label: 'Publicidad', category: 'work', icon: faRectangleAd, keywords: ['anuncio', 'publicidad', 'campaña', 'marketing'] },
  { name: 'stapler', label: 'Grapadora', category: 'work', icon: faStapler, keywords: ['grapar', 'papeles', 'oficina', 'archivar'] },
] as const satisfies readonly AppIconEntry[]
