import {
  faBriefcase,
  faBuilding,
  faBug,
  faCode,
  faComments,
  faDesktop,
  faDiagramProject,
  faFile,
  faFileLines,
  faFolder,
  faHammer,
  faHeadset,
  faKeyboard,
  faLaptop,
  faMicrophone,
  faPen,
  faPenToSquare,
  faPencil,
  faPhone,
  faScrewdriverWrench,
  faTerminal,
  faToolbox,
  faUsers,
  faUserGroup,
  faVideo,
} from '@fortawesome/free-solid-svg-icons'
import type { AppIconEntry } from '@/shared/icons/types'

export const workIcons = [
  { name: 'briefcase', label: 'Trabajo', category: 'work', icon: faBriefcase, keywords: ['trabajo', 'office', 'job', 'business', 'oficina'] },
  { name: 'laptop', label: 'Portátil', category: 'work', icon: faLaptop, keywords: ['ordenador', 'computer', 'remoto', 'remote'] },
  { name: 'desktop', label: 'Escritorio', category: 'work', icon: faDesktop, keywords: ['pc', 'monitor', 'oficina'] },
  { name: 'keyboard', label: 'Teclado', category: 'work', icon: faKeyboard, keywords: ['escribir', 'typing', 'input'] },
  { name: 'code', label: 'Código', category: 'work', icon: faCode, keywords: ['coding', 'programación', 'dev', 'software'] },
  { name: 'terminal', label: 'Terminal', category: 'work', icon: faTerminal, keywords: ['cli', 'consola', 'shell', 'programación', 'coding', 'dev'] },
  { name: 'bug', label: 'Bug', category: 'work', icon: faBug, keywords: ['debug', 'error', 'incidencia'] },
  { name: 'folder', label: 'Carpeta', category: 'work', icon: faFolder, keywords: ['archivos', 'proyecto', 'documentos'] },
  { name: 'file', label: 'Archivo', category: 'work', icon: faFile, keywords: ['documento', 'fichero'] },
  { name: 'file-lines', label: 'Documento', category: 'work', icon: faFileLines, keywords: ['notas', 'informe', 'escritura'] },
  { name: 'diagram-project', label: 'Proyecto', category: 'work', icon: faDiagramProject, keywords: ['kanban', 'gestión', 'planificación'] },
  { name: 'screwdriver-wrench', label: 'Mantenimiento', category: 'work', icon: faScrewdriverWrench, keywords: ['reparar', 'tools', 'fix'] },
  { name: 'hammer', label: 'Construcción', category: 'work', icon: faHammer, keywords: ['build', 'maker', 'obra'] },
  { name: 'toolbox', label: 'Herramientas', category: 'work', icon: faToolbox, keywords: ['kit', 'utilidades', 'tools'] },
  { name: 'building', label: 'Empresa', category: 'work', icon: faBuilding, keywords: ['corporativo', 'oficina', 'negocio'] },
  { name: 'users', label: 'Equipo', category: 'social', icon: faUsers, keywords: ['colaboración', 'team', 'grupo', 'social'] },
  { name: 'user-group', label: 'Grupo', category: 'social', icon: faUserGroup, keywords: ['reunión', 'team', 'personas', 'social'] },
  { name: 'comments', label: 'Comentarios', category: 'social', icon: faComments, keywords: ['chat', 'feedback', 'mensajes', 'social'] },
  { name: 'phone', label: 'Teléfono', category: 'social', icon: faPhone, keywords: ['llamada', 'call', 'contacto', 'social'] },
  { name: 'video', label: 'Videollamada', category: 'work', icon: faVideo, keywords: ['reunión', 'meet', 'zoom', 'streaming'] },
  { name: 'microphone', label: 'Micrófono', category: 'work', icon: faMicrophone, keywords: ['audio', 'podcast', 'voz'] },
  { name: 'headset', label: 'Auricular', category: 'work', icon: faHeadset, keywords: ['soporte', 'call center', 'audio'] },
  { name: 'pen', label: 'Bolígrafo', category: 'work', icon: faPen, keywords: ['escribir', 'firma', 'notas'] },
  { name: 'pencil', label: 'Lápiz', category: 'work', icon: faPencil, keywords: ['dibujar', 'sketch', 'borrador'] },
  { name: 'edit', label: 'Editar', category: 'work', icon: faPenToSquare, keywords: ['pen', 'modificar', 'lapiz', 'escribir'] },
] as const satisfies readonly AppIconEntry[]
